-- Lane B B11.2 — auth_step_up_challenges table.
--
-- Authority:
--   * docs/archive/_execution/lane_b_features/03_execution_slices.md
--     ("B11.2 — RFC 9470 step-up challenge on sensitive routes")
--   * RFC 9470 — OAuth 2.0 Step Up Authentication Challenge Protocol
--     https://www.rfc-editor.org/rfc/rfc9470
--   * CLAUDE.md "Hard Promises" #4 (per-operator isolation NON-NEGOTIABLE)
--   * CLAUDE.md "RLS-Ready Schema" — operator-scoped fact tables include
--     (operator_id, location_id) + RLS policy stub from creation; every
--     fact-table B-tree index leads with operator_id; RLS policies use
--     the four STABLE LEAKPROOF PARALLEL SAFE wrapper functions; bare
--     current_setting() reads forbidden.
--   * CLAUDE.md "Time Guardrails" — operator-scoped tables MUST use
--     TIMESTAMPTZ.
--   * docs/contracts/hardening_rls_and_repository_pattern_contract.md
--     (wrapper-only RLS posture; SET LOCAL transaction-scoped tenant
--      injection via OperatorScopedRepository.)
--   * B11.1 precedent: 202605131030_b11_1_auth_handoff_codes.sql
--     (mirrored idiom for opaque code/hash, TTL check constraint,
--      operator-leading B-tree indexes, wrapper-only RLS, idempotent
--      DDL).
--
-- Adds public.auth_step_up_challenges — one row per emitted RFC 9470
-- step-up challenge. A challenge is created when a caller hits a
-- flagged sensitive route with a JWT whose `auth_time` (the
-- `lastFreshAuthAt` claim in ProxyJwtClaims) is older than the
-- route's required freshness window or whose `acr` does not meet the
-- route's required acr level. The proxy returns 401 with a
-- `WWW-Authenticate: Bearer error="insufficient_user_authentication",
-- acr_values="<required>", max_age=<seconds>` header per RFC 9470 §4.
-- The client (mobile or web) re-authenticates and replays with a
-- fresher JWT. The proxy verifies the freshness/acr now meets the
-- route's policy AND consumes the matching challenge row (marks
-- `consumed_at`). Consumption is one-shot so a replay of the same
-- challenge_id by a stolen device gets 410 Gone.
--
-- Schema notes:
--   * challenge_id text primary key — opaque, server-generated by
--     gen_random_bytes(16) via pgcrypto. 22-char base64-url body
--     gives ~128 bits of entropy. Matches the B11.1 idiom.
--   * route_path stores the path the challenge was emitted on so the
--     replay can be cross-checked: a challenge issued for
--     `/v1/auth/password/change` cannot be replayed against
--     `/v1/admin/auth/roles/...`. Length-bounded (1..256) to match
--     the longest path constant in advisor_proxy.dart.
--   * required_acr names the acr value the proxy demanded (today the
--     only emitted value is `urn:mfa` per the slice doc; the column
--     is text so future levels — e.g. `urn:mfa:totp` or
--     `urn:mfa:webauthn` — can land without a migration).
--   * required_freshness_seconds carries the route's freshness budget
--     (today 300 s for password/mfa/role mutations per the slice doc;
--     the per-route registry in tool/advisor_proxy/auth_step_up_routes.dart
--     is the source of truth, the column persists the value that was
--     in effect at challenge time for audit replay).
--   * expires_at = created_at + interval (route's challenge_ttl).
--     5-minute default; 15-minute hard ceiling (the CHECK below
--     enforces the ceiling so a buggy emitter cannot mint a forever
--     challenge).
--   * consumed_at marks one-shot consumption; the redeem predicate
--     (consumed_at IS NULL AND expires_at > now() AND
--     route_path = $route) refuses replays.
--   * source_actor_kind / source_actor_id records the caller that
--     received the challenge so the audit reader can correlate
--     "challenge issued" -> "challenge consumed" across two
--     separate auth contexts when a service principal escalates.
--   * source_device_fingerprint is the device that received the
--     challenge (parallel to handoff_codes.source_device_fingerprint).
--
-- Hard rules carried verbatim from CLAUDE.md / phase docs:
--
--   * HP #4 RLS-Ready Schema. Table carries (operator_id, location_id)
--     from creation; tenant-leading B-tree indexes; per-tenant RLS
--     policy enabled at table-creation time using the wrapper function
--     `app_current_operator()`. No bare current_setting() reads.
--   * Wrapper-only RLS posture. Policy body calls
--     public.app_current_operator(). The four wrapper functions are
--     STABLE LEAKPROOF PARALLEL SAFE so the planner can fold them into
--     index scans.
--   * Time guardrails. All temporal columns are TIMESTAMPTZ.
--     created_at, expires_at, consumed_at — all UTC instants, never
--     wall-clock TIMESTAMP WITHOUT TIME ZONE.
--   * Idempotent migration. if not exists on every CREATE,
--     drop policy if exists before create policy. Re-applying the
--     migration is a no-op.
--   * No client-side challenge_id. The opaque id is generated server-
--     side via encode(gen_random_bytes(16), 'base64'), stripped of
--     URL-unsafe characters by the application before storage.
--     Clients never supply a candidate id.
--
-- Service principal note (CLAUDE.md "Service principals"):
--   * `actor_kind` taxonomy applies. Service principals (`sp:`-prefixed
--     JWT subjects) MAY be subject to step-up rules in the future, but
--     for V1 the policy in tool/advisor_proxy/auth_step_up_routes.dart
--     SKIPS challenge emission when actor_kind == 'service_principal'
--     because service principals do not have an interactive MFA flow.
--     The column is still populated when a challenge IS issued (e.g.
--     when a future policy admits SP step-up via mTLS reauth) so the
--     audit reader can attribute the challenge.
--
-- Operator approval gate: per CLAUDE.md "agent-led slices" — auth-
-- critical, RLS-touching, schema-touching, and proxy-touching slices
-- require explicit operator approval before merge regardless of audit
-- verdict.

begin;

-- pgcrypto already required by audit_logs (202604280005) and by B11.1
-- handoff_codes (202605131030); listed here for explicitness because
-- gen_random_bytes() is the entropy source for the opaque
-- challenge_id.
create extension if not exists pgcrypto;

-- ─── auth_step_up_challenges ──────────────────────────────────────
create table if not exists public.auth_step_up_challenges (
  challenge_id                text primary key,
  operator_id                 uuid not null,
  location_id                 uuid not null,
  user_id                     uuid not null,
  route_path                  text not null
                              check (char_length(route_path) between 1 and 256),
  required_acr                text not null
                              check (char_length(required_acr) between 1 and 64),
  required_freshness_seconds  integer not null
                              check (
                                required_freshness_seconds > 0
                                and required_freshness_seconds <= 3600
                              ),
  expires_at                  timestamptz not null,
  consumed_at                 timestamptz null,
  source_actor_kind           text not null
                              check (char_length(source_actor_kind) between 1 and 32),
  source_device_fingerprint   text null,
  created_at                  timestamptz not null default now(),
  -- Challenge TTL: positive lifespan, hard ceiling 15 minutes. The
  -- slice's default is 5 minutes; the ceiling here keeps a buggy
  -- emitter from minting a forever-challenge that a replay attacker
  -- could pocket.
  constraint auth_step_up_challenges_ttl_chk check (
    expires_at > created_at
    and expires_at <= created_at + interval '15 minutes'
  ),
  -- Challenge id shape: base64-url body of gen_random_bytes(16) +/-
  -- a small slop. Reject malformed shapes so a buggy emit path
  -- cannot smuggle a too-short or non-URL-safe id into the table.
  constraint auth_step_up_challenges_id_shape_chk check (
    char_length(challenge_id) between 22 and 64
    and challenge_id ~ '^[A-Za-z0-9_-]+$'
  )
);

comment on table public.auth_step_up_challenges is
  'Lane B B11.2 — operator-scoped RFC 9470 step-up challenges. Proxy '
  'emits a row when a caller hits a sensitive route with stale '
  'auth_time or insufficient acr; 401 + WWW-Authenticate carries the '
  'challenge_id. Client re-auths and replays; proxy consumes the row '
  '(consumed_at = now()) and admits the request. Per-operator RLS: '
  '(operator_id = app_current_operator()).';

comment on column public.auth_step_up_challenges.challenge_id is
  'Opaque server-generated challenge id. Body is base64-url of '
  'gen_random_bytes(16) (~128 bits of entropy). Primary key.';

comment on column public.auth_step_up_challenges.operator_id is
  'Operator the challenged JWT was scoped to. RLS clamps reads + '
  'writes to this tenant; the consume predicate also re-asserts '
  '(operator_id = app_current_operator()).';

comment on column public.auth_step_up_challenges.location_id is
  'Location the challenged JWT was scoped to. Carried so the consume '
  'gateway can run through the tenant transaction wrapper, which '
  'requires both operator_id and location_id to issue SET LOCAL.';

comment on column public.auth_step_up_challenges.user_id is
  'JWT subject of the human who received the challenge. The replay '
  'must resolve to the same user.';

comment on column public.auth_step_up_challenges.route_path is
  'The proxy path the challenge was emitted on. The consume predicate '
  'compares the inbound route to this column so a challenge issued '
  'for /v1/auth/password/change cannot be replayed against an admin '
  'role-mutation route.';

comment on column public.auth_step_up_challenges.required_acr is
  'The acr value the proxy demanded (RFC 9470 acr_values). V1 emits '
  '"urn:mfa". Future levels (e.g. "urn:mfa:totp", "urn:mfa:webauthn") '
  'land without a migration.';

comment on column public.auth_step_up_challenges.required_freshness_seconds is
  'The max_age the proxy demanded (RFC 9470 max_age). Persists the '
  'value that was in effect when the challenge was minted so the '
  'audit reader sees the exact policy in force at emit time.';

comment on column public.auth_step_up_challenges.expires_at is
  'Challenge TTL boundary. The consume predicate (expires_at > now()) '
  'rejects late replays. Default 5 minutes; hard ceiling 15 minutes '
  'enforced by auth_step_up_challenges_ttl_chk.';

comment on column public.auth_step_up_challenges.consumed_at is
  'Set by the atomic UPDATE ... RETURNING in the consume handler. '
  'NULL until first successful replay; NOT NULL afterwards. Replays '
  'return 410 because the predicate (consumed_at IS NULL) no longer '
  'matches.';

comment on column public.auth_step_up_challenges.source_actor_kind is
  'actor_kind of the caller that received the challenge ("user", '
  '"service_principal", etc.). Mirrors audit_logs.actor_kind so the '
  'audit reader can correlate challenge issuance to the responsible '
  'actor class.';

comment on column public.auth_step_up_challenges.source_device_fingerprint is
  'Device fingerprint of the caller that received the challenge '
  '(parallel to handoff_codes.source_device_fingerprint). Optional.';

-- Operator-leading B-tree indexes per CI lint (CLAUDE.md hard rule —
-- "every fact-table B-tree index leads with operator_id" enforced by
-- tool/index_leading_column_lint.dart).

-- Consume / replay lookup keys on the PK (challenge_id), which already
-- has a unique index. RLS adds the operator predicate that the
-- planner folds into the PK lookup; no separate index needed for that
-- read path.

-- Reaper sweep + per-user audit list are operator-scoped; the optimal
-- index is (operator_id, expires_at) with a partial filter on
-- consumed_at IS NULL so the working set stays tiny.
create index if not exists auth_step_up_challenges_operator_expires_at_active_idx
  on public.auth_step_up_challenges (operator_id, expires_at)
  where consumed_at is null;

-- Per-user replay-correlate read in the audit log surface.
-- (operator_id, user_id, created_at desc) keeps the index small and
-- supports the "show me my last N step-up challenges" view.
create index if not exists auth_step_up_challenges_operator_user_idx
  on public.auth_step_up_challenges (operator_id, user_id, created_at desc);

-- RLS — wrapper-only per Phase 9.0Σ.b item 4. Per-operator policy
-- using the STABLE LEAKPROOF PARALLEL SAFE wrapper from
-- 202604280000_phase_9_0sigma_b_rls_wrappers.sql. Bare current_setting
-- reads are forbidden (rls_policy_lint enforces this).
alter table public.auth_step_up_challenges enable row level security;

drop policy if exists "auth_step_up_challenges_per_operator"
  on public.auth_step_up_challenges;
create policy "auth_step_up_challenges_per_operator"
  on public.auth_step_up_challenges for all to service_role
  using (
    operator_id = public.app_current_operator()
  )
  with check (
    operator_id = public.app_current_operator()
  );

-- Grants. Runtime (service_role) needs full DML for emit, consume,
-- and the reaper sweep. forge_admin gets read for ops visibility (the
-- forge admin console can render a per-operator challenge list to
-- diagnose step-up loops).
revoke all on public.auth_step_up_challenges from public;
grant select, insert, update, delete
  on public.auth_step_up_challenges to service_role;
grant select, delete
  on public.auth_step_up_challenges to forge_admin;

commit;
