-- Lane B B2.1 — default_role_catalog_versions table + operators pointer.
--
-- Authority:
--   * docs/_execution/lane_b_features/03_execution_slices.md
--     ("B2.1 — Default Role catalog schema + publish endpoint")
--   * CLAUDE.md "Hard Promises" #4 (per-operator isolation NON-NEGOTIABLE)
--   * CLAUDE.md "RLS-Ready Schema" — operator-scoped fact tables include
--     (operator_id, location_id) + RLS policy stub from creation. THIS
--     TABLE IS NOT OPERATOR-SCOPED — see "Why no RLS" below.
--   * CLAUDE.md "Time Guardrails" — all temporal columns are TIMESTAMPTZ.
--   * docs/contracts/hardening_rls_and_repository_pattern_contract.md
--     (admin-pool BYPASSRLS posture for non-tenant tables; SET LOCAL
--      ROLE forge_admin via TenantTransactionWrapper.runAsSystem.)
--   * Precedent: 202604280004_phase_9_0sigma_d_service_principals.sql
--     (operator-scoped catalog of admin actors) for the admin DML grants
--     shape, and 202605131030_b11_1_auth_handoff_codes.sql for the
--     idempotent DDL idiom.
--
-- Why this exists
-- ---------------
-- The Default Role catalog is the F&F-wide "starter set" of role
-- definitions every operator inherits at signup. Today this catalog is
-- hard-coded in application code; F&F admins cannot rotate it without
-- a deploy. B2.1 introduces a versioned catalog (publish-with-rollback)
-- so admins can ship catalog updates without code deploys, and so we
-- can audit who published which version with what blast radius.
--
-- B2.2 (separate slice) ships the admin editor UI; this migration is
-- the persistence shape only.
--
-- Schema notes
-- ------------
--   * version_id uuid PK — server-generated by gen_random_uuid().
--   * version_number int — monotonically incrementing per publish. The
--     repository computes it via MAX(version_number)+1 inside the
--     publish transaction; the partial unique index on is_current keeps
--     a single row globally as the "current" version.
--   * published_at timestamptz — UTC instant; never wall-clock.
--   * published_by_user_id uuid — the F&F admin who issued the publish.
--     References public.users(user_id) so deletion of the user account
--     cascades to ON DELETE RESTRICT — we intentionally preserve audit
--     attribution.
--   * payload jsonb — serialized catalog (the role definitions array).
--     Stored verbatim as published so a rollback is a byte-identical
--     replay of an earlier version. CHECK: jsonb_typeof = 'array' so
--     a malformed publish body cannot land.
--   * payload_sha256 text — SHA-256 hex of canonical payload. Computed
--     application-side at publish time and persisted so the audit row +
--     downstream readers can verify the catalog they're looking at
--     matches the published bytes. CHECK: 64-char lowercase hex.
--   * is_current boolean — partial UNIQUE INDEX where is_current = true
--     enforces "at most one current version globally" without a hand-
--     written CHECK or trigger. New publishes flip the old current to
--     false in the same transaction (see publishVersion in the repo).
--   * superseded_at timestamptz nullable — stamped at the moment a
--     newer version takes over. NULL while the row is current; a row
--     that never publishes a successor never sets this column.
--   * notes text nullable — admin-written rollout notes. Length-
--     bounded (0..2000) to keep accidental log dumps out of the table.
--
-- operators.default_role_catalog_version_id
-- ------------------------------------------
-- New nullable FK column on operators that pins a specific catalog
-- version to that operator. NULL = "follow the latest published
-- version" (the common case at PR-merge time, since no version has
-- been published yet). When a version is pinned, the resolver
-- (lib/infrastructure/persistence/postgres/repositories/roles_repository.dart)
-- returns that version's payload regardless of subsequent publishes
-- — the rollback path is "patch operators.default_role_catalog_version_id
-- to the older version's id". ON DELETE SET NULL because deleting a
-- catalog version is allowed (versions are content-addressed) but
-- must not orphan the operators row.
--
-- Why no RLS on default_role_catalog_versions
-- -------------------------------------------
-- This is a GLOBAL F&F-wide catalog table — NOT an operator-scoped
-- fact table. CLAUDE.md "RLS-Ready Schema" mandates operator-scoped
-- fact tables ship with RLS policy stubs from creation; this table
-- has NO operator_id column and is read by every operator through
-- the resolver. The defense-in-depth posture is:
--
--   * The admin-pool runtime (service_role + forge_admin) is the only
--     identity that reads/writes this table. The repository (see
--     default_role_catalog_versions_repository.dart) routes every call
--     through TenantTransactionWrapper.runAsSystem so the connection
--     carries `SET LOCAL ROLE forge_admin` for the lifetime of the
--     transaction.
--   * Grants below explicitly REVOKE all from public, GRANT SELECT to
--     service_role (so the resolver can read the current catalog from
--     a tenant transaction without elevating), and GRANT full DML to
--     forge_admin (so the admin publish path can mutate).
--   * Operator-scoped readers never need to filter by operator_id on
--     this table because there is no operator_id column to filter on
--     — the catalog is the same for everyone. The per-operator pin is
--     `operators.default_role_catalog_version_id`, which is enforced
--     by the existing per-operator RLS regime on the operators table
--     (we do NOT touch that regime here).
--
-- Idempotency
-- -----------
-- All DDL is idempotent (if not exists on every CREATE, drop policy if
-- exists before create policy, alter table … add column if not exists).
-- Re-applying the migration is a no-op.
--
-- Lock + timeout guardrails
-- -------------------------
-- The ALTER TABLE on `operators` takes an ACCESS EXCLUSIVE lock
-- briefly. We bound the wait so a hot tenant pool does not stall
-- behind us.
--
-- Operator approval gate
-- ----------------------
-- Per CLAUDE.md "agent-led slices" — schema-touching slices require
-- explicit operator approval before merge regardless of audit verdict.
-- This migration is the schema artifact that gates that approval.

begin;

set local statement_timeout = '30s';
set local lock_timeout = '5s';

-- pgcrypto already required by audit_logs (202604280005); referenced
-- here for explicitness because gen_random_uuid() is the entropy
-- source for the version_id default.
create extension if not exists pgcrypto;

-- ─── default_role_catalog_versions ────────────────────────────────
create table if not exists public.default_role_catalog_versions (
  version_id              uuid primary key default gen_random_uuid(),
  version_number          integer not null,
  published_at            timestamptz not null default now(),
  published_by_user_id    uuid not null,
  payload                 jsonb not null,
  payload_sha256          text not null,
  is_current              boolean not null default false,
  superseded_at           timestamptz,
  notes                   text,
  constraint default_role_catalog_versions_version_number_chk
    check (version_number >= 1),
  constraint default_role_catalog_versions_payload_shape_chk
    check (jsonb_typeof(payload) = 'array'),
  constraint default_role_catalog_versions_payload_sha256_shape_chk
    check (payload_sha256 ~ '^[0-9a-f]{64}$'),
  constraint default_role_catalog_versions_superseded_chk
    check (
      (is_current = true and superseded_at is null)
      or
      (is_current = false)
    ),
  constraint default_role_catalog_versions_notes_length_chk
    check (notes is null or char_length(notes) between 0 and 2000)
);

comment on table public.default_role_catalog_versions is
  'Lane B B2.1 — F&F-wide versioned Default Role catalog. One row per '
  'publish. Global (no operator_id). At most one row has is_current = '
  'true at any time (enforced by the partial UNIQUE INDEX below). '
  'Read by the per-operator roles resolver via the operators.default'
  '_role_catalog_version_id pointer (NULL pointer = follow current). '
  'No RLS — admin-pool BYPASSRLS posture; runtime reads are SELECT-'
  'only via service_role.';

comment on column public.default_role_catalog_versions.version_id is
  'UUID primary key — server-generated by gen_random_uuid(). Stable '
  'identity referenced by operators.default_role_catalog_version_id '
  'and quoted in audit rows.';

comment on column public.default_role_catalog_versions.version_number is
  'Monotonically incrementing per publish (1, 2, 3, …). Computed by '
  'the publish repository as MAX(version_number)+1 inside the publish '
  'transaction. NOT a primary key — UI surfaces version_number for '
  'human readability while every wire format keys off version_id.';

comment on column public.default_role_catalog_versions.published_at is
  'UTC instant the row was inserted. TIMESTAMPTZ per CLAUDE.md "Time '
  'Guardrails".';

comment on column public.default_role_catalog_versions.published_by_user_id is
  'F&F admin who issued the publish. References public.users(user_id) '
  'logically; an FK is not declared here because publish flows accept '
  'super_admin Firebase users that may not have a Postgres users row '
  'in every environment. The proxy enforces role gate; the audit row '
  'captures the user identity.';

comment on column public.default_role_catalog_versions.payload is
  'Serialized catalog (jsonb array of role definitions). Stored '
  'verbatim as published so a rollback is a byte-identical replay of '
  'an earlier version. The jsonb_typeof CHECK rejects non-array '
  'shapes.';

comment on column public.default_role_catalog_versions.payload_sha256 is
  'Lowercase hex SHA-256 of the canonical payload bytes. Computed '
  'application-side at publish time and persisted so audit rows + '
  'downstream readers can verify the catalog they see matches the '
  'published bytes.';

comment on column public.default_role_catalog_versions.is_current is
  'True for exactly one row at a time (enforced by the partial '
  'UNIQUE INDEX default_role_catalog_versions_current_unique). The '
  'publish transaction flips the previous current to false and sets '
  'the new row to true in a single COMMIT.';

comment on column public.default_role_catalog_versions.superseded_at is
  'Stamped when a newer version becomes current. NULL while the row '
  'is current; the CHECK above guards "is_current = true AND '
  'superseded_at IS NOT NULL" as a forbidden shape.';

comment on column public.default_role_catalog_versions.notes is
  'Optional admin-written rollout notes (free-form, 0..2000 chars). '
  'Surfaced in the admin history view; not user-facing.';

-- Partial UNIQUE INDEX — at most one current version globally. The
-- predicate `where is_current = true` keeps the index small (single
-- row) and lets the publish transaction atomically swap currents.
create unique index if not exists default_role_catalog_versions_current_unique
  on public.default_role_catalog_versions ((true))
  where is_current = true;

-- Latest-lookup index — speeds the publish transaction's
-- MAX(version_number)+1 read and the history-list ORDER BY.
create index if not exists default_role_catalog_versions_version_number_desc_idx
  on public.default_role_catalog_versions (version_number desc);

-- ─── operators.default_role_catalog_version_id ────────────────────
-- New nullable FK column. NULL = follow latest current version.
alter table public.operators
  add column if not exists default_role_catalog_version_id uuid;

-- FK constrained separately so the ADD COLUMN above stays idempotent
-- when the column already exists. ON DELETE SET NULL preserves the
-- operators row when a catalog version is removed.
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'operators_default_role_catalog_version_id_fkey'
  ) then
    alter table public.operators
      add constraint operators_default_role_catalog_version_id_fkey
      foreign key (default_role_catalog_version_id)
      references public.default_role_catalog_versions(version_id)
      on delete set null;
  end if;
end
$$;

comment on column public.operators.default_role_catalog_version_id is
  'Lane B B2.1 — pointer to the Default Role catalog version this '
  'operator follows. NULL = follow the latest published version (the '
  'common case). When pinned, the per-operator roles resolver returns '
  'this version verbatim regardless of subsequent publishes — the '
  'rollback path is "patch this column to an older version_id".';

-- ─── Grants ────────────────────────────────────────────────────────
-- Admin-pool BYPASSRLS posture for the catalog table. Runtime reads
-- only need SELECT; the publish path runs under forge_admin via
-- TenantTransactionWrapper.runAsSystem.
revoke all on public.default_role_catalog_versions from public;
grant select
  on public.default_role_catalog_versions to service_role;
grant select, insert, update, delete
  on public.default_role_catalog_versions to forge_admin;

commit;
