-- Lane B B11.1 — auth_handoff_codes table.
--
-- Authority:
--   * docs/_execution/lane_b_features/03_execution_slices.md
--     ("B11.1 — handoff_codes table + endpoints")
--   * docs/_execution/lane_b_features/01_product_rule_and_ia.md
--     (addendum A1: "Redemption-Code Handoff" — code never appears in
--      a JWT-in-URL; mobile mints a one-time short-TTL opaque code that
--      the web client redeems atomically against this table.)
--   * CLAUDE.md "Hard Promises" #4 (per-operator isolation NON-NEGOTIABLE)
--   * CLAUDE.md "RLS-Ready Schema" — operator-scoped fact tables include
--     (operator_id, location_id) + RLS policy stub from creation; every
--     fact-table B-tree index leads with operator_id; RLS policies use
--     the four STABLE LEAKPROOF PARALLEL SAFE wrapper functions; bare
--     current_setting() reads forbidden.
--   * CLAUDE.md "Time Guardrails" — operator-scoped tables MUST use
--     TIMESTAMPTZ. handoff codes are session-bucketed (NOT business-day-
--     bucketed) so business_date denorm is intentionally out of scope.
--   * docs/contracts/hardening_rls_and_repository_pattern_contract.md
--     (wrapper-only RLS posture; SET LOCAL transaction-scoped tenant
--      injection via OperatorScopedRepository.)
--
-- Adds public.handoff_codes — one row per minted handoff code. Each row
-- represents a mobile-side request to hand the active operator's session
-- off to the web. The web client resolves the row by POSTing the opaque
-- code to /v1/auth/handoff/redeem; the proxy's atomic UPDATE … RETURNING
-- consumes the row (consumed_at = now()) and returns the resolved
-- (user_id, operator_id, target_path) so the web can mint a fresh
-- session for the same human. The opaque code never travels as a JWT,
-- and the web client never sends it as a URL query parameter to the
-- proxy — see addendum A1 above.
--
-- Schema notes carried verbatim from the slice doc:
--   * code text primary key — opaque, server-generated by gen_random_bytes(16)
--     (pgcrypto). 22-char base64-url body provides ~128 bits of entropy
--     so brute force inside the 60-second TTL is computationally
--     infeasible.
--   * 60-second TTL via expires_at = created_at + interval '60 seconds'.
--     Enforced server-side by the redeem predicate
--     (expires_at > now()); also enforced by the inline reaper running
--     at the head of every mint (see auth_handoff_routes.dart).
--   * source_device_fingerprint records the mobile device that minted
--     the code so the audit row carries the originating device when
--     the web later redeems. Optional (NULL allowed) — mobile clients
--     that have not granted device-fingerprint capability still mint.
--
-- Hard rules carried verbatim from CLAUDE.md / phase docs:
--
--   * **HP #4 RLS-Ready Schema.** Table carries operator_id from
--     creation; tenant-leading B-tree indexes; per-tenant RLS policy
--     enabled at table-creation time using the wrapper function
--     `app_current_operator()`. No bare current_setting() reads.
--   * **Wrapper-only RLS posture (Phase 9.0Σ.b item 4).** Policy body
--     calls public.app_current_operator(). The four wrapper functions
--     are STABLE LEAKPROOF PARALLEL SAFE so the planner can fold them
--     into index scans.
--   * **Time guardrails.** All temporal columns are TIMESTAMPTZ.
--     created_at, expires_at, consumed_at — all UTC instants, never
--     wall-clock TIMESTAMP WITHOUT TIME ZONE.
--   * **Idempotent migration.** if not exists on every CREATE,
--     drop policy if exists before create policy. Re-applying the
--     migration is a no-op.
--   * **No client-side codes.** The opaque code is generated server-
--     side by encode(gen_random_bytes(16), 'base64'), stripped of
--     URL-unsafe characters by the application before storage. Clients
--     never supply a candidate code.
--
-- Operator approval gate: per CLAUDE.md "agent-led slices" — auth-
-- critical, RLS-touching, schema-touching, and proxy-touching slices
-- require explicit operator approval before merge regardless of audit
-- verdict. This migration is one of the three artifacts that gate that
-- approval.

begin;

-- pgcrypto already required by audit_logs (202604280005); listed here
-- for explicitness because gen_random_bytes() is the entropy source for
-- the opaque code.
create extension if not exists pgcrypto;

-- ─── handoff_codes ─────────────────────────────────────────────────
create table if not exists public.handoff_codes (
  code                       text primary key,
  user_id                    uuid not null,
  operator_id                uuid not null,
  location_id                uuid not null,
  target_path                text not null
                             check (char_length(target_path) between 1 and 512),
  expires_at                 timestamptz not null,
  consumed_at                timestamptz null,
  source_device_fingerprint  text null,
  created_at                 timestamptz not null default now(),
  -- 60-second TTL is the contract; reject rows that try to widen it.
  -- The 5-second slop guards against minor clock drift between the
  -- application and the database session; the application is expected
  -- to set expires_at exactly to created_at + interval '60 seconds'.
  constraint handoff_codes_ttl_chk check (
    expires_at > created_at
    and expires_at <= created_at + interval '65 seconds'
  ),
  -- Code shape: server-side base64-url body of gen_random_bytes(16),
  -- which yields a 22-character body (no padding). Reject malformed
  -- shapes so a buggy mint path can't smuggle a too-short or
  -- non-URL-safe code into the table.
  constraint handoff_codes_code_shape_chk check (
    char_length(code) between 22 and 64
    and code ~ '^[A-Za-z0-9_-]+$'
  )
);

comment on table public.handoff_codes is
  'Lane B B11.1 — operator-scoped one-time handoff codes. Mobile mints '
  'a row via POST /v1/auth/handoff/codes; web redeems atomically via '
  'POST /v1/auth/handoff/redeem (UPDATE … RETURNING with predicate '
  'consumed_at IS NULL AND expires_at > now()). 60-second TTL. '
  'Replaces the original Decision #5 token-in-URL hand-off path per '
  'addendum A1. The opaque code never travels as a JWT and is never '
  'sent as a URL query parameter to the proxy. RLS: per-operator '
  '(operator_id = app_current_operator()).';

comment on column public.handoff_codes.code is
  'Opaque server-generated handoff code. Body is base64-url of '
  'gen_random_bytes(16) (~128 bits of entropy). Primary key — '
  'collision probability inside the 60-second TTL is negligible.';

comment on column public.handoff_codes.user_id is
  'JWT subject of the human who minted the code. The web client '
  'resumes as the same user.';

comment on column public.handoff_codes.operator_id is
  'Operator the minting JWT was scoped to. Redeem rejects '
  '(403 wrong_operator) when the redeeming caller resolves to a '
  'different operator_id.';

comment on column public.handoff_codes.location_id is
  'Location the minting JWT was scoped to. Carried so the redeem '
  'gateway can run through the tenant transaction wrapper, which '
  'requires both operator_id and location_id to issue SET LOCAL.';

comment on column public.handoff_codes.target_path is
  'The deep-link target path the web should land at after redeem '
  '(e.g. /operator-web/team). Surfaced in the redeem response so '
  'the web client can navigate without round-tripping the path '
  'through the URL.';

comment on column public.handoff_codes.expires_at is
  '60 seconds after created_at. The redeem predicate '
  '(expires_at > now()) enforces this in addition to the row-level '
  'TTL check constraint.';

comment on column public.handoff_codes.consumed_at is
  'Set by the atomic UPDATE … RETURNING in the redeem handler. NULL '
  'until first successful redeem; NOT NULL afterwards. Replays return '
  '410 Gone because the predicate (consumed_at IS NULL) no longer '
  'matches.';

comment on column public.handoff_codes.source_device_fingerprint is
  'Device fingerprint collected by the mobile mint client (when '
  'available). Logged on the redeem audit_logs row so the audit '
  'reader can see which mobile device originated the handoff.';

-- Operator-leading B-tree indexes per CI lint (CLAUDE.md hard rule).
-- The composite (operator_id, user_id, created_at desc) supports the
-- per-user 10/hour rate-limit window scan in the mint handler.
create index if not exists handoff_codes_operator_user_idx
  on public.handoff_codes (operator_id, user_id, created_at desc);

-- Partial index supports the redeem lookup. WHERE consumed_at IS NULL
-- so the index stays small (each row appears in this index for at
-- most 60 seconds before the inline reaper drops it).
create index if not exists handoff_codes_code_active_idx
  on public.handoff_codes (code)
  where consumed_at is null;

-- Partial index supports the inline reaper sweep. WHERE consumed_at
-- IS NULL filters out already-redeemed rows the reaper does not need
-- to revisit. Once a row is consumed it can age out via the
-- expires_at index for archival cleanup.
create index if not exists handoff_codes_expires_at_active_idx
  on public.handoff_codes (expires_at)
  where consumed_at is null;

-- RLS — wrapper-only per Phase 9.0Σ.b item 4. Per-operator policy
-- using the STABLE LEAKPROOF PARALLEL SAFE wrapper from
-- 202604280000_phase_9_0sigma_b_rls_wrappers.sql. Bare current_setting
-- reads are forbidden (rls_policy_lint enforces this).
alter table public.handoff_codes enable row level security;

drop policy if exists "handoff_codes_per_operator"
  on public.handoff_codes;
create policy "handoff_codes_per_operator"
  on public.handoff_codes for all to service_role
  using (
    operator_id = public.app_current_operator()
  )
  with check (
    operator_id = public.app_current_operator()
  );

-- Grants. Runtime (service_role) needs full DML for mint, redeem, and
-- the inline reaper. forge_admin gets read for ops visibility (the
-- forge admin console can render a per-operator handoff-code list to
-- diagnose mobile-to-web bounce failures).
revoke all on public.handoff_codes from public;
grant select, insert, update, delete
  on public.handoff_codes to service_role;
grant select, delete
  on public.handoff_codes to forge_admin;

commit;
