// The tie between what a cook READS and what the calculator SCALES.
//
// `kBarrioRecipeIngredients` is a structured second view of the Recipes
// manual's ingredient lines, generated by
// `tool/barrio_recipe_ingredients_generator.py`. The reader renders the
// card body; the calculator renders the parse. If the two ever drift, the
// calculator scales numbers the reader never showed, which is the one
// failure this file exists to make impossible.
//
// HOW THIS STAYS AN HONEST GUARD (see
// `feedback_negative_controls_can_be_vacuous`). Nothing below asks the
// generator what it found. Every expected value is re-derived here from
// the LIVE `kBarrioTrainingDocs['training_recipes']` document at runtime,
// by this file's own reader ([_amountIn]) and its own hand-written unit
// vocabulary:
//
//   * the ingredient lines come from splitting each card's own body on
//     blank lines and taking the paragraphs that open with the Markdown
//     bullet, so the coverage check compares two independent readings of
//     the same manual rather than a parse against itself;
//   * the amount text, the number or numbers inside it, the unit and the
//     ingredient name are all re-read off the raw line here and compared
//     field by field with what the data claims;
//   * the nine lines the calculator must leave exactly as written are
//     written out BY HAND below, card and line, so a line that quietly
//     stopped scaling (or quietly started) fails naming itself.
//
// Corrupting one entry's `raw` by a single character, or dropping one
// entry, fails the coverage and substring tests (re-verified 2026-08-13,
// REC-6).

import 'package:flutter_test/flutter_test.dart';
import 'package:forge_and_flow/internal/barrio/content/company_handbook_content.dart';
import 'package:forge_and_flow/internal/barrio/content/recipes/barrio_recipe_ingredients.dart';
import 'package:forge_and_flow/internal/barrio/content/recipes/barrio_recipe_models.dart';
import 'package:forge_and_flow/internal/barrio/content/training/training_docs.dart';

const String _kRecipesDocId = 'training_recipes';

/// Words that, sitting straight after a number, belong to the AMOUNT and
/// not to the ingredient's name. Declared here by hand so the split is
/// asserted against an independent list rather than against whichever
/// words the generator happened to accept.
const Set<String> _kUnitWords = <String>{
  'g', 'kg', 'mg', 'lb', 'lbs', 'oz',
  'ml', 'l', 'tsp', 'tbsp', 'cup', 'cups',
  'gram', 'grams', 'kilogram', 'kilograms', 'milligram', 'milligrams',
  'pound', 'pounds', 'ounce', 'ounces',
  'millilitre', 'millilitres', 'milliliter', 'milliliters',
  'litre', 'litres', 'liter', 'liters',
  'teaspoon', 'teaspoons', 'tablespoon', 'tablespoons',
  'jar', 'jars', 'can', 'cans', 'bag', 'bags', 'bottle', 'bottles',
  'tin', 'tins', 'case', 'cases', 'box', 'boxes',
  'piece', 'pieces', 'pc', 'pcs', 'clove', 'cloves', 'stalk', 'stalks',
  'bunch', 'bunches', 'head', 'heads', 'sprig', 'sprigs', 'leaf', 'leaves',
  'slab', 'slabs', 'stick', 'sticks',
};

/// The ONLY lines allowed to carry a unit their own text never prints.
///
/// NARROW BY DESIGN, AND IT MUST STAY NARROW. Two lines of the manual are
/// weights the operator wrote as a bare number, and confirmed as grams on
/// 2026-08-13. Everywhere else, a unit that is not on the line is a parser
/// inventing a measurement. So this table is written out line by line, and
/// the tests below prove BOTH directions: these two carry the confirmed
/// unit, and no other line in the manual carries a unit its text lacks.
///
/// Re-confirming with the operator is the only thing that may add a row.
const Map<String, String> _kOperatorConfirmedUnits = <String, String>{
  '235 Pumpkin Seeds': 'g', // Beef Skewer Topping
  '654 Canola Oil': 'g', // Pork Belly Glaze
};

/// Every line of the manual the calculator must print exactly as written,
/// because it carries no number to multiply. Hand-listed 'cardId|line'.
///
/// EIGHT OF THE NINE ARE PLAIN: they open with a word, not a number, and
/// they end with a word, not a measurement. The ninth is the habanero
/// line, which carries a parenthesised weight AND a count of peppers, so
/// scaling either one leaves the other lying; it is deliberately left
/// unparsed rather than given a rule that fires on one line of the manual.
const Set<String> _kLinesWithNoNumber = <String>{
  'training_recipes_c0_u0|Salt TT',
  'training_recipes_c5_u0|Salt TT',
  'training_recipes_c19_u0|L5S TT',
  'training_recipes_c19_u0|Salt TT',
  'training_recipes_c23_u0|The Peel of One Orange',
  'training_recipes_c27_u0|(30g) 4-5 Habanero Peppers (deseeded and deribbed)',
  'training_recipes_c30_u0|One Large Onion Red Small Dice',
  'training_recipes_c30_u0|Salt TT',
  'training_recipes_c30_u0|L5S TT',
};

/// Fraction glyphs the operator's kitchen types, decoded here so the
/// quantity check never borrows the generator's table.
const Map<String, double> _kFractionGlyphs = <String, double>{
  '¼': 0.25, // one quarter
  '½': 0.5, // one half
  '¾': 0.75, // three quarters
  '⅓': 1 / 3, // one third
  '⅔': 2 / 3, // two thirds
};

const String _kNumber = r'\d+(?:\.\d+)?(?:/\d+(?:\.\d+)?)?|[¼½¾⅓⅔]';

/// Two numbers with a hyphen between them, at the head of the line.
final RegExp _kRangeAtHead =
    RegExp('^($_kNumber)' r'\s*([A-Za-z]+)?\s*-\s*' '($_kNumber)'
        r'\s*([A-Za-z]+)?(?![\w-])');

/// One number at the head of the line, with the word it attaches to.
final RegExp _kNumberAtHead =
    RegExp('^($_kNumber)' r'\s*([A-Za-z]+)?(?![\w-])');

/// A number and its unit closing the line, which is how one line of the
/// manual writes its amount ('Lime 300mL').
final RegExp _kNumberAtTail =
    RegExp(r'(?<![\w.])' '($_kNumber)' r'\s*([A-Za-z]+)$');

/// A token this file's reader found, as a number.
double? _valueOf(String token) {
  final glyph = _kFractionGlyphs[token];
  if (glyph != null) return glyph;
  if (token.contains('/')) {
    final parts = token.split('/');
    final bottom = double.tryParse(parts[1]);
    final top = double.tryParse(parts[0]);
    if (top == null || bottom == null || bottom == 0) return null;
    return top / bottom;
  }
  return double.tryParse(token);
}

bool _isUnitWord(String? word) =>
    word != null && _kUnitWords.contains(word.toLowerCase());

/// [matched] with a trailing [word] taken back off, for the case where the
/// word the regex swept up is the start of the ingredient name rather than
/// a unit ('12 Eggs' matches '12 Eggs' but its amount is only '12'). Both
/// regexes below end in an optional word, so the word is always the tail.
String _withoutTrailingWord(String matched, String? word) {
  if (word == null) return matched.trimRight();
  return matched.substring(0, matched.length - word.length).trimRight();
}

/// The amount [raw] prints, read from first principles off the line's own
/// text: which characters are the amount, the number or numbers in it, and
/// the unit word attached to them. Null when the line prints no amount.
({String text, List<double> numbers, String? unit})? _amountIn(String raw) {
  final range = _kRangeAtHead.firstMatch(raw);
  if (range != null) {
    final low = _valueOf(range.group(1)!);
    final high = _valueOf(range.group(3)!);
    if (low != null && high != null) {
      final lowUnit = range.group(2);
      final highUnit = range.group(4);
      // Either slot may hold the first word of the ingredient name
      // ('9-10 Roma Tomatoes'), so a slot only counts as a unit when it
      // holds a word this file recognises.
      if (_isUnitWord(highUnit)) {
        return (
          text: range.group(0)!,
          numbers: <double>[low, high],
          unit: highUnit,
        );
      }
      return (
        text: _withoutTrailingWord(range.group(0)!, highUnit),
        numbers: <double>[low, high],
        unit: _isUnitWord(lowUnit) ? lowUnit : null,
      );
    }
  }

  final head = _kNumberAtHead.firstMatch(raw);
  if (head != null) {
    final value = _valueOf(head.group(1)!);
    if (value != null) {
      final word = head.group(2);
      if (_isUnitWord(word)) {
        return (
          text: head.group(0)!,
          numbers: <double>[value],
          unit: word,
        );
      }
      return (
        text: _withoutTrailingWord(head.group(0)!, word),
        numbers: <double>[value],
        unit: null,
      );
    }
  }

  final tail = _kNumberAtTail.firstMatch(raw);
  if (tail != null && _isUnitWord(tail.group(2))) {
    final value = _valueOf(tail.group(1)!);
    if (value != null && raw.substring(0, tail.start).trim().isNotEmpty) {
      return (
        text: raw.substring(tail.start),
        numbers: <double>[value],
        unit: tail.group(2),
      );
    }
  }
  return null;
}

/// What is left of [raw] once its amount is taken out: the ingredient.
String _nameIn(String raw, String? amount) {
  final rest = amount == null ? raw : raw.replaceFirst(amount, '');
  return rest.trim().replaceFirst(RegExp(r'^of\s+', caseSensitive: false), '')
      .trim();
}

/// Every card of the routed Recipes manual, in reading order.
List<HandbookUnit> _recipeCards() {
  final doc = kBarrioTrainingDocs[_kRecipesDocId];
  expect(doc, isNotNull,
      reason: 'the Recipes manual must be registered in kBarrioTrainingDocs');
  return <HandbookUnit>[
    for (final chapter in doc!.chapters) ...chapter.units,
  ];
}

/// The ingredient lines a card body actually prints: its blank-line
/// separated paragraphs that open with the Markdown list bullet, bullet
/// stripped. Read straight off the live body, never off the parse.
List<String> _ingredientLinesOf(String body) => <String>[
      for (final paragraph in body.split('\n\n'))
        if (paragraph.startsWith('- ')) paragraph.substring(2).trim(),
    ]..removeWhere((String line) => line.isEmpty);

/// Every parsed entry of the committed data, keyed 'cardId|line' so it can
/// be compared with a set derived from the live card bodies.
List<({String key, BarrioRecipeIngredient line})> _everyParsedLine() =>
    <({String key, BarrioRecipeIngredient line})>[
      for (final entry in kBarrioRecipeIngredients.entries)
        for (final line in entry.value)
          (key: '${entry.key}|${line.raw}', line: line),
    ];

void main() {
  group('recipe ingredient data', () {
    test('the manual carries ingredient data at all', () {
      // Non-vacuity: every comparison below is trivially true against an
      // empty bank, so the bank has to be real first.
      expect(kBarrioRecipeIngredients, isNotEmpty);
      final all = kBarrioRecipeIngredients.values.expand((e) => e).toList();
      expect(all.length, greaterThan(100),
          reason: 'the Recipes manual parses to hundreds of lines; a corpus '
              'this small means the data was gutted');
      expect(all.any((e) => e.scales), isTrue,
          reason: 'a manual of recipes must have something worth scaling');
      expect(all.any((e) => !e.scales), isTrue,
          reason: 'the no-number branch must be reached by real lines');
      expect(all.any((e) => e.quantityHigh != null), isTrue,
          reason: 'the range branch must be reached by real lines');
    });

    test('the parse covers every ingredient line, in order, with none '
        'silently dropped', () {
      // THE COVERAGE GUARD. The lines come from the live card bodies; the
      // raws come from the committed data. A dropped, added, reordered or
      // edited entry fails here.
      var linesSeen = 0;
      for (final card in _recipeCards()) {
        final lines = _ingredientLinesOf(card.body);
        final entries = kBarrioRecipeIngredients[card.id];
        if (lines.isEmpty) {
          expect(entries, anyOf(isNull, isEmpty),
              reason: '${card.id} prints no ingredient line, so it must '
                  'carry no ingredient data');
          continue;
        }
        expect(entries, isNotNull,
            reason: '${card.id} prints ${lines.length} ingredient line(s) '
                'but carries no ingredient data; regenerate with '
                'tool/barrio_recipe_ingredients_generator.py');
        expect(entries!.map((e) => e.raw).toList(), lines,
            reason: '${card.id}: the parsed lines must be exactly the lines '
                'the card body prints, in the same order');
        linesSeen += lines.length;
      }
      expect(linesSeen, greaterThan(0),
          reason: 'no ingredient line was checked, so this guard proved '
              'nothing; the manual or its body format changed');
    });

    test('every parsed line is an exact substring of its own card body', () {
      // THE TIE. Even with the counts lined up, a raw that is not literally
      // in the body means the calculator shows text the reader never saw.
      final cardsById = <String, HandbookUnit>{
        for (final card in _recipeCards()) card.id: card,
      };
      for (final entry in kBarrioRecipeIngredients.entries) {
        final card = cardsById[entry.key];
        expect(card, isNotNull,
            reason: '${entry.key} is not a card of the Recipes manual; a '
                'stale unit id would attach data to the wrong recipe');
        for (final ingredient in entry.value) {
          expect(card!.body.contains(ingredient.raw), isTrue,
              reason: '${entry.key}: "${ingredient.raw}" does not appear in '
                  'that card\'s body word for word');
        }
      }
    });

    test('the amount is a slice of the line, and the rest of the line is '
        'the ingredient', () {
      // The calculator rewrites the numbers INSIDE `amount` and prints
      // `name` beside it. If `amount` were ever text the line does not
      // print, or `name` anything but the remainder, a cook would read an
      // ingredient list the card never wrote.
      var withAmount = 0;
      var withoutAmount = 0;
      for (final row in _everyParsedLine()) {
        final line = row.line;
        final amount = line.amount;
        if (amount == null) {
          withoutAmount += 1;
          expect(line.quantity, isNull,
              reason: '${row.key} carries a quantity but no amount text, so '
                  'nothing could render it');
          expect(line.name, line.raw,
              reason: '${row.key} has no amount, so the whole line is the '
                  'ingredient and must print exactly as written');
          continue;
        }
        withAmount += 1;
        expect(line.quantity, isNotNull,
            reason: '${row.key} carries amount text but no number');
        expect(line.raw.contains(amount), isTrue,
            reason: '${row.key}: the amount "$amount" is not printed by the '
                'line it was taken from');
        expect(line.name, _nameIn(line.raw, amount),
            reason: '${row.key}: the ingredient name must be what is left of '
                'the line once "$amount" is taken out');
        expect(line.name.trim(), isNotEmpty,
            reason: '${row.key} is an amount of nothing');
      }
      expect(withAmount, greaterThan(100),
          reason: 'only $withAmount lines carry an amount, so the corpus '
              'collapsed and this proved nothing');
      expect(withoutAmount, greaterThan(0),
          reason: 'the no-amount branch was never reached');
    });

    test('exactly the lines that print no number are left as written', () {
      // THE OPERATOR RULE, both directions, against a hand-written list.
      // A line that quietly stopped scaling is an amount taken away from a
      // cook; a line that quietly started is a number invented for them.
      final asWritten = <String>{
        for (final row in _everyParsedLine())
          if (!row.line.scales) row.key,
      };
      expect(asWritten, _kLinesWithNoNumber,
          reason: 'the manual now leaves a different set of lines as '
              'written than the set this file was written against');

      // And the same nine, derived off the live bodies rather than off the
      // data, so the hand-written list cannot drift with the parse.
      final readAsHavingNoNumber = <String>{
        for (final card in _recipeCards())
          for (final line in _ingredientLinesOf(card.body))
            if (_amountIn(line) == null) '${card.id}|$line',
      };
      expect(readAsHavingNoNumber, _kLinesWithNoNumber,
          reason: 'this file reads a different set of numberless lines out '
              'of the manual than the data carries');
    });

    test('the amount, the numbers and the unit are what the line prints',
        () {
      // Re-read off the raw text with this file's own reader, so a parser
      // bug cannot supply its own expected value.
      var ranges = 0;
      var confirmed = 0;
      var ordinary = 0;
      for (final row in _everyParsedLine()) {
        final line = row.line;
        final read = _amountIn(line.raw);
        if (read == null) {
          expect(line.amount, isNull, reason: '${row.key} invented an amount');
          expect(line.quantity, isNull);
          expect(line.quantityHigh, isNull);
          expect(line.unit, isNull);
          continue;
        }
        expect(line.amount, read.text,
            reason: '${row.key} claims the amount "${line.amount}" but the '
                'line prints "${read.text}"');
        expect(line.quantity, isNotNull);
        expect(line.quantity!, closeTo(read.numbers.first, 1e-9),
            reason: '${row.key} was parsed as ${line.quantity} but the line '
                'prints ${read.numbers.first}');
        if (read.numbers.length == 2) {
          ranges += 1;
          expect(line.quantityHigh, isNotNull,
              reason: '${row.key} is a range, so both numbers must scale');
          expect(line.quantityHigh!, closeTo(read.numbers[1], 1e-9),
              reason: '${row.key} lost the second number of its range');
        } else {
          expect(line.quantityHigh, isNull,
              reason: '${row.key} carries a second number the line does not '
                  'print');
        }

        final operatorUnit = _kOperatorConfirmedUnits[line.raw];
        if (operatorUnit != null) {
          // THE NARROW EXCEPTION, and the only one. These two lines print
          // no unit, which is precisely why the operator had to be asked.
          confirmed += 1;
          expect(read.unit, isNull,
              reason: '"${line.raw}" now prints its own unit, so the '
                  'operator confirmation is stale and must be deleted here '
                  'and in tool/barrio_recipe_ingredients_generator.py');
          expect(line.unit, operatorUnit,
              reason: '${row.key} carries "${line.unit}", but the operator '
                  'confirmed "$operatorUnit"');
          continue;
        }
        ordinary += 1;
        expect(line.unit, read.unit,
            reason: '${row.key} claims the unit "${line.unit}" but the '
                'amount it printed reads "${read.unit}"');
        if (line.unit != null) {
          expect(line.amount!.contains(line.unit!), isTrue,
              reason: '${row.key}: the unit must be inside the amount the '
                  'line printed, not found elsewhere');
        }
      }
      expect(ranges, greaterThan(0),
          reason: 'the range branch was never reached');
      expect(confirmed, _kOperatorConfirmedUnits.length,
          reason: 'an operator-confirmed line is no longer in the manual');
      expect(ordinary, greaterThan(100),
          reason: 'the ordinary branch was barely reached, so the corpus '
              'collapsed');
    });

    test('only the two confirmed lines carry a unit their text lacks', () {
      // The other direction of the exception above: a confirmation pointed
      // at the wrong ingredient, or a parser that started inventing units
      // elsewhere, fails here.
      final invented = <String>[
        for (final row in _everyParsedLine())
          if (row.line.unit != null && !row.line.raw.contains(row.line.unit!))
            row.line.raw,
      ];
      expect(invented.toSet(), _kOperatorConfirmedUnits.keys.toSet(),
          reason: 'these lines carry a unit their own text never prints: '
              '${invented.join(", ")}');
      expect(invented, hasLength(_kOperatorConfirmedUnits.length),
          reason: 'one confirmation landed on more than one ingredient');
    });

    test('no card outside the Recipes manual carries ingredient data', () {
      final recipeIds = _recipeCards().map((c) => c.id).toSet();
      final strays = kBarrioRecipeIngredients.keys
          .where((id) => !recipeIds.contains(id))
          .toList();
      expect(strays, isEmpty,
          reason: 'these unit ids are not Recipes cards: ${strays.join(", ")}');
      // The lookup must stay quiet for every other manual.
      expect(barrioRecipeIngredientsForUnit('training_wine_c0_u0'), isEmpty);
      expect(barrioRecipeIngredientsForUnit('no_such_unit'), isEmpty);
    });
  });
}
