// The tie between what a cook READS and what a calculator would SCALE.
//
// `kBarrioRecipeIngredients` is a structured second view of the Recipes
// manual's ingredient lines, generated by
// `tool/barrio_recipe_ingredients_generator.py`. The reader renders the
// card body; a calculator would render the parse. If the two ever drift,
// a calculator scales numbers the reader never showed, which is the one
// failure this file exists to make impossible.
//
// HOW THIS STAYS AN HONEST GUARD. Nothing below asks the generator what
// it found. Every expected value is re-derived here from the LIVE
// `kBarrioTrainingDocs['training_recipes']` document at runtime:
//
//   * the ingredient lines come from splitting each card's own body on
//     blank lines and taking the paragraphs that open with the Markdown
//     bullet, so the coverage check compares two independent readings of
//     the same manual rather than a parse against itself;
//   * the quantities are re-read off the raw text by [_leadingNumber]
//     below, which carries its own fraction table and never consults
//     `BarrioRecipeIngredient.quantity`;
//   * the mass and volume vocabulary is declared here, so the scaling
//     rule is asserted against an independent list rather than against
//     whichever words the generator happened to accept.
//
// Corrupting one entry's `raw` by a single character, or dropping one
// entry, fails the first two tests below (verified 2026-08-13).

import 'package:flutter_test/flutter_test.dart';
import 'package:forge_and_flow/internal/barrio/content/company_handbook_content.dart';
import 'package:forge_and_flow/internal/barrio/content/recipes/barrio_recipe_ingredients.dart';
import 'package:forge_and_flow/internal/barrio/content/recipes/barrio_recipe_models.dart';
import 'package:forge_and_flow/internal/barrio/content/training/training_docs.dart';

const String _kRecipesDocId = 'training_recipes';

/// Units that measure mass or volume, declared independently of the
/// generator: only a quantity in one of these may be multiplied.
const Set<String> _kMassVolumeUnits = <String>{
  'g', 'kg', 'mg', 'lb', 'lbs', 'oz',
  'ml', 'l', 'tsp', 'tbsp', 'cup', 'cups',
};

/// Fraction glyphs the operator's kitchen types, decoded here so the
/// quantity check never borrows the generator's table.
const Map<String, double> _kFractionGlyphs = <String, double>{
  '¼': 0.25, // one quarter
  '½': 0.5, // one half
  '¾': 0.75, // three quarters
  '⅓': 1 / 3, // one third
  '⅔': 2 / 3, // two thirds
};

/// Every card of the routed Recipes manual, in reading order.
List<HandbookUnit> _recipeCards() {
  final doc = kBarrioTrainingDocs[_kRecipesDocId];
  expect(doc, isNotNull,
      reason: 'the Recipes manual must be registered in kBarrioTrainingDocs');
  return <HandbookUnit>[
    for (final chapter in doc!.chapters) ...chapter.units,
  ];
}

/// The ingredient lines a card body actually prints: its blank-line
/// separated paragraphs that open with the Markdown list bullet, bullet
/// stripped. Read straight off the live body, never off the parse.
List<String> _ingredientLinesOf(String body) => <String>[
      for (final paragraph in body.split('\n\n'))
        if (paragraph.startsWith('- ')) paragraph.substring(2).trim(),
    ]..removeWhere((String line) => line.isEmpty);

/// The number [raw] literally opens with, and where it ends. Null when the
/// line opens with no number at all.
({double value, int end})? _leadingNumber(String raw) {
  if (raw.isEmpty) return null;
  final glyph = _kFractionGlyphs[raw[0]];
  if (glyph != null) return (value: glyph, end: 1);
  final match = RegExp(r'^\d+(?:\.\d+)?(?:/\d+(?:\.\d+)?)?').firstMatch(raw);
  if (match == null) return null;
  final token = match.group(0)!;
  if (token.contains('/')) {
    final parts = token.split('/');
    final bottom = double.parse(parts[1]);
    if (bottom == 0) return null;
    return (value: double.parse(parts[0]) / bottom, end: match.end);
  }
  return (value: double.parse(token), end: match.end);
}

void main() {
  group('recipe ingredient data', () {
    test('the manual carries ingredient data at all', () {
      // Non-vacuity: every comparison below is trivially true against an
      // empty bank, so the bank has to be real first.
      expect(kBarrioRecipeIngredients, isNotEmpty);
      final all = kBarrioRecipeIngredients.values.expand((e) => e).toList();
      expect(all, isNotEmpty);
      expect(all.any((e) => e.scalable), isTrue,
          reason: 'a manual of recipes must have something worth scaling');
      expect(all.any((e) => !e.scalable), isTrue,
          reason: 'the hold rule must actually be reached by real lines');
    });

    test('the parse covers every ingredient line, in order, with none '
        'silently dropped', () {
      // THE COVERAGE GUARD. The lines come from the live card bodies; the
      // raws come from the committed data. A dropped, added, reordered or
      // edited entry fails here.
      var linesSeen = 0;
      for (final card in _recipeCards()) {
        final lines = _ingredientLinesOf(card.body);
        final entries = kBarrioRecipeIngredients[card.id];
        if (lines.isEmpty) {
          expect(entries, anyOf(isNull, isEmpty),
              reason: '${card.id} prints no ingredient line, so it must '
                  'carry no ingredient data');
          continue;
        }
        expect(entries, isNotNull,
            reason: '${card.id} prints ${lines.length} ingredient line(s) '
                'but carries no ingredient data; regenerate with '
                'tool/barrio_recipe_ingredients_generator.py');
        expect(entries!.map((e) => e.raw).toList(), lines,
            reason: '${card.id}: the parsed lines must be exactly the lines '
                'the card body prints, in the same order');
        linesSeen += lines.length;
      }
      expect(linesSeen, greaterThan(0),
          reason: 'no ingredient line was checked, so this guard proved '
              'nothing; the manual or its body format changed');
    });

    test('every parsed line is an exact substring of its own card body', () {
      // THE TIE. Even with the counts lined up, a raw that is not literally
      // in the body means a calculator would show text the reader never saw.
      final cardsById = <String, HandbookUnit>{
        for (final card in _recipeCards()) card.id: card,
      };
      for (final entry in kBarrioRecipeIngredients.entries) {
        final card = cardsById[entry.key];
        expect(card, isNotNull,
            reason: '${entry.key} is not a card of the Recipes manual; a '
                'stale unit id would attach data to the wrong recipe');
        for (final ingredient in entry.value) {
          expect(card!.body.contains(ingredient.raw), isTrue,
              reason: '${entry.key}: "${ingredient.raw}" does not appear in '
                  'that card\'s body word for word');
        }
      }
    });

    test('a scalable line carries one quantity in a unit of mass or volume',
        () {
      for (final entry in kBarrioRecipeIngredients.entries) {
        for (final ingredient in entry.value.where((i) => i.scalable)) {
          final where = '${entry.key}: "${ingredient.raw}"';
          expect(ingredient.hold, isNull,
              reason: '$where is scalable, so it must not name a hold');
          expect(ingredient.quantity, isNotNull,
              reason: '$where is scalable, so it must carry a quantity');
          expect(ingredient.unit, isNotNull,
              reason: '$where is scalable, so it must carry a unit');
          expect(_kMassVolumeUnits.contains(ingredient.unit!.toLowerCase()),
              isTrue,
              reason: '$where scales on "${ingredient.unit}", which is not a '
                  'unit of mass or volume; only those divide cleanly');
        }
      }
    });

    test('a held line says why it is held', () {
      for (final entry in kBarrioRecipeIngredients.entries) {
        for (final ingredient in entry.value.where((i) => !i.scalable)) {
          final where = '${entry.key}: "${ingredient.raw}"';
          expect(ingredient.hold, isNotNull,
              reason: '$where is held back with no reason given; a cook '
                  'reading a calculator deserves to know why a line did '
                  'not move');
          if (ingredient.hold == BarrioIngredientHold.noQuantity) {
            expect(ingredient.quantity, isNull,
                reason: '$where claims no quantity but carries one');
          }
          if (ingredient.hold == BarrioIngredientHold.containerCount ||
              ingredient.hold == BarrioIngredientHold.wholeItemCount) {
            expect(ingredient.unit, isNotNull,
                reason: '$where counts something, so it must name what');
            expect(_kMassVolumeUnits.contains(ingredient.unit!.toLowerCase()),
                isFalse,
                reason: '$where is held as a count but its unit measures '
                    'mass or volume, which should have been scalable');
          }
        }
      }
    });

    test('the parsed quantity is the number the line actually prints', () {
      // Re-read off the raw text with this file's own reader, so a parser
      // bug cannot supply its own expected value.
      for (final entry in kBarrioRecipeIngredients.entries) {
        for (final ingredient in entry.value) {
          final where = '${entry.key}: "${ingredient.raw}"';
          final read = _leadingNumber(ingredient.raw);
          if (ingredient.quantity == null) {
            expect(read, isNull,
                reason: '$where carries no quantity, but the line opens with '
                    'the number ${read?.value}');
            continue;
          }
          expect(read, isNotNull,
              reason: '$where carries quantity ${ingredient.quantity}, but '
                  'the line does not open with a number');
          expect(read!.value, closeTo(ingredient.quantity!, 1e-9),
              reason: '$where was parsed as ${ingredient.quantity} but the '
                  'line opens with ${read.value}');
          if (ingredient.unit != null) {
            expect(ingredient.raw.contains(ingredient.unit!), isTrue,
                reason: '$where was given the unit "${ingredient.unit}", '
                    'which the line never prints');
            if (ingredient.hold != BarrioIngredientHold.range) {
              expect(
                  ingredient.raw
                      .substring(read.end)
                      .trimLeft()
                      .startsWith(ingredient.unit!),
                  isTrue,
                  reason: '$where: the unit must be the word attached to the '
                      'quantity, not one found elsewhere in the line');
            }
          }
        }
      }
    });

    test('every line names the ingredient it is an amount of', () {
      for (final entry in kBarrioRecipeIngredients.entries) {
        for (final ingredient in entry.value) {
          final where = '${entry.key}: "${ingredient.raw}"';
          expect(ingredient.name.trim(), isNotEmpty,
              reason: '$where has no ingredient name');
          expect(ingredient.raw.trim().endsWith(ingredient.name), isTrue,
              reason: '$where names "${ingredient.name}", which is not the '
                  'tail of the line it came from');
        }
      }
    });

    test('no card outside the Recipes manual carries ingredient data', () {
      final recipeIds = _recipeCards().map((c) => c.id).toSet();
      final strays = kBarrioRecipeIngredients.keys
          .where((id) => !recipeIds.contains(id))
          .toList();
      expect(strays, isEmpty,
          reason: 'these unit ids are not Recipes cards: ${strays.join(", ")}');
      // The lookup must stay quiet for every other manual.
      expect(barrioRecipeIngredientsForUnit('training_wine_c0_u0'), isEmpty);
      expect(barrioRecipeIngredientsForUnit('no_such_unit'), isEmpty);
    });
  });
}
