// Phase 7.55e.5 — Deterministic mock POS/labor integration replay seed.
//
// Generates realistic historical and current-week operational data through
// the same model path that live Phase 8 adapters will use:
//   mock POS/labor replay -> canonical app models -> SQLite operational tables.
//
// Replaces direct DemoData fixture copies in SQLite bootstrap.
// DemoData still exists for static preview paths (7.55e.6 handles cleanup).
//
// Phase 7.55f.4 — Parameterized by scenario business date.
// generateForDate(isoDate) produces coherent output for any date.
// The default scenario (2026-03-27) is preserved for backward compat.
//
// All variation is deterministic — no random generators.

import '../models/shift_record.dart';
import '../models/week_record.dart';
import '../services/labor_model.dart';

/// Describes the mock replay scenario for a given business date.
class MockReplayScenario {
  final String currentBusinessDate; // ISO date, e.g. '2026-03-27'
  final String currentWeekId;       // e.g. '2026-W13'
  final String openShiftDayLabel;   // e.g. 'Fri'
  final String openShiftDaypart;    // e.g. 'dinner'

  const MockReplayScenario({
    required this.currentBusinessDate,
    required this.currentWeekId,
    required this.openShiftDayLabel,
    required this.openShiftDaypart,
  });
}

/// Output of the mock integration replay generator.
class MockReplayOutput {
  final List<ShiftRecord> historicalClosedShifts;
  final List<ShiftRecord> currentWeekShifts;
  final List<WeekRecord> weekRecords;
  final MockReplayScenario scenario;

  const MockReplayOutput({
    required this.historicalClosedShifts,
    required this.currentWeekShifts,
    required this.weekRecords,
    required this.scenario,
  });
}

/// One service period's deterministic locked target band, exposed by
/// [MockIntegrationReplaySeed.demoDaypartTargetBand] so the demo cycle
/// seeder can stamp differentiated per-period rows without reaching into
/// the seed's private maps.
class DemoDaypartTargetBand {
  final double targetCPLH;
  final double targetSPLH;
  final double targetPPA;
  final double opzFloorCPLH;
  final double opzCeilingCPLH;

  const DemoDaypartTargetBand({
    required this.targetCPLH,
    required this.targetSPLH,
    required this.targetPPA,
    required this.opzFloorCPLH,
    required this.opzCeilingCPLH,
  });
}

/// Deterministic mock POS/labor replay generator.
///
/// Produces operationally coherent shift and week records that behave like
/// Phase 8 live POS/labor adapter output. All derived metrics use
/// [LaborModel] as the single formula source.
///
/// No randomness — all variation is deterministic from week/day indices.
class MockIntegrationReplaySeed {
  MockIntegrationReplaySeed._();

  /// Source system identifier for records generated by this replay.
  static const String sourceSystem = 'mock_pos_labor_replay';

  /// Per-Daypart V1 (Slice 1, Gap 22) — deterministic timing-profile id
  /// used by the demo seeder so closed shifts carry a
  /// `business_timing_profile_id` + `business_timing_profile_version_id`
  /// + `service_period_key` that round-trip through the standard read
  /// path. Production live writes resolve this from
  /// `restaurant_timing_configs` via the BusinessTimingProfileResolver;
  /// the demo deterministic id stays stable across runs.
  static const String demoBusinessTimingProfileId =
      'demo_business_timing_profile_v1';

  /// Per-Daypart V1 (Slice 1) — per-period locked target stamps the
  /// demo seeder writes onto closed shifts so the History grader and
  /// per-period analytics consumers see realistic per-period bands.
  /// Values mirror the demo cycle's intended per-period output (the
  /// recommendation engine would produce these from the seeded
  /// candidate cohort; the seeder mirrors them directly so reseed runs
  /// are deterministic).
  static const Map<String, double> _daypartTargetCPLH = {
    'lunch': 4.40,
    'dinner': 4.80,
    'late_night': 3.90,
  };
  static const Map<String, double> _daypartTargetSPLH = {
    'lunch': 165.0,
    'dinner': 200.0,
    'late_night': 150.0,
  };
  static const Map<String, double> _daypartTargetPPA = {
    'lunch': 40.50,
    'dinner': 43.00,
    'late_night': 38.50,
  };
  static const Map<String, double> _daypartOpzFloor = {
    'lunch': 4.00,
    'dinner': 4.30,
    'late_night': 3.50,
  };
  static const Map<String, double> _daypartOpzCeiling = {
    'lunch': 5.00,
    'dinner': 5.40,
    'late_night': 4.40,
  };

  /// Service-period ids the demo scenario is built around, in display
  /// order. These are the same keys used by the demo timing config's
  /// `service_period_definitions_json` and by [demoDaypartTargetBand].
  static const List<String> demoServicePeriodIds = [
    'lunch',
    'dinner',
    'late_night',
  ];

  /// Per-Daypart V1 demo fidelity — the deterministic per-period locked
  /// target band the demo seeder stamps onto the demo `TargetCycle`'s
  /// per-period rows when the recommendation cohort yields no
  /// per-period stats for [periodId]. Returns `null` for an unknown
  /// period id (Design Rule 2 — absent means unavailable, never a `0`
  /// sentinel; the caller decides the fallback). The five values are
  /// the same constants already stamped onto demo closed shifts so the
  /// cycle and the history grader agree.
  static DemoDaypartTargetBand? demoDaypartTargetBand(String periodId) {
    final cplh = _daypartTargetCPLH[periodId];
    if (cplh == null) return null;
    return DemoDaypartTargetBand(
      targetCPLH: cplh,
      targetSPLH: _daypartTargetSPLH[periodId] ?? _targetSPLH,
      targetPPA: _daypartTargetPPA[periodId] ?? _targetPPA,
      opzFloorCPLH: _daypartOpzFloor[periodId]!,
      opzCeilingCPLH: _daypartOpzCeiling[periodId]!,
    );
  }

  /// Default mock replay business date (Friday dinner scenario).
  static const String defaultBusinessDate = '2026-03-27';

  /// Current week for the default scenario (backward compat).
  static const String currentWeekId = '2026-W13';

  /// Historical weekIds for the default scenario, newest first (backward compat).
  static const List<String> historicalWeekIds = [
    '2026-W12', '2026-W11', '2026-W10', '2026-W09',
    '2026-W08', '2026-W07', '2026-W06', '2026-W05',
  ];

  // ── Target standards (from MeridianConfig / BaselineData) ───────────────
  static const double _targetCPLH = 4.58;
  static const double _targetSPLH = 180.0;
  static const double _targetPPA = 41.50;
  static const double _fohWage = 16.50;
  static const double _bohWage = 21.35;
  static const double _theoreticalLaborPct = 20.48;

  // ── Operating pattern: 14 shifts per week ───────────────────────────────
  // Mon–Thu: lunch + dinner. Fri: lunch + dinner + late_night.
  // Sat: dinner + late_night. Sun: dinner.
  static const List<(String, String)> weekSlots = [
    ('Mon', 'lunch'), ('Mon', 'dinner'),
    ('Tue', 'lunch'), ('Tue', 'dinner'),
    ('Wed', 'lunch'), ('Wed', 'dinner'),
    ('Thu', 'lunch'), ('Thu', 'dinner'),
    ('Fri', 'lunch'), ('Fri', 'dinner'), ('Fri', 'late_night'),
    ('Sat', 'dinner'), ('Sat', 'late_night'),
    ('Sun', 'dinner'),
  ];

  // ── Day-of-week base cover distribution (weekly sum = 1200) ─────────────
  // Monday slowest, Saturday dinner strongest, Sunday soft.
  static const Map<String, int> _dayBaseCovers = {
    'Mon': 140, 'Tue': 150, 'Wed': 160, 'Thu': 190,
    'Fri': 220, 'Sat': 230, 'Sun': 110,
  };

  // ── Daypart split ratios per day of week ────────────────────────────────
  static const Map<String, Map<String, double>> _daypartRatios = {
    'Mon': {'lunch': 0.45, 'dinner': 0.55},
    'Tue': {'lunch': 0.45, 'dinner': 0.55},
    'Wed': {'lunch': 0.45, 'dinner': 0.55},
    'Thu': {'lunch': 0.45, 'dinner': 0.55},
    'Fri': {'lunch': 0.45, 'dinner': 0.40, 'late_night': 0.15},
    'Sat': {'dinner': 0.775, 'late_night': 0.225},
    'Sun': {'dinner': 1.0},
  };

  // ── Daypart PPA offsets from target PPA ─────────────────────────────────
  // Dinner commands higher PPA, late_night lower.
  static const Map<String, double> _daypartPPAOffset = {
    'lunch': -1.00,
    'dinner': 1.50,
    'late_night': -3.00,
  };

  // ── Week-level deterministic variation ──────────────────────────────────
  // Index 0 = oldest historical week, index 7 = newest.
  // Produces realistic week-to-week variation in covers, PPA, and CPLH.
  static const List<double> _weekCoverScales = [
    1.00, 0.97, 1.03, 0.95, 1.02, 1.05, 0.98, 0.96,
  ];
  static const List<double> _weekPPAShifts = [
    0.0, -0.50, 0.80, -1.20, 0.40, 1.00, -0.80, 0.60,
  ];
  static const List<double> _weekCPLHScales = [
    1.00, 0.98, 1.02, 0.95, 1.01, 1.03, 0.97, 1.00,
  ];

  // ── Open shift in-progress state ────────────────────────────────────────
  // Deterministic mid-service snapshot for the current open shift.
  // ~63% through service: covers arriving but scheduled hours committed.
  static const double openProgressFraction = 0.63;
  static const String openShiftTimeLabel = '7:45 PM';
  static const String openShiftServiceElapsedLabel = '3h 15m into service';

  /// Source shift ID for the default scenario's open shift (backward compat).
  static const String openShiftSourceShiftId = 'w13-fri-dinner-open';

  /// Deterministic source shift ID for seeded open_shift_snapshots rows.
  ///
  /// Format: `w{weekNum}-{day}-{daypart}-{status}`
  /// e.g. `w13-fri-late_night-projected`, `w13-fri-lunch-closed`.
  /// The current open shift uses [openShiftSourceShiftIdFor] instead.
  static String snapshotSourceShiftId({
    required String weekId,
    required String dayLabel,
    required String daypart,
    required String status,
  }) {
    final weekNum = weekId.split('-W').last;
    return 'w$weekNum-${dayLabel.toLowerCase()}-$daypart-$status';
  }

  /// Source shift ID for the scenario's open shift.
  static String openShiftSourceShiftIdFor(MockReplayScenario scenario) {
    final weekNum = scenario.currentWeekId.split('-W').last;
    return 'w$weekNum-${scenario.openShiftDayLabel.toLowerCase()}'
        '-${scenario.openShiftDaypart}-open';
  }

  /// Default-scenario output — cached for backward compatibility.
  static final MockReplayOutput output = generateForDate(defaultBusinessDate);

  // ── Parameterized generator ─────────────────────────────────────────────

  /// Generates a full mock replay output for an arbitrary business date.
  ///
  /// The default business date [defaultBusinessDate] produces output
  /// identical to the pre-7.55f.4 fixed generator.
  static MockReplayOutput generateForDate(String isoBusinessDate) {
    final parts = isoBusinessDate.split('-');
    final dt = DateTime(
        int.parse(parts[0]), int.parse(parts[1]), int.parse(parts[2]));
    final dayLabel = _dayLabelFromDate(dt);
    final weekId = _weekIdFromDate(dt);
    final dayIndex = dt.weekday - 1; // 0=Mon .. 6=Sun

    // 8 historical weeks before the current week (newest first)
    final currentMonday =
        DateTime(dt.year, dt.month, dt.day - (dt.weekday - 1));
    final histWeekIds = <String>[];
    for (int i = 1; i <= 8; i++) {
      final prev = DateTime(
          currentMonday.year, currentMonday.month, currentMonday.day - 7 * i);
      histWeekIds.add(_weekIdFromDate(prev));
    }

    final allHistorical = <ShiftRecord>[];
    final weekRecords = <WeekRecord>[];

    // Generate oldest first so week indices map to variation arrays.
    // After each week's shifts are added to `allHistorical`, derive its
    // WeekRecord against the cumulative pool so the frozen month + 60-day
    // dollar-impact windows (Phase 7.55q.10) reflect what would have been
    // on the live Variance card the moment that week closed.
    for (int wi = 0; wi < histWeekIds.length; wi++) {
      final wid = histWeekIds[histWeekIds.length - 1 - wi];
      final shifts = _generateClosedWeek(wid, wi);
      allHistorical.addAll(shifts);
      weekRecords.add(_deriveWeekRecord(wid, shifts, allHistorical));
    }
    weekRecords.sort((a, b) => b.weekId.compareTo(a.weekId));

    final currentWeekShifts =
        _generateCurrentWeekForDate(weekId, dayIndex);

    // Open shift is always dinner (see prompt 7.55f.4 rules).
    final scenario = MockReplayScenario(
      currentBusinessDate: isoBusinessDate,
      currentWeekId: weekId,
      openShiftDayLabel: dayLabel,
      openShiftDaypart: 'dinner',
    );

    return MockReplayOutput(
      historicalClosedShifts: allHistorical,
      currentWeekShifts: currentWeekShifts,
      weekRecords: weekRecords,
      scenario: scenario,
    );
  }

  // ── Day-of-week helpers ─────────────────────────────────────────────────

  static const _dayLabels = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];

  static String _dayLabelFromDate(DateTime dt) => _dayLabels[dt.weekday - 1];

  /// Compute ISO week-id from a [DateTime].
  ///
  /// Uses UTC internally to avoid DST-induced off-by-one in
  /// [DateTime.difference] (the spring-forward day is only 23 hours).
  static String _weekIdFromDate(DateTime dt) {
    final monday = DateTime.utc(dt.year, dt.month, dt.day - (dt.weekday - 1));
    final jan4 = DateTime.utc(monday.year, 1, 4);
    final w1Monday =
        DateTime.utc(jan4.year, jan4.month, jan4.day - (jan4.weekday - 1));
    final weekNum =
        ((monday.difference(w1Monday).inDays) / 7).floor() + 1;
    return '${monday.year}-W${weekNum.toString().padLeft(2, '0')}';
  }

  // ── Generator ───────────────────────────────────────────────────────────

  /// Generate all 14 closed shifts for one historical week.
  static List<ShiftRecord> _generateClosedWeek(String weekId, int weekIndex) {
    final coverScale = _weekCoverScales[weekIndex];
    final ppaShift = _weekPPAShifts[weekIndex];
    final cplhScale = _weekCPLHScales[weekIndex];

    final shifts = <ShiftRecord>[];
    for (final slot in weekSlots) {
      shifts.add(_generateShift(
        weekId: weekId,
        day: slot.$1,
        daypart: slot.$2,
        status: 'closed',
        coverScale: coverScale,
        ppaShift: ppaShift,
        cplhScale: cplhScale,
        weekIndex: weekIndex,
      ));
    }
    return shifts;
  }

  /// Generate one shift with deterministic variation.
  static ShiftRecord _generateShift({
    required String weekId,
    required String day,
    required String daypart,
    required String status,
    required double coverScale,
    required double ppaShift,
    required double cplhScale,
    required int weekIndex,
  }) {
    final dayIndex =
        const ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'].indexOf(day);
    final dayCovers = _dayBaseCovers[day]!;
    final ratio = _daypartRatios[day]![daypart]!;
    final forecastCovers = (dayCovers * ratio).round();

    final businessDate = _businessDateFromWeekDay(weekId, day)!;

    if (status != 'closed') {
      // Projected: use forecast values at target rates.
      final basePPA = _targetPPA + (_daypartPPAOffset[daypart] ?? 0);
      final foh = LaborModel.modelFohHours(forecastCovers, _targetCPLH);
      final boh = LaborModel.modelBohHoursFromSales(
        forecastCovers * basePPA,
        _targetSPLH,
      );
      // 7.58.4: round-trip the lever id through `determineLever` against
      // the same row inputs so the projected record matches what the
      // engine would say. Wages match target; the wage axis cannot fire.
      // The empty-candidate fallback (`covers_down`) — and any axis that
      // does fire on the daypart PPA offset — is engine truth, not a
      // hand-coded sentinel. The non-closed `on_model` sentinel remains
      // the property of `CurrentWeekState.shiftRecordFromSnapshot`
      // (open snapshots), per the phase 7.58 contract Output Cardinality.
      final projectedLever = LaborModel.determineLever(
        actualCovers: forecastCovers,
        forecastCovers: forecastCovers,
        avgCPLH: _targetCPLH,
        avgPPA: basePPA,
        targetCPLH: _targetCPLH,
        targetPPA: _targetPPA,
        avgSPLH: _targetSPLH,
        targetSPLH: _targetSPLH,
        avgFohBlendedWage: _fohWage,
        targetFohWage: _fohWage,
        avgBohBlendedWage: _bohWage,
        targetBohWage: _bohWage,
        scheduledFohHours: foh,
        modelFohHours: foh,
        scheduledBohHours: boh,
        modelBohHours: boh,
      );
      return ShiftRecord(
        weekId: weekId,
        dayLabel: day,
        daypart: daypart,
        status: status,
        businessDate: businessDate,
        covers: forecastCovers,
        forecastCovers: forecastCovers,
        ppa: basePPA,
        cplh: _targetCPLH,
        splh: _targetSPLH,
        fohHours: foh,
        bohHours: boh,
        theoreticalLaborPct: _theoreticalLaborPct,
        primaryLever: projectedLever.toUpperCase(),
        sourceSystem: sourceSystem,
        // Per-Daypart V1 (Slice 1, Gap 22) — timing-provenance stamps
        // also on the projected/open-shift seed branch so reads see a
        // consistent shape across closed and projected rows.
        businessTimingProfileId: demoBusinessTimingProfileId,
        businessTimingProfileVersionId: demoBusinessTimingProfileId,
        servicePeriodKey: daypart,
      );
    }

    // ── Closed shift with deterministic variation ─────────────────────────

    // Per-day jitter: deterministic +/- 3% (different per week × day).
    final dayJitter =
        0.97 + ((weekIndex * 3 + dayIndex * 5 + 1) % 7) * 0.01;

    final rawCovers = dayCovers * ratio * coverScale * dayJitter;
    final covers = rawCovers.round().clamp(10, 9999);

    final basePPA = _targetPPA + (_daypartPPAOffset[daypart] ?? 0);
    final ppa = double.parse((basePPA + ppaShift).toStringAsFixed(2));

    final sales = covers * ppa;
    final actualCPLH = _targetCPLH * cplhScale;
    final fohHours = LaborModel.modelFohHours(covers, actualCPLH);
    final bohHours = LaborModel.modelBohHoursFromSales(sales, _targetSPLH);

    final cplh = fohHours > 0 ? covers / fohHours : _targetCPLH;
    final splh = bohHours > 0 ? sales / bohHours : _targetSPLH;

    // 7.58.4 / F-3: pass the full axis set (covers + ppa + cplh + splh +
    // wages + hours-flex) so the per-shift seed lever matches what
    // `ShiftFactBuilder.fromClosedShiftInput` would emit for the same
    // inputs. Seed wages match target by construction (sales-side actuals
    // are scaled, not wages), so the wage axis stays quiet — but it is
    // now passed so the round-trip test pins fixture parity with the
    // live producer.
    final modelFoh = LaborModel.modelFohHours(covers, _targetCPLH);
    final modelBoh = LaborModel.modelBohHoursFromSales(sales, _targetSPLH);
    final lever = LaborModel.determineLever(
      actualCovers: covers,
      forecastCovers: forecastCovers,
      avgCPLH: cplh,
      avgPPA: ppa,
      targetCPLH: _targetCPLH,
      targetPPA: _targetPPA,
      avgSPLH: splh,
      targetSPLH: _targetSPLH,
      avgFohBlendedWage: _fohWage,
      targetFohWage: _fohWage,
      avgBohBlendedWage: _bohWage,
      targetBohWage: _bohWage,
      scheduledFohHours: fohHours,
      modelFohHours: modelFoh,
      scheduledBohHours: bohHours,
      modelBohHours: modelBoh,
    );

    return ShiftRecord(
      weekId: weekId,
      dayLabel: day,
      daypart: daypart,
      status: 'closed',
      businessDate: businessDate,
      covers: covers,
      forecastCovers: forecastCovers,
      ppa: ppa,
      cplh: double.parse(cplh.toStringAsFixed(2)),
      splh: double.parse(splh.toStringAsFixed(2)),
      fohHours: fohHours,
      bohHours: bohHours,
      theoreticalLaborPct: _theoreticalLaborPct,
      primaryLever: lever.toUpperCase(),
      storedFohLaborDollar: fohHours * _fohWage,
      storedBohLaborDollar: bohHours * _bohWage,
      sourceSystem: sourceSystem,
      // Per-Daypart V1 (Slice 1, Gap 22 fix): demo seeder writes
      // shift_records with the demo restaurant's timing-provenance
      // fields populated. The demo timing config (see
      // `sqlite_database_seed.dart`) is hardcoded to a 3-period
      // setup keyed on profile_id `demoBusinessTimingProfileId`. The
      // `daypart` value already carries the service-period identifier
      // ('lunch' / 'dinner' / 'late_night'), so the same string is the
      // canonical service period key.
      businessTimingProfileId: demoBusinessTimingProfileId,
      businessTimingProfileVersionId: demoBusinessTimingProfileId,
      servicePeriodKey: daypart,
      // Per-Daypart V1 (Slice 1): per-shift per-period locked target
      // stamps. Demo regenerate runs through the same DAOs as
      // production close-shifts, so these stamps mirror the demo
      // cycle's per-period rows. Stamping at seed time keeps the
      // history grader honest: each closed shift is judged against
      // its period's locked target, not the whole-day pool.
      daypartTargetCPLH: _daypartTargetCPLH[daypart],
      daypartTargetSPLH: _daypartTargetSPLH[daypart],
      daypartTargetPPA: _daypartTargetPPA[daypart] ?? _targetPPA,
      daypartOpzFloorCPLH: _daypartOpzFloor[daypart],
      daypartOpzCeilingCPLH: _daypartOpzCeiling[daypart],
    );
  }

  /// Derive a [WeekRecord] from a week's closed shifts.
  ///
  /// All aggregate metrics are computed from the shift-level data.
  /// Target fields are left null — the backfill pass stamps them.
  ///
  /// Phase 7.55q.10: also captures `closedAt` (last business date of the
  /// week) and the frozen month + 60-day dollar-impact windows by filtering
  /// [historicalPool] (all historical shifts seeded so far, including this
  /// week's). Mirrors the runtime `_buildWeekRecord` capture in
  /// `lib/services/shift_service.dart` so demo history shows the same
  /// 4-row Dollar Impact view the live Variance card would have shown.
  static WeekRecord _deriveWeekRecord(
    String weekId,
    List<ShiftRecord> shifts,
    List<ShiftRecord> historicalPool,
  ) {
    final totalCovers = shifts.fold<int>(0, (s, r) => s + r.covers);
    final forecastCovers = shifts.fold<int>(0, (s, r) => s + r.forecastCovers);
    final totalFoh = shifts.fold<int>(0, (s, r) => s + r.fohHours);
    final totalBoh = shifts.fold<int>(0, (s, r) => s + r.bohHours);
    final totalSales = shifts.fold<double>(0, (s, r) => s + r.actualSales);
    final totalLabor = shifts.fold<double>(0, (s, r) => s + r.totalLaborDollar);

    final avgPPA = totalCovers > 0 ? totalSales / totalCovers : _targetPPA;
    final avgCPLH = totalFoh > 0 ? totalCovers / totalFoh : _targetCPLH;
    final actualLaborPct =
        totalSales > 0 ? totalLabor / totalSales * 100 : 0.0;

    final dollarGap = LaborModel.dollarGap(
      totalLabor,
      totalCovers,
      avgPPA,
      targetCPLH: _targetCPLH,
      targetSPLH: _targetSPLH,
      fohWage: _fohWage,
      bohWage: _bohWage,
    );

    final avgSPLH = totalBoh > 0 ? totalSales / totalBoh : _targetSPLH;
    // 7.58.4 / F-3: include wages + hours-flex so the seed-derived
    // weekly lever mirrors `ShiftService._buildWeekRecord` (which feeds
    // the same axis set into `determineLever` at close time). Demo
    // wages match target — wage axis stays quiet — but the call shape
    // now matches the live producer for round-trip parity.
    final wkFohLaborDollar =
        shifts.fold<double>(0, (s, r) => s + r.fohLaborDollar);
    final wkBohLaborDollar =
        shifts.fold<double>(0, (s, r) => s + r.bohLaborDollar);
    final wkBlendedFohWage =
        totalFoh > 0 ? wkFohLaborDollar / totalFoh : _fohWage;
    final wkBlendedBohWage =
        totalBoh > 0 ? wkBohLaborDollar / totalBoh : _bohWage;
    final wkModelFoh = LaborModel.modelFohHours(totalCovers, _targetCPLH);
    final wkModelBoh =
        LaborModel.modelBohHoursFromSales(totalSales, _targetSPLH);
    final lever = LaborModel.determineLever(
      actualCovers: totalCovers,
      forecastCovers: forecastCovers,
      avgCPLH: avgCPLH,
      avgPPA: avgPPA,
      targetCPLH: _targetCPLH,
      targetPPA: _targetPPA,
      avgSPLH: avgSPLH,
      targetSPLH: _targetSPLH,
      avgFohBlendedWage: wkBlendedFohWage,
      targetFohWage: _fohWage,
      avgBohBlendedWage: wkBlendedBohWage,
      targetBohWage: _bohWage,
      scheduledFohHours: totalFoh,
      modelFohHours: wkModelFoh,
      scheduledBohHours: totalBoh,
      modelBohHours: wkModelBoh,
    );

    // ── Frozen Dollar Impact windows (7.55q.10) ────────────────────────
    // Compute the month + 60-day dollar-impact windows that the live
    // Variance card would have shown the moment this week closed, plus
    // the close timestamp itself. Reuses the same window math the
    // runtime path uses; see `_buildWeekRecord` and
    // `_accumulateDollarImpact` in `lib/services/shift_service.dart`.
    final closedAt = shifts
        .map((s) => s.businessDate)
        .whereType<String>()
        .fold<String?>(null,
            (max, d) => max == null || d.compareTo(max) > 0 ? d : max);
    double? monthDollarImpact;
    double? sixtyDayDollarImpact;
    if (closedAt != null) {
      final closedDt = _parseDate(closedAt);
      final monthStart =
          _formatDate(DateTime.utc(closedDt.year, closedDt.month, 1));
      final monthShifts = historicalPool.where((s) {
        final bd = s.businessDate;
        return bd != null &&
            bd.compareTo(monthStart) >= 0 &&
            bd.compareTo(closedAt) <= 0;
      }).toList();
      monthDollarImpact = _accumulateDollarImpactSeed(monthShifts);
      final sixtyDayStart =
          _formatDate(closedDt.subtract(const Duration(days: 59)));
      final sixtyDayShifts = historicalPool.where((s) {
        final bd = s.businessDate;
        return bd != null &&
            bd.compareTo(sixtyDayStart) >= 0 &&
            bd.compareTo(closedAt) <= 0;
      }).toList();
      sixtyDayDollarImpact = _accumulateDollarImpactSeed(sixtyDayShifts);
    }

    return WeekRecord(
      weekId: weekId,
      weekLabel: _weekLabel(weekId),
      totalCovers: totalCovers,
      forecastCovers: forecastCovers,
      totalFohHours: totalFoh,
      totalBohHours: totalBoh,
      avgPPA: double.parse(avgPPA.toStringAsFixed(2)),
      avgCPLH: double.parse(avgCPLH.toStringAsFixed(2)),
      theoreticalLaborPct: _theoreticalLaborPct,
      actualLaborPct: double.parse(actualLaborPct.toStringAsFixed(2)),
      dollarGap: double.parse(dollarGap.toStringAsFixed(2)),
      primaryLeverId: lever,
      shiftsCompleted: shifts.length,
      blendedFohWage: _fohWage,
      blendedBohWage: _bohWage,
      monthDollarImpact: monthDollarImpact,
      sixtyDayDollarImpact: sixtyDayDollarImpact,
      closedAt: closedAt,
    );
  }

  /// Seed-side mirror of `ShiftService._accumulateDollarImpact`. Uses the
  /// seed's own target standards instead of per-shift locked targets,
  /// because seed shifts don't carry `targetCPLH` / `targetSPLH` /
  /// `targetFohWage` / `targetBohWage` (those come from the per-shift
  /// backfill that runs after seed insertion). Same formula otherwise:
  /// actualLabor − (modelFoh × fohWage + modelBoh × bohWage).
  static double _accumulateDollarImpactSeed(List<ShiftRecord> shifts) {
    return shifts.fold<double>(0, (sum, s) {
      final actualLabor = s.fohLaborDollar + s.bohLaborDollar;
      final modelFoh = LaborModel.modelFohHours(s.covers, _targetCPLH);
      final modelBoh =
          LaborModel.modelBohHoursFromSales(s.actualSales, _targetSPLH);
      final theoreticalLabor = modelFoh * _fohWage + modelBoh * _bohWage;
      return sum + (actualLabor - theoreticalLabor);
    });
  }

  // ── Date helpers (local to seed; mirror shift_service helpers) ─────────

  static DateTime _parseDate(String iso) {
    final p = iso.split('-');
    return DateTime.utc(int.parse(p[0]), int.parse(p[1]), int.parse(p[2]));
  }

  static String _formatDate(DateTime dt) =>
      '${dt.year}-${dt.month.toString().padLeft(2, '0')}-${dt.day.toString().padLeft(2, '0')}';

  /// Generate current week with status derived from the business date.
  ///
  /// [dayIndex] is 0=Mon .. 6=Sun within the current week.
  /// Shifts before the current day are closed. Shifts after are projected.
  /// On the current day: lunch is closed (earlier service), dinner is
  /// projected (will be open in snapshots), late_night is projected.
  static List<ShiftRecord> _generateCurrentWeekForDate(
      String weekId, int dayIndex) {
    const coverScale = 0.93;
    const ppaShift = 0.30;
    const cplhScale = 0.98;
    const weekIndex = 8; // distinct from historical indices

    final shifts = <ShiftRecord>[];
    for (final slot in weekSlots) {
      final slotDayIndex = _dayLabels.indexOf(slot.$1);

      String status;
      if (slotDayIndex < dayIndex) {
        // Past day — closed
        status = 'closed';
      } else if (slotDayIndex > dayIndex) {
        // Future day — projected
        status = 'projected';
      } else {
        // Current day — lunch is closed (earlier service), rest projected
        status = slot.$2 == 'lunch' ? 'closed' : 'projected';
      }

      shifts.add(_generateShift(
        weekId: weekId,
        day: slot.$1,
        daypart: slot.$2,
        status: status,
        coverScale: coverScale,
        ppaShift: ppaShift,
        cplhScale: cplhScale,
        weekIndex: weekIndex,
      ));
    }
    return shifts;
  }

  /// Human-readable week label from weekId (e.g., '2026-W05' -> 'Jan 26').
  static String _weekLabel(String weekId) {
    final parts = weekId.split('-W');
    if (parts.length != 2) return weekId;
    final year = int.tryParse(parts[0]);
    final week = int.tryParse(parts[1]);
    if (year == null || week == null) return weekId;

    final jan4 = DateTime(year, 1, 4);
    final w1Monday = jan4.subtract(Duration(days: jan4.weekday - 1));
    final monday = w1Monday.add(Duration(days: (week - 1) * 7));

    const months = [
      'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
      'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',
    ];
    return '${months[monday.month - 1]} ${monday.day}';
  }

  /// Strict YYYY-W## weekId + known dayLabel → ISO date, or null.
  static final _weekIdPattern = RegExp(r'^\d{4}-W\d{2}$');

  static String? _businessDateFromWeekDay(String weekId, String dayLabel) {
    const dayOffset = {
      'Mon': 0, 'Tue': 1, 'Wed': 2, 'Thu': 3,
      'Fri': 4, 'Sat': 5, 'Sun': 6,
    };
    if (!dayOffset.containsKey(dayLabel)) return null;
    if (!_weekIdPattern.hasMatch(weekId)) return null;
    final parts = weekId.split('-W');
    final year = int.tryParse(parts[0]);
    final week = int.tryParse(parts[1]);
    if (year == null || week == null) return null;
    final jan4 = DateTime(year, 1, 4);
    final w1Monday = jan4.subtract(Duration(days: jan4.weekday - 1));
    final monday = w1Monday.add(Duration(days: (week - 1) * 7));
    final date = monday.add(Duration(days: dayOffset[dayLabel]!));
    return '${date.year}-${date.month.toString().padLeft(2, '0')}-${date.day.toString().padLeft(2, '0')}';
  }
}
