// Lane B B11.1 — HandoffCodesRepository.
//
// Persistence layer for `public.handoff_codes`. Every read and write
// goes through `OperatorScopedRepository.withTenant` so the per-tenant
// RLS policy admits the row (primary defense: repository pattern;
// backup: RLS).
//
// Authority:
//   * db/migrations/202605131030_b11_1_auth_handoff_codes.sql
//     (table + RLS policy + indexes).
//   * docs/contracts/hardening_rls_and_repository_pattern_contract.md
//     (every operator-scoped table goes through OperatorScopedRepository;
//     no raw `package:postgres` import outside this directory).
//   * docs/archive/_execution/lane_b_features/01_product_rule_and_ia.md
//     (addendum A1: the opaque code is server-generated by
//     gen_random_bytes(16) — never client-supplied — and never travels
//     as a URL parameter to the proxy.)
//
// Methods:
//   * mint           — INSERT a fresh row. The opaque code is generated
//                      server-side via encode(gen_random_bytes(16),
//                      'base64') with URL-unsafe characters removed.
//                      Returns the code so the proxy can embed it in
//                      the response body. (Idempotency replay logic
//                      lives in the route file's in-memory cache; this
//                      method always inserts a new row.)
//   * redeem         — Atomic UPDATE … RETURNING. Sets consumed_at =
//                      now() and returns the redeemed row's
//                      (user_id, operator_id, target_path, source_
//                      device_fingerprint) — but ONLY when the
//                      predicate (consumed_at IS NULL AND expires_at >
//                      now() AND operator_id = caller's operator)
//                      holds. A returned-empty result is the signal
//                      for "404/410/403"; the caller distinguishes by
//                      classifying the row's state.
//   * countRecent    — Per-user 10/hour rate-limit counter. SELECT
//                      count(*) over rows from the same user within
//                      the trailing 1-hour window.
//   * reapExpired    — Inline reaper. DELETE rows whose expires_at is
//                      well past (1 day) so the partial indexes stay
//                      small. Called at the head of every mint
//                      transaction (the slice picked the inline reaper
//                      option — see the route file's "Lifecycle /
//                      background workers" lens entry).
//   * lookupForReplayCheck — Reads the current state of a code without
//                      mutating it. Used by the cross-operator audit
//                      classifier to distinguish "wrong operator (403)"
//                      from "expired or already consumed (410)".

import 'dart:convert';
import 'dart:math' as math;

import 'package:crypto/crypto.dart';

import '../operator_scoped_repository.dart';
import '../tenant_context.dart';

/// Read projection of a successfully-redeemed handoff code. The proxy
/// uses this to build the redeem response payload and the audit row.
class HandoffCodeRedeemed {
  const HandoffCodeRedeemed({
    required this.code,
    required this.userId,
    required this.operatorId,
    required this.locationId,
    required this.targetPath,
    required this.sourceDeviceFingerprint,
    required this.consumedAt,
  });

  /// The code that was redeemed. Carried through so the audit row's
  /// payload can include the SHA-256 hash (NOT the raw code) for
  /// debugging without leaking material into the audit chain.
  final String code;

  final String userId;
  final String operatorId;
  final String locationId;
  final String targetPath;
  final String? sourceDeviceFingerprint;
  final DateTime consumedAt;
}

/// Snapshot of a handoff code's state without mutating it. Used by
/// the redeem failure path to classify (wrong operator vs. expired
/// vs. already consumed) so the route can return the correct status
/// code (403 vs. 410).
class HandoffCodeState {
  const HandoffCodeState({
    required this.operatorId,
    required this.expiresAt,
    required this.consumedAt,
  });

  final String operatorId;
  final DateTime expiresAt;
  final DateTime? consumedAt;

  bool get isExpired => DateTime.now().toUtc().isAfter(expiresAt);
  bool get isConsumed => consumedAt != null;
}

class HandoffCodesRepository extends OperatorScopedRepository {
  HandoffCodesRepository(super.tenantWrapper);

  /// Server-side TTL contract; the migration's CHECK constraint
  /// rejects any row whose expires_at is more than 65 seconds past
  /// created_at. Application keeps the canonical 60-second value.
  static const Duration kHandoffTtl = Duration(seconds: 60);

  /// Per-user mint cap inside any 1-hour rolling window. Slice doc
  /// promise: "Per-user rate limit 10/hour".
  static const int kRateLimitPerHour = 10;

  /// Inline reaper horizon. Rows older than this are dropped at the
  /// head of every mint transaction so the partial indexes stay
  /// bounded. Picked 1 day to leave a comfortable observability
  /// window — operators investigating a bounce failure can still
  /// inspect a "was-this-recently-redeemed" trail in audit_logs.
  static const Duration kReaperHorizon = Duration(days: 1);

  /// Insert a new code. Returns the freshly minted code string. The
  /// migration enforces the code shape via CHECK constraint, so a
  /// malformed candidate is rejected by Postgres before the row
  /// commits.
  ///
  /// The mint discipline — server-side `gen_random_bytes(16)` —
  /// matches the contract addendum A1 mandate that codes are not
  /// client-supplied. We bind the generated code as a parameter so
  /// the proxy can also stash it into the in-memory idempotency
  /// replay cache without re-querying the row.
  Future<String> mint({
    required String operatorId,
    required String locationId,
    required String userId,
    required String targetPath,
    required String? sourceDeviceFingerprint,
    DateTime Function()? now,
  }) {
    final ctx = TenantContext(
      operatorId: operatorId,
      locationId: locationId,
      userId: userId,
    );
    return withTenant<String>(ctx, (exec) async {
      // Inline reaper — drop rows older than the reaper horizon so
      // the partial indexes (handoff_codes_code_active_idx and
      // handoff_codes_expires_at_active_idx) stay small. Bounded by
      // the per-tenant RLS policy, so this scan never crosses
      // tenant boundaries even though it reads no business state.
      await exec.execute(
        'delete from public.handoff_codes '
        'where operator_id = @operator_id::uuid '
        'and expires_at < @reap_floor::timestamptz',
        parameters: <String, Object?>{
          'operator_id': operatorId,
          'reap_floor': (now ?? DateTime.now)()
              .toUtc()
              .subtract(kReaperHorizon)
              .toIso8601String(),
        },
      );

      final code = _generateOpaqueCode();
      final rows = await exec.query(
        'insert into public.handoff_codes ('
        'code, user_id, operator_id, location_id, target_path, '
        'expires_at, source_device_fingerprint) '
        'values ('
        '@code, @user_id::uuid, @operator_id::uuid, @location_id::uuid, '
        '@target_path, '
        // The migration's CHECK constraint clamps expires_at to
        // created_at + 65 seconds; we pass 60 seconds (the contract).
        "now() + interval '60 seconds', "
        '@source_device_fingerprint) '
        'returning code',
        parameters: <String, Object?>{
          'code': code,
          'user_id': userId,
          'operator_id': operatorId,
          'location_id': locationId,
          'target_path': targetPath,
          'source_device_fingerprint': sourceDeviceFingerprint,
        },
      );
      if (rows.isEmpty) {
        throw StateError(
          'handoff_codes insert returned no rows — RLS policy may '
          'have blocked the row even though SET LOCAL ran',
        );
      }
      final stored = rows.single['code'];
      if (stored is! String || stored.isEmpty) {
        throw StateError(
          'handoff_codes insert returned a malformed code',
        );
      }
      return stored;
    });
  }

  /// Atomic redeem. Returns a [HandoffCodeRedeemed] when the row
  /// transitions from "active" to "consumed"; returns null when the
  /// predicate did not match (expired, already consumed, wrong
  /// operator, or the code does not exist).
  ///
  /// The caller-supplied [callerOperatorId] / [callerLocationId] /
  /// [callerUserId] resolve the JWT-derived caller scope; the SET
  /// LOCAL discipline puts these on the transaction so the per-
  /// tenant RLS policy clamps the UPDATE to the caller's operator.
  /// The WHERE includes `operator_id = @caller_operator_id::uuid`
  /// as a defense-in-depth predicate so a misconfigured RLS posture
  /// would still refuse to consume a row from a different operator
  /// (returns 0 rows instead of leaking).
  Future<HandoffCodeRedeemed?> redeem({
    required String callerOperatorId,
    required String callerLocationId,
    required String callerUserId,
    required String code,
  }) {
    final ctx = TenantContext(
      operatorId: callerOperatorId,
      locationId: callerLocationId,
      userId: callerUserId,
    );
    return withTenant<HandoffCodeRedeemed?>(ctx, (exec) async {
      final rows = await exec.query(
        'update public.handoff_codes '
        'set consumed_at = now() '
        'where code = @code '
        'and operator_id = @operator_id::uuid '
        'and consumed_at is null '
        'and expires_at > now() '
        'returning '
        'code, '
        'user_id::text as user_id, '
        'operator_id::text as operator_id, '
        'location_id::text as location_id, '
        'target_path, '
        'source_device_fingerprint, '
        'consumed_at',
        parameters: <String, Object?>{
          'code': code,
          'operator_id': callerOperatorId,
        },
      );
      if (rows.isEmpty) return null;
      final row = rows.single;
      return HandoffCodeRedeemed(
        code: row['code'] as String,
        userId: row['user_id'] as String,
        operatorId: row['operator_id'] as String,
        locationId: row['location_id'] as String,
        targetPath: row['target_path'] as String,
        sourceDeviceFingerprint: row['source_device_fingerprint'] is String
            ? row['source_device_fingerprint'] as String
            : null,
        consumedAt: _asUtcDateTime(row['consumed_at']),
      );
    });
  }

  /// Reads the current state of a code without mutating it. Returns
  /// null when the code does not exist OR exists in a different
  /// operator (the per-tenant RLS policy filters the read). The
  /// redeem-failure classifier uses this to distinguish "wrong
  /// operator (403)" from "expired or already consumed (410)".
  ///
  /// We run a second narrow lookup through `withSystem` so the
  /// caller can detect the "code exists but belongs to a different
  /// operator" case for the 403 branch. The system path is bounded
  /// to a single SELECT on the primary key — no DML, no broader
  /// reads — and the value is only used to produce a 403 status
  /// code (no row data leaks back to the client).
  Future<HandoffCodeState?> lookupForReplayCheck({
    required String code,
    required String adminReason,
  }) {
    return withSystem<HandoffCodeState?>(
      (exec) async {
        final rows = await exec.query(
          'select '
          'operator_id::text as operator_id, '
          'expires_at, '
          'consumed_at '
          'from public.handoff_codes '
          'where code = @code '
          'limit 1',
          parameters: <String, Object?>{
            'code': code,
          },
        );
        if (rows.isEmpty) return null;
        final row = rows.single;
        return HandoffCodeState(
          operatorId: row['operator_id'] as String,
          expiresAt: _asUtcDateTime(row['expires_at']),
          consumedAt: row['consumed_at'] == null
              ? null
              : _asUtcDateTime(row['consumed_at']),
        );
      },
      reason: adminReason,
    );
  }

  /// Counts how many rows the user has minted in the trailing 1-hour
  /// window. Tenant-scoped — RLS plus the WHERE predicate clamp the
  /// scan to (operator_id, user_id) and the operator-leading
  /// `handoff_codes_operator_user_idx` makes the lookup a single
  /// index range scan.
  Future<int> countRecentForUser({
    required String operatorId,
    required String locationId,
    required String userId,
    DateTime Function()? now,
  }) {
    final ctx = TenantContext(
      operatorId: operatorId,
      locationId: locationId,
      userId: userId,
    );
    return withTenant<int>(ctx, (exec) async {
      final since = (now ?? DateTime.now)()
          .toUtc()
          .subtract(const Duration(hours: 1));
      final rows = await exec.query(
        'select count(*)::int as cnt '
        'from public.handoff_codes '
        'where operator_id = @operator_id::uuid '
        'and user_id = @user_id::uuid '
        'and created_at >= @since::timestamptz',
        parameters: <String, Object?>{
          'operator_id': operatorId,
          'user_id': userId,
          'since': since.toIso8601String(),
        },
      );
      if (rows.isEmpty) return 0;
      final v = rows.single['cnt'];
      return v is int ? v : 0;
    });
  }

  /// SHA-256 hash of [code], hex-encoded. The audit_logs payload
  /// stores this — never the raw code — so the audit chain is not a
  /// token-leak vector even if a future reader gains broad audit_logs
  /// access.
  static String hashCodeForAudit(String code) =>
      sha256.convert(utf8.encode(code)).toString();

  /// Generates a 22-character base64-url body of 16 random bytes
  /// (~128 bits of entropy). Padding stripped, '+' / '/' replaced
  /// with '-' / '_' so the code matches the migration's
  /// `^[A-Za-z0-9_-]+$` shape constraint and is URL-safe in case a
  /// caller needs to pass it as a URL fragment in a non-proxy
  /// context (e.g. the browser landing URL hash, NOT a query
  /// parameter sent to the proxy — addendum A1).
  static String _generateOpaqueCode() {
    final rnd = math.Random.secure();
    final bytes = List<int>.generate(16, (_) => rnd.nextInt(256));
    return base64UrlEncode(bytes).replaceAll('=', '');
  }

  static DateTime _asUtcDateTime(Object? value) {
    if (value is DateTime) return value.toUtc();
    if (value is String) return DateTime.parse(value).toUtc();
    throw StateError('handoff_codes row missing timestamp');
  }
}
