// Phase 8 W2.B - notification preferences proxy routes.
//
// Three operator-scoped per-user routes - the actor's own
// preferences only. Idempotency-Key required on writes following the
// existing per-tenant idempotency pattern in `operator_routes.dart`.
//
//   GET    /v1/operator/notification-preferences
//   PUT    /v1/operator/notification-preferences/:eventKey/:channel
//          ?scope_kind=operator|location&scope_id=<uuid>
//   DELETE /v1/operator/notification-preferences/:eventKey/:channel
//          ?scope_kind=operator|location&scope_id=<uuid>
//
// Auth:
//   * Bearer token resolves to OperatorContext (operatorId required).
//   * Caller is the actor; routes operate on the actor's own row,
//     never another user's. RLS policy on the table enforces this.
//
// Idempotency:
//   * Idempotency-Key required on PUT and DELETE; missing / blank /
//     >200 chars -> 400 idempotency_key_missing /
//     idempotency_key_too_long.
//   * Same key + same body within TTL -> replay (cached response).
//   * Same key + different body -> 409 idempotency_key_conflict.
//
// CLAUDE.md compliance:
//   * Operator-scoped - operator_id resolved from JWT, never from URL.
//   * No client-side UUIDs - id is server-generated by gen_random_uuid().
//   * Plain-English error messages, no engineering jargon.

import 'dart:convert';

import 'package:crypto/crypto.dart';

import 'package:forge_and_flow/domain/models/notification_preference.dart';
import 'package:forge_and_flow/infrastructure/persistence/postgres/repositories/notification_preferences_repository.dart';

/// Route prefix.
const String notificationPreferencesPath =
    '/v1/operator/notification-preferences';
const String notificationPreferencesPrefix =
    '$notificationPreferencesPath/';

/// Channel values admitted by the migration's CHECK constraint.
const Set<String> _kAdmittedChannels = <String>{'push', 'email', 'inbox'};

/// Scope-kind values admitted by the migration's CHECK constraint.
const Set<String> _kAdmittedScopeKinds = <String>{'operator', 'location'};

/// Lightweight rejection envelope, matches `OperatorWriteRejected`.
class NotificationPreferenceRouteRejected implements Exception {
  const NotificationPreferenceRouteRejected({
    required this.code,
    required this.message,
    required this.statusCode,
    this.extras = const <String, Object?>{},
  });

  final String code;
  final String message;
  final int statusCode;
  final Map<String, Object?> extras;
}

/// Locator gateway around [NotificationPreferencesRepository] so the
/// route handler can be tested with a recording fake.
abstract class NotificationPreferencesGateway {
  Future<List<NotificationPreference>> listForUser({
    required String operatorId,
    required String locationId,
    required String userId,
  });

  Future<NotificationPreference> upsert({
    required String operatorId,
    required String locationId,
    required String userId,
    required String eventKey,
    required NotificationChannel channel,
    required NotificationScopeKind scopeKind,
    required String? scopeId,
    required bool enabled,
  });

  Future<bool> delete({
    required String operatorId,
    required String locationId,
    required String userId,
    required String eventKey,
    required NotificationChannel channel,
    required NotificationScopeKind scopeKind,
    required String? scopeId,
  });
}

/// Production gateway backed by the Postgres repository.
class RepositoryNotificationPreferencesGateway
    implements NotificationPreferencesGateway {
  RepositoryNotificationPreferencesGateway({required this.repository});

  final NotificationPreferencesRepository repository;

  @override
  Future<List<NotificationPreference>> listForUser({
    required String operatorId,
    required String locationId,
    required String userId,
  }) =>
      repository.listForUser(
        operatorId: operatorId,
        locationId: locationId,
        userId: userId,
      );

  @override
  Future<NotificationPreference> upsert({
    required String operatorId,
    required String locationId,
    required String userId,
    required String eventKey,
    required NotificationChannel channel,
    required NotificationScopeKind scopeKind,
    required String? scopeId,
    required bool enabled,
  }) =>
      repository.upsert(
        operatorId: operatorId,
        locationId: locationId,
        userId: userId,
        eventKey: eventKey,
        channel: channel,
        scopeKind: scopeKind,
        scopeId: scopeId,
        enabled: enabled,
      );

  @override
  Future<bool> delete({
    required String operatorId,
    required String locationId,
    required String userId,
    required String eventKey,
    required NotificationChannel channel,
    required NotificationScopeKind scopeKind,
    required String? scopeId,
  }) =>
      repository.delete(
        operatorId: operatorId,
        locationId: locationId,
        userId: userId,
        eventKey: eventKey,
        channel: channel,
        scopeKind: scopeKind,
        scopeId: scopeId,
      );
}

/// In-memory replay cache for PUT / DELETE routes. Mirrors
/// `OperatorWriteIdempotencyCache` shape but local to this surface so
/// the existing operator-write cache stays scoped to its routes.
class NotificationPreferencesIdempotencyCache {
  NotificationPreferencesIdempotencyCache({
    this.ttl = const Duration(hours: 1),
    this.maxEntries = 5000,
    DateTime Function()? now,
  }) : _now = now ?? DateTime.now;

  final Duration ttl;
  final int maxEntries;
  final DateTime Function() _now;

  final Map<String, _CacheEntry> _store = <String, _CacheEntry>{};

  Future<({int statusCode, Map<String, Object?> body})> runOrReplay({
    required String operatorId,
    required String userId,
    required String route,
    required String idempotencyKey,
    required String requestBodyHash,
    required Future<({int statusCode, Map<String, Object?> body})> Function()
        compute,
  }) async {
    _gc();
    final key = '$operatorId|$userId|$route|$idempotencyKey';
    final cached = _store[key];
    if (cached != null) {
      if (cached.bodyHash != requestBodyHash) {
        throw const NotificationPreferenceRouteRejected(
          code: 'idempotency_key_conflict',
          message: 'Idempotency-Key was reused with a different body',
          statusCode: 409,
        );
      }
      return (statusCode: cached.statusCode, body: cached.body);
    }
    final result = await compute();
    if (result.statusCode >= 200 &&
        result.statusCode < 500 &&
        result.statusCode != 429) {
      _store[key] = _CacheEntry(
        statusCode: result.statusCode,
        body: result.body,
        bodyHash: requestBodyHash,
        expiresAt: _now().add(ttl),
      );
      _evictOverflow();
    }
    return result;
  }

  void _gc() {
    final cutoff = _now();
    _store.removeWhere((_, entry) => entry.expiresAt.isBefore(cutoff));
  }

  void _evictOverflow() {
    while (_store.length > maxEntries) {
      _store.remove(_store.keys.first);
    }
  }
}

class _CacheEntry {
  _CacheEntry({
    required this.statusCode,
    required this.body,
    required this.bodyHash,
    required this.expiresAt,
  });

  final int statusCode;
  final Map<String, Object?> body;
  final String bodyHash;
  final DateTime expiresAt;
}

/// Stable hash of a request payload (canonical JSON, sorted keys) -
/// matches `hashOperatorRequestBody` shape so retries hash to the
/// same value regardless of map insertion order.
String hashNotificationPreferencesRequest(Map<String, Object?> body) {
  final canonical = _canonicalJson(body);
  return sha256.convert(utf8.encode(canonical)).toString();
}

String _canonicalJson(Object? value) {
  if (value is Map) {
    final keys = value.keys.map((k) => k.toString()).toList()..sort();
    final entries = <String>[
      for (final k in keys) '${jsonEncode(k)}:${_canonicalJson(value[k])}',
    ];
    return '{${entries.join(',')}}';
  }
  if (value is List) {
    return '[${value.map(_canonicalJson).join(',')}]';
  }
  return jsonEncode(value);
}

/// Router. Caller resolves auth + JWT scope, then hands off here.
class NotificationPreferencesRouter {
  NotificationPreferencesRouter({
    required this.gateway,
    NotificationPreferencesIdempotencyCache? idempotencyCache,
  }) : _idempotencyCache =
            idempotencyCache ?? NotificationPreferencesIdempotencyCache();

  final NotificationPreferencesGateway gateway;
  final NotificationPreferencesIdempotencyCache _idempotencyCache;

  /// True when [path] / [method] is one of the three routes.
  static bool matches(String path, String method) {
    if (method == 'GET' && path == notificationPreferencesPath) return true;
    if ((method == 'PUT' || method == 'DELETE') &&
        path.startsWith(notificationPreferencesPrefix)) {
      return true;
    }
    return false;
  }

  /// Handle one request once auth + scope resolution + (for writes)
  /// the Idempotency-Key header have been read by the caller.
  ///
  /// `query` carries the parsed query parameters (`scope_kind`,
  /// `scope_id`).
  Future<({int statusCode, Map<String, Object?> body})> handle({
    required String method,
    required String path,
    required Map<String, String> query,
    required String operatorId,
    required String locationId,
    required String actorUserId,
    String? idempotencyKey,
    Map<String, Object?>? body,
  }) async {
    try {
      if (method == 'GET' && path == notificationPreferencesPath) {
        return _handleList(
          operatorId: operatorId,
          locationId: locationId,
          userId: actorUserId,
        );
      }
      // PUT / DELETE - parse the path suffix.
      if (path.startsWith(notificationPreferencesPrefix)) {
        final suffix = path.substring(notificationPreferencesPrefix.length);
        final parts = suffix.split('/');
        if (parts.length != 2 || parts[0].isEmpty || parts[1].isEmpty) {
          return (
            statusCode: 404,
            body: const <String, Object?>{
              'error': 'not_found',
              'message': 'route not found',
            },
          );
        }
        final eventKey = Uri.decodeComponent(parts[0]);
        final channel = Uri.decodeComponent(parts[1]);
        final scopeKind = query['scope_kind'];
        final scopeId = query['scope_id'];
        if (method == 'PUT') {
          if (idempotencyKey == null) {
            throw const NotificationPreferenceRouteRejected(
              code: 'idempotency_key_missing',
              message: 'Idempotency-Key header is required for PUT',
              statusCode: 400,
            );
          }
          return await _runIdempotent(
            operatorId: operatorId,
            userId: actorUserId,
            route: 'PUT $path?scope_kind=$scopeKind&scope_id=${scopeId ?? ''}',
            idempotencyKey: idempotencyKey,
            body: body ?? const <String, Object?>{},
            compute: () => _handleUpsert(
              operatorId: operatorId,
              locationId: locationId,
              userId: actorUserId,
              eventKey: eventKey,
              channelRaw: channel,
              scopeKindRaw: scopeKind,
              scopeIdRaw: scopeId,
              body: body ?? const <String, Object?>{},
            ),
          );
        }
        if (method == 'DELETE') {
          if (idempotencyKey == null) {
            throw const NotificationPreferenceRouteRejected(
              code: 'idempotency_key_missing',
              message: 'Idempotency-Key header is required for DELETE',
              statusCode: 400,
            );
          }
          return await _runIdempotent(
            operatorId: operatorId,
            userId: actorUserId,
            route:
                'DELETE $path?scope_kind=$scopeKind&scope_id=${scopeId ?? ''}',
            idempotencyKey: idempotencyKey,
            body: const <String, Object?>{},
            compute: () => _handleDelete(
              operatorId: operatorId,
              locationId: locationId,
              userId: actorUserId,
              eventKey: eventKey,
              channelRaw: channel,
              scopeKindRaw: scopeKind,
              scopeIdRaw: scopeId,
            ),
          );
        }
      }
      return (
        statusCode: 404,
        body: const <String, Object?>{
          'error': 'not_found',
          'message': 'route not found',
        },
      );
    } on NotificationPreferenceRouteRejected catch (rejected) {
      return (
        statusCode: rejected.statusCode,
        body: <String, Object?>{
          'error': rejected.code,
          'message': rejected.message,
          ...rejected.extras,
        },
      );
    }
  }

  Future<({int statusCode, Map<String, Object?> body})> _runIdempotent({
    required String operatorId,
    required String userId,
    required String route,
    required String idempotencyKey,
    required Map<String, Object?> body,
    required Future<({int statusCode, Map<String, Object?> body})> Function()
        compute,
  }) {
    final bodyHash = hashNotificationPreferencesRequest(body);
    return _idempotencyCache.runOrReplay(
      operatorId: operatorId,
      userId: userId,
      route: route,
      idempotencyKey: idempotencyKey,
      requestBodyHash: bodyHash,
      compute: compute,
    );
  }

  Future<({int statusCode, Map<String, Object?> body})> _handleList({
    required String operatorId,
    required String locationId,
    required String userId,
  }) async {
    final rows = await gateway.listForUser(
      operatorId: operatorId,
      locationId: locationId,
      userId: userId,
    );
    return (
      statusCode: 200,
      body: <String, Object?>{
        'preferences': <Map<String, Object?>>[
          for (final row in rows) row.toJson(),
        ],
      },
    );
  }

  Future<({int statusCode, Map<String, Object?> body})> _handleUpsert({
    required String operatorId,
    required String locationId,
    required String userId,
    required String eventKey,
    required String channelRaw,
    required String? scopeKindRaw,
    required String? scopeIdRaw,
    required Map<String, Object?> body,
  }) async {
    final channel = _parseChannel(channelRaw);
    final scope = _parseScope(scopeKindRaw, scopeIdRaw);
    final enabled = body['enabled'];
    if (enabled is! bool) {
      return (
        statusCode: 400,
        body: const <String, Object?>{
          'error': 'invalid_body',
          'message': 'request body must include `enabled`: true | false',
        },
      );
    }
    final record = await gateway.upsert(
      operatorId: operatorId,
      locationId: locationId,
      userId: userId,
      eventKey: eventKey,
      channel: channel,
      scopeKind: scope.kind,
      scopeId: scope.id,
      enabled: enabled,
    );
    return (statusCode: 200, body: record.toJson());
  }

  Future<({int statusCode, Map<String, Object?> body})> _handleDelete({
    required String operatorId,
    required String locationId,
    required String userId,
    required String eventKey,
    required String channelRaw,
    required String? scopeKindRaw,
    required String? scopeIdRaw,
  }) async {
    final channel = _parseChannel(channelRaw);
    final scope = _parseScope(scopeKindRaw, scopeIdRaw);
    final removed = await gateway.delete(
      operatorId: operatorId,
      locationId: locationId,
      userId: userId,
      eventKey: eventKey,
      channel: channel,
      scopeKind: scope.kind,
      scopeId: scope.id,
    );
    return (
      statusCode: 200,
      body: <String, Object?>{'removed': removed},
    );
  }

  NotificationChannel _parseChannel(String raw) {
    if (!_kAdmittedChannels.contains(raw)) {
      throw NotificationPreferenceRouteRejected(
        code: 'invalid_channel',
        message: 'channel must be one of ${_kAdmittedChannels.join(' / ')}',
        statusCode: 400,
      );
    }
    return NotificationChannelWire.fromWire(raw);
  }

  ({NotificationScopeKind kind, String? id}) _parseScope(
    String? scopeKindRaw,
    String? scopeIdRaw,
  ) {
    final scopeKindWire = scopeKindRaw ?? 'operator';
    if (!_kAdmittedScopeKinds.contains(scopeKindWire)) {
      throw NotificationPreferenceRouteRejected(
        code: 'invalid_scope_kind',
        message:
            'scope_kind must be one of ${_kAdmittedScopeKinds.join(' / ')}',
        statusCode: 400,
      );
    }
    final scopeKind = NotificationScopeKindWire.fromWire(scopeKindWire);
    if (scopeKind == NotificationScopeKind.operator) {
      // operator-scoped row carries NULL scope_id even if a value was
      // submitted; we ignore the param so the UNIQUE NULLS NOT
      // DISTINCT key still collapses cleanly.
      return (kind: scopeKind, id: null);
    }
    if (scopeIdRaw == null || scopeIdRaw.isEmpty) {
      throw const NotificationPreferenceRouteRejected(
        code: 'invalid_scope_id',
        message: 'scope_id is required when scope_kind is location',
        statusCode: 400,
      );
    }
    return (kind: scopeKind, id: scopeIdRaw);
  }
}
