// Pure Dart admin-visible vendor capability catalog.
//
// Keep this file free of adapter imports. The proxy binary is built
// with `dart compile exe`, and the concrete adapter registries import
// Flutter through some vendor files. Tests compare this catalog with
// those registries so the proxy can stay AOT-buildable without
// drifting from implemented adapter metadata.

import 'package:forge_and_flow/services/integration/integration_adapter_common.dart';

const List<VendorCapabilityProfile> kAdminVisibleVendorCapabilityProfiles =
    <VendorCapabilityProfile>[
      VendorCapabilityProfile(
        vendorId: 'aloha_ncr_voyix',
        displayName: 'Aloha (NCR Voyix)',
        category: IntegrationCategory.pos,
        authMode: VendorAuthMode.oauth,
        grantScope: VendorGrantScope.perLocation,
        webhookSupport: VendorWebhookSupport.autoRegister,
        coversFieldExposed: true,
        lifecycle: VendorLifecycle.documented,
      ),
      VendorCapabilityProfile(
        vendorId: 'clover',
        displayName: 'Clover',
        category: IntegrationCategory.pos,
        authMode: VendorAuthMode.oauth,
        grantScope: VendorGrantScope.perLocation,
        webhookSupport: VendorWebhookSupport.autoRegister,
        coversFieldExposed: false,
        lifecycle: VendorLifecycle.documented,
      ),
      VendorCapabilityProfile(
        vendorId: 'lightspeed_lsk',
        displayName: 'Lightspeed Restaurant K-Series',
        category: IntegrationCategory.pos,
        authMode: VendorAuthMode.oauth,
        grantScope: VendorGrantScope.perLocation,
        webhookSupport: VendorWebhookSupport.autoRegister,
        coversFieldExposed: true,
        lifecycle: VendorLifecycle.documented,
      ),
      VendorCapabilityProfile(
        vendorId: 'oracle_micros_simphony',
        displayName: 'Oracle MICROS Simphony',
        category: IntegrationCategory.pos,
        authMode: VendorAuthMode.oauth,
        grantScope: VendorGrantScope.perLocation,
        webhookSupport: VendorWebhookSupport.pollOnly,
        coversFieldExposed: true,
        lifecycle: VendorLifecycle.documented,
      ),
      VendorCapabilityProfile(
        vendorId: 'revel',
        displayName: 'Revel Systems',
        category: IntegrationCategory.pos,
        authMode: VendorAuthMode.oauth,
        grantScope: VendorGrantScope.perLocation,
        webhookSupport: VendorWebhookSupport.autoRegister,
        coversFieldExposed: true,
        lifecycle: VendorLifecycle.documented,
      ),
      VendorCapabilityProfile(
        vendorId: 'square',
        displayName: 'Square',
        category: IntegrationCategory.pos,
        authMode: VendorAuthMode.oauth,
        grantScope: VendorGrantScope.operatorWide,
        webhookSupport: VendorWebhookSupport.autoRegister,
        coversFieldExposed: false,
        lifecycle: VendorLifecycle.documented,
      ),
      VendorCapabilityProfile(
        vendorId: 'toast',
        displayName: 'Toast',
        category: IntegrationCategory.pos,
        authMode: VendorAuthMode.oauth,
        grantScope: VendorGrantScope.perLocation,
        webhookSupport: VendorWebhookSupport.autoRegister,
        coversFieldExposed: true,
        lifecycle: VendorLifecycle.documented,
      ),
      VendorCapabilityProfile(
        vendorId: 'libro',
        displayName: 'Libro Reserve',
        category: IntegrationCategory.reservation,
        authMode: VendorAuthMode.oauth,
        grantScope: VendorGrantScope.perLocation,
        webhookSupport: VendorWebhookSupport.autoRegister,
        coversFieldExposed: false,
        lifecycle: VendorLifecycle.documented,
      ),
      VendorCapabilityProfile(
        vendorId: 'opentable',
        displayName: 'OpenTable',
        category: IntegrationCategory.reservation,
        authMode: VendorAuthMode.oauth,
        grantScope: VendorGrantScope.perLocation,
        webhookSupport: VendorWebhookSupport.autoRegister,
        coversFieldExposed: false,
        lifecycle: VendorLifecycle.documented,
      ),
      VendorCapabilityProfile(
        vendorId: 'sevenrooms',
        displayName: 'SevenRooms',
        category: IntegrationCategory.reservation,
        authMode: VendorAuthMode.oauthOrKeyPaste,
        grantScope: VendorGrantScope.perLocation,
        webhookSupport: VendorWebhookSupport.manualPaste,
        coversFieldExposed: false,
        lifecycle: VendorLifecycle.documented,
      ),
      VendorCapabilityProfile(
        vendorId: 'tock',
        displayName: 'Tock',
        category: IntegrationCategory.reservation,
        authMode: VendorAuthMode.keyPaste,
        grantScope: VendorGrantScope.perLocation,
        webhookSupport: VendorWebhookSupport.manualPaste,
        coversFieldExposed: false,
        lifecycle: VendorLifecycle.documented,
      ),
      VendorCapabilityProfile(
        vendorId: 'adp',
        displayName: 'ADP Workforce Now / Workforce Manager',
        category: IntegrationCategory.labor,
        authMode: VendorAuthMode.oauth,
        grantScope: VendorGrantScope.operatorWide,
        webhookSupport: VendorWebhookSupport.autoRegister,
        coversFieldExposed: false,
        lifecycle: VendorLifecycle.documented,
        modules: <String>['workforce_now', 'workforce_manager', 'run'],
      ),
      VendorCapabilityProfile(
        vendorId: 'agendrix',
        displayName: 'Agendrix',
        category: IntegrationCategory.labor,
        authMode: VendorAuthMode.oauth,
        grantScope: VendorGrantScope.operatorWide,
        webhookSupport: VendorWebhookSupport.pollOnly,
        coversFieldExposed: false,
        lifecycle: VendorLifecycle.documented,
      ),
      VendorCapabilityProfile(
        vendorId: 'humanity',
        displayName: 'Humanity',
        category: IntegrationCategory.labor,
        authMode: VendorAuthMode.keyPaste,
        grantScope: VendorGrantScope.operatorWide,
        webhookSupport: VendorWebhookSupport.pollOnly,
        coversFieldExposed: false,
        lifecycle: VendorLifecycle.documented,
      ),
      VendorCapabilityProfile(
        vendorId: 'push_operations',
        displayName: 'Push Operations',
        category: IntegrationCategory.labor,
        authMode: VendorAuthMode.keyPaste,
        grantScope: VendorGrantScope.operatorWide,
        webhookSupport: VendorWebhookSupport.pollOnly,
        coversFieldExposed: false,
        lifecycle: VendorLifecycle.documented,
      ),
      VendorCapabilityProfile(
        vendorId: 'quickbooks_time',
        displayName: 'QuickBooks Time',
        category: IntegrationCategory.labor,
        authMode: VendorAuthMode.oauth,
        grantScope: VendorGrantScope.operatorWide,
        webhookSupport: VendorWebhookSupport.pollOnly,
        coversFieldExposed: false,
        lifecycle: VendorLifecycle.documented,
        modules: <String>['time'],
      ),
      VendorCapabilityProfile(
        vendorId: 'seven_shifts',
        displayName: '7shifts',
        category: IntegrationCategory.labor,
        authMode: VendorAuthMode.oauth,
        grantScope: VendorGrantScope.operatorWide,
        webhookSupport: VendorWebhookSupport.autoRegister,
        coversFieldExposed: false,
        lifecycle: VendorLifecycle.documented,
      ),
    ];
