// Phase 8 W5.A.1 — wage role rows proxy write routes.
//
// Two operator-scoped routes — the operator's own wage mix only.
// Idempotency-Key required on both. Pattern mirrors the W2.B
// notification preferences seam (in-memory replay cache, plain-English
// rejection envelope, JWT-resolved operator/location, no client-side
// UUID generation).
//
//   POST   /v1/operator/wage-role-rows
//   DELETE /v1/operator/wage-role-rows/:wage_role_row_id
//
// Auth:
//   * Bearer token resolves to OperatorContext (operatorId required).
//   * Caller must hold an operator-write role (`operator_owner`);
//     the dispatcher in advisor_proxy.dart checks
//     `kOperatorWriteRoles` before delegating here.
//   * RLS on the table is the backup defense; the repository pattern
//     SET LOCALs the operator + location every transaction.
//
// Idempotency:
//   * Idempotency-Key required on POST and DELETE; missing / blank /
//     >200 chars → 400 idempotency_key_missing /
//     idempotency_key_too_long.
//   * Same key + same body within TTL → replay (cached response).
//   * Same key + different body → 409 idempotency_key_conflict.
//
// Audit:
//   * On every successful write the router fires a single audit row
//     through [WageRoleRowsAuditSink]. Production wires
//     [ProductionWageRoleRowsAuditSink] which lands one
//     `public.audit_logs` row per write (hash-chained, operator-scoped,
//     wrapped in the tenant tx). A replayed idempotent request does NOT
//     fire a new audit row because the router replays the cached
//     response without re-invoking the gateway.
//
// CLAUDE.md compliance:
//   * Operator-scoped — operator_id resolved from JWT, never from URL.
//   * No client-side UUIDs — id is server-generated by gen_random_uuid().
//   * Plain-English error messages, no engineering jargon.
//   * Permissions + audit (Hard Contract 7) — every write is permission
//     checked, idempotency keyed, and audit logged.

import 'dart:convert';

import 'package:crypto/crypto.dart';

import 'package:forge_and_flow/domain/models/wage_role_row_record.dart';
import 'package:forge_and_flow/infrastructure/persistence/postgres/repositories/wage_role_rows_repository.dart';

/// Route prefix.
const String wageRoleRowsPath = '/v1/operator/wage-role-rows';
const String wageRoleRowsPrefix = '$wageRoleRowsPath/';

/// Labor-bucket values admitted by the migration's CHECK constraint.
const Set<String> _kAdmittedLaborBuckets = <String>{'foh', 'boh', 'manager'};

/// Source values admitted by the migration's CHECK constraint.
const Set<String> _kAdmittedSources = <String>{
  'operator_manual',
  'vendor_per_position',
  'admin_seed',
  'migration_seed',
};

/// Strict 8-4-4-4-12 lowercase UUID format. The repository's
/// TenantContext also validates, but failing earlier in the route
/// keeps the 400 envelope consistent with the rest of the surface.
final RegExp _kUuidPattern = RegExp(
  r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$',
);

/// Lightweight rejection envelope — same shape as
/// `OperatorWriteRejected` / `NotificationPreferenceRouteRejected`.
class WageRoleRowsRouteRejected implements Exception {
  const WageRoleRowsRouteRejected({
    required this.code,
    required this.message,
    required this.statusCode,
    this.extras = const <String, Object?>{},
  });

  final String code;
  final String message;
  final int statusCode;
  final Map<String, Object?> extras;
}

/// Locator gateway around [WageRoleRowsRepository] so the route
/// handler can be tested with a recording fake.
abstract class WageRoleRowsGateway {
  Future<WageRoleRowRecord> upsert({
    required String operatorId,
    required String locationId,
    required String restaurantId,
    required String roleName,
    required String laborBucket,
    required double hourlyRate,
    required double weightedHours,
    String? jobCode,
    String? vendorId,
    String? vendorRoleId,
    WageRoleRowSource source,
    bool isActive,
    Map<String, Object?> metadata,
    String? actorUserId,
  });

  Future<bool> softDelete({
    required String operatorId,
    required String locationId,
    required String wageRoleRowId,
    String? actorUserId,
  });
}

/// Production gateway backed by the Postgres repository.
class RepositoryWageRoleRowsGateway implements WageRoleRowsGateway {
  RepositoryWageRoleRowsGateway({required this.repository});

  final WageRoleRowsRepository repository;

  @override
  Future<WageRoleRowRecord> upsert({
    required String operatorId,
    required String locationId,
    required String restaurantId,
    required String roleName,
    required String laborBucket,
    required double hourlyRate,
    required double weightedHours,
    String? jobCode,
    String? vendorId,
    String? vendorRoleId,
    WageRoleRowSource source = WageRoleRowSource.operatorManual,
    bool isActive = true,
    Map<String, Object?> metadata = const <String, Object?>{},
    String? actorUserId,
  }) => repository.upsert(
    operatorId: operatorId,
    locationId: locationId,
    restaurantId: restaurantId,
    roleName: roleName,
    laborBucket: laborBucket,
    hourlyRate: hourlyRate,
    weightedHours: weightedHours,
    jobCode: jobCode,
    vendorId: vendorId,
    vendorRoleId: vendorRoleId,
    source: source,
    isActive: isActive,
    metadata: metadata,
    actorUserId: actorUserId,
  );

  @override
  Future<bool> softDelete({
    required String operatorId,
    required String locationId,
    required String wageRoleRowId,
    String? actorUserId,
  }) => repository.softDelete(
    operatorId: operatorId,
    locationId: locationId,
    wageRoleRowId: wageRoleRowId,
    actorUserId: actorUserId,
  );
}

/// In-memory replay cache for POST / DELETE routes. Mirrors
/// `NotificationPreferencesIdempotencyCache` shape but local to this
/// surface so the existing operator-write cache stays scoped to its
/// routes.
class WageRoleRowsIdempotencyCache {
  WageRoleRowsIdempotencyCache({
    this.ttl = const Duration(hours: 1),
    this.maxEntries = 5000,
    DateTime Function()? now,
  }) : _now = now ?? DateTime.now;

  final Duration ttl;
  final int maxEntries;
  final DateTime Function() _now;

  final Map<String, _CacheEntry> _store = <String, _CacheEntry>{};

  Future<({int statusCode, Map<String, Object?> body})> runOrReplay({
    required String operatorId,
    required String locationId,
    required String route,
    required String idempotencyKey,
    required String requestBodyHash,
    required Future<({int statusCode, Map<String, Object?> body})> Function()
    compute,
  }) async {
    _gc();
    final key = '$operatorId|$locationId|$route|$idempotencyKey';
    final cached = _store[key];
    if (cached != null) {
      if (cached.bodyHash != requestBodyHash) {
        throw const WageRoleRowsRouteRejected(
          code: 'idempotency_key_conflict',
          message: 'Idempotency-Key was reused with a different body',
          statusCode: 409,
        );
      }
      return (statusCode: cached.statusCode, body: cached.body);
    }
    final result = await compute();
    if (result.statusCode >= 200 &&
        result.statusCode < 500 &&
        result.statusCode != 429) {
      _store[key] = _CacheEntry(
        statusCode: result.statusCode,
        body: result.body,
        bodyHash: requestBodyHash,
        expiresAt: _now().add(ttl),
      );
      _evictOverflow();
    }
    return result;
  }

  void _gc() {
    final cutoff = _now();
    _store.removeWhere((_, entry) => entry.expiresAt.isBefore(cutoff));
  }

  void _evictOverflow() {
    while (_store.length > maxEntries) {
      _store.remove(_store.keys.first);
    }
  }
}

class _CacheEntry {
  _CacheEntry({
    required this.statusCode,
    required this.body,
    required this.bodyHash,
    required this.expiresAt,
  });

  final int statusCode;
  final Map<String, Object?> body;
  final String bodyHash;
  final DateTime expiresAt;
}

/// Stable hash of a request payload (canonical JSON, sorted keys) —
/// matches `hashOperatorRequestBody` shape so retries hash to the
/// same value regardless of map insertion order.
String hashWageRoleRowsRequest(Map<String, Object?> body) {
  final canonical = _canonicalJson(body);
  return sha256.convert(utf8.encode(canonical)).toString();
}

String _canonicalJson(Object? value) {
  if (value is Map) {
    final keys = value.keys.map((k) => k.toString()).toList()..sort();
    final entries = <String>[
      for (final k in keys) '${jsonEncode(k)}:${_canonicalJson(value[k])}',
    ];
    return '{${entries.join(',')}}';
  }
  if (value is List) {
    return '[${value.map(_canonicalJson).join(',')}]';
  }
  return jsonEncode(value);
}

/// Audit sink fired once per successful wage-role-rows write. Mirrors
/// the [OperatorWriteAuditSink] shape so production can reuse the same
/// hash-chained `public.audit_logs` writer wired for operator account /
/// business timing writes. The router invokes this AFTER the gateway
/// returns a successful result; replayed idempotent requests do NOT
/// re-fire the sink (the cache short-circuits before `compute` runs).
///
/// Implementations MUST swallow audit failures rather than rethrowing —
/// the business write has already committed by the time this is called
/// and a downstream observability failure must not cause the proxy to
/// return a 5xx for a request whose actual side-effect succeeded.
abstract class WageRoleRowsAuditSink {
  Future<void> recordUpsert({
    required String operatorId,
    required String locationId,
    required String actorUserId,
    required String actorKind,
    required String wageRoleRowId,
    required String restaurantId,
    required String roleName,
    required String laborBucket,
    required double hourlyRate,
    required double weightedHours,
    required String source,
    required DateTime occurredAt,
  });

  Future<void> recordSoftDelete({
    required String operatorId,
    required String locationId,
    required String actorUserId,
    required String actorKind,
    required String wageRoleRowId,
    required bool removed,
    required DateTime occurredAt,
  });
}

/// No-op default. Tests that do not care about audit-log writes leave
/// this in place; production wires [ProductionWageRoleRowsAuditSink]
/// (in `proxy_bootstrap.dart`) so the audit row lands.
class NoopWageRoleRowsAuditSink implements WageRoleRowsAuditSink {
  const NoopWageRoleRowsAuditSink();

  @override
  Future<void> recordUpsert({
    required String operatorId,
    required String locationId,
    required String actorUserId,
    required String actorKind,
    required String wageRoleRowId,
    required String restaurantId,
    required String roleName,
    required String laborBucket,
    required double hourlyRate,
    required double weightedHours,
    required String source,
    required DateTime occurredAt,
  }) async {}

  @override
  Future<void> recordSoftDelete({
    required String operatorId,
    required String locationId,
    required String actorUserId,
    required String actorKind,
    required String wageRoleRowId,
    required bool removed,
    required DateTime occurredAt,
  }) async {}
}

/// Router. Caller resolves auth + JWT scope, then hands off here.
class WageRoleRowsRouter {
  WageRoleRowsRouter({
    required this.gateway,
    WageRoleRowsIdempotencyCache? idempotencyCache,
    WageRoleRowsAuditSink? auditSink,
    DateTime Function()? now,
  }) : _idempotencyCache = idempotencyCache ?? WageRoleRowsIdempotencyCache(),
       _auditSink = auditSink ?? const NoopWageRoleRowsAuditSink(),
       _now = now ?? DateTime.now;

  final WageRoleRowsGateway gateway;
  final WageRoleRowsIdempotencyCache _idempotencyCache;
  final WageRoleRowsAuditSink _auditSink;
  final DateTime Function() _now;

  /// True when [path] / [method] is one of the two routes.
  static bool matches(String path, String method) {
    if (method == 'POST' && path == wageRoleRowsPath) return true;
    if (method == 'DELETE' && path.startsWith(wageRoleRowsPrefix)) return true;
    return false;
  }

  /// Handle one request once auth + scope resolution + the
  /// Idempotency-Key header have been read by the caller.
  ///
  /// [actorKind] feeds the audit-log row (`'user'` for end-users,
  /// `'service'` for service-principal-issued JWTs); the dispatcher in
  /// `advisor_proxy.dart` reads this from the resolved JWT scope.
  Future<({int statusCode, Map<String, Object?> body})> handle({
    required String method,
    required String path,
    required String operatorId,
    required String locationId,
    required String? actorUserId,
    required String idempotencyKey,
    String actorKind = 'user',
    Map<String, Object?>? body,
  }) async {
    try {
      if (method == 'POST' && path == wageRoleRowsPath) {
        return await _runIdempotent(
          operatorId: operatorId,
          locationId: locationId,
          route: 'POST $path',
          idempotencyKey: idempotencyKey,
          body: body ?? const <String, Object?>{},
          compute: () => _handleUpsert(
            operatorId: operatorId,
            locationId: locationId,
            actorUserId: actorUserId,
            actorKind: actorKind,
            body: body ?? const <String, Object?>{},
          ),
        );
      }
      if (method == 'DELETE' && path.startsWith(wageRoleRowsPrefix)) {
        final suffix = path.substring(wageRoleRowsPrefix.length);
        if (suffix.isEmpty || suffix.contains('/')) {
          return (
            statusCode: 404,
            body: const <String, Object?>{
              'error': 'not_found',
              'message': 'route not found',
            },
          );
        }
        final wageRoleRowId = Uri.decodeComponent(suffix).toLowerCase();
        if (!_kUuidPattern.hasMatch(wageRoleRowId)) {
          throw const WageRoleRowsRouteRejected(
            code: 'invalid_wage_role_row_id',
            message: 'wage_role_row_id must be a UUID',
            statusCode: 400,
          );
        }
        return await _runIdempotent(
          operatorId: operatorId,
          locationId: locationId,
          route: 'DELETE $path',
          idempotencyKey: idempotencyKey,
          body: const <String, Object?>{},
          compute: () => _handleSoftDelete(
            operatorId: operatorId,
            locationId: locationId,
            wageRoleRowId: wageRoleRowId,
            actorUserId: actorUserId,
            actorKind: actorKind,
          ),
        );
      }
      return (
        statusCode: 404,
        body: const <String, Object?>{
          'error': 'not_found',
          'message': 'route not found',
        },
      );
    } on WageRoleRowsRouteRejected catch (rejected) {
      return (
        statusCode: rejected.statusCode,
        body: <String, Object?>{
          'error': rejected.code,
          'message': rejected.message,
          ...rejected.extras,
        },
      );
    }
  }

  Future<({int statusCode, Map<String, Object?> body})> _runIdempotent({
    required String operatorId,
    required String locationId,
    required String route,
    required String idempotencyKey,
    required Map<String, Object?> body,
    required Future<({int statusCode, Map<String, Object?> body})> Function()
    compute,
  }) {
    final bodyHash = hashWageRoleRowsRequest(body);
    return _idempotencyCache.runOrReplay(
      operatorId: operatorId,
      locationId: locationId,
      route: route,
      idempotencyKey: idempotencyKey,
      requestBodyHash: bodyHash,
      compute: compute,
    );
  }

  Future<({int statusCode, Map<String, Object?> body})> _handleUpsert({
    required String operatorId,
    required String locationId,
    required String? actorUserId,
    required String actorKind,
    required Map<String, Object?> body,
  }) async {
    final restaurantId = _requireString(body, 'restaurant_id', maxLength: 128);
    final roleName = _requireString(body, 'role_name', maxLength: 128);
    if (roleName != roleName.trim()) {
      throw const WageRoleRowsRouteRejected(
        code: 'invalid_role_name',
        message: 'role_name must not have leading or trailing whitespace',
        statusCode: 400,
      );
    }
    final laborBucket = _requireString(body, 'labor_bucket', maxLength: 16);
    if (!_kAdmittedLaborBuckets.contains(laborBucket)) {
      throw WageRoleRowsRouteRejected(
        code: 'invalid_labor_bucket',
        message:
            'labor_bucket must be one of ${_kAdmittedLaborBuckets.join(' / ')}',
        statusCode: 400,
      );
    }
    final hourlyRate = _requireRate(body, 'hourly_rate');
    final weightedHours = _requireRate(body, 'weighted_hours');

    final jobCode = _optionalString(body, 'job_code', maxLength: 128);
    final vendorId = _optionalString(body, 'vendor_id', maxLength: 64);
    final vendorRoleId = _optionalString(
      body,
      'vendor_role_id',
      maxLength: 128,
    );

    final sourceWire = body['source'];
    WageRoleRowSource source = WageRoleRowSource.operatorManual;
    if (sourceWire != null) {
      if (sourceWire is! String || !_kAdmittedSources.contains(sourceWire)) {
        throw WageRoleRowsRouteRejected(
          code: 'invalid_source',
          message: 'source must be one of ${_kAdmittedSources.join(' / ')}',
          statusCode: 400,
        );
      }
      source = WageRoleRowSourceWire.fromWire(sourceWire);
    }

    final metadataRaw = body['metadata'];
    Map<String, Object?> metadata = const <String, Object?>{};
    if (metadataRaw != null) {
      if (metadataRaw is! Map) {
        throw const WageRoleRowsRouteRejected(
          code: 'invalid_metadata',
          message: 'metadata must be a JSON object',
          statusCode: 400,
        );
      }
      metadata = Map<String, Object?>.from(metadataRaw);
    }

    final record = await gateway.upsert(
      operatorId: operatorId,
      locationId: locationId,
      restaurantId: restaurantId,
      roleName: roleName,
      laborBucket: laborBucket,
      hourlyRate: hourlyRate,
      weightedHours: weightedHours,
      jobCode: jobCode,
      vendorId: vendorId,
      vendorRoleId: vendorRoleId,
      source: source,
      metadata: metadata,
      actorUserId: actorUserId,
    );
    // Hash-chained audit log (Hard Contract 7). The sink swallows
    // failures so a downstream observability outage cannot 5xx a
    // request whose business write already committed.
    await _auditSink.recordUpsert(
      operatorId: operatorId,
      locationId: locationId,
      actorUserId: actorUserId ?? '',
      actorKind: actorKind,
      wageRoleRowId: record.wageRoleRowId,
      restaurantId: record.restaurantId,
      roleName: record.roleName,
      laborBucket: record.laborBucket,
      hourlyRate: record.hourlyRate,
      weightedHours: record.weightedHours,
      source: record.source.wire,
      occurredAt: _now().toUtc(),
    );
    return (statusCode: 200, body: record.toJson());
  }

  Future<({int statusCode, Map<String, Object?> body})> _handleSoftDelete({
    required String operatorId,
    required String locationId,
    required String wageRoleRowId,
    required String? actorUserId,
    required String actorKind,
  }) async {
    final removed = await gateway.softDelete(
      operatorId: operatorId,
      locationId: locationId,
      wageRoleRowId: wageRoleRowId,
      actorUserId: actorUserId,
    );
    // Hash-chained audit log even when the row was already inactive
    // (`removed = false`), so a delete attempt is always recorded.
    await _auditSink.recordSoftDelete(
      operatorId: operatorId,
      locationId: locationId,
      actorUserId: actorUserId ?? '',
      actorKind: actorKind,
      wageRoleRowId: wageRoleRowId,
      removed: removed,
      occurredAt: _now().toUtc(),
    );
    return (
      statusCode: 200,
      body: <String, Object?>{
        'wage_role_row_id': wageRoleRowId,
        'removed': removed,
      },
    );
  }

  /// Read a required string field from [body], rejecting missing /
  /// blank / oversized values with a typed 400.
  String _requireString(
    Map<String, Object?> body,
    String field, {
    required int maxLength,
  }) {
    final raw = body[field];
    if (raw is! String) {
      throw WageRoleRowsRouteRejected(
        code: 'missing_$field',
        message: '$field is required',
        statusCode: 400,
      );
    }
    final value = raw.trim();
    if (value.isEmpty) {
      throw WageRoleRowsRouteRejected(
        code: 'invalid_$field',
        message: '$field must not be blank',
        statusCode: 400,
      );
    }
    if (value.length > maxLength) {
      throw WageRoleRowsRouteRejected(
        code: 'invalid_$field',
        message: '$field must be $maxLength characters or fewer',
        statusCode: 400,
      );
    }
    return value;
  }

  /// Read an optional string field from [body]; null / absent / blank
  /// → null. Oversized values throw.
  String? _optionalString(
    Map<String, Object?> body,
    String field, {
    required int maxLength,
  }) {
    final raw = body[field];
    if (raw == null) return null;
    if (raw is! String) {
      throw WageRoleRowsRouteRejected(
        code: 'invalid_$field',
        message: '$field must be a string when present',
        statusCode: 400,
      );
    }
    final value = raw.trim();
    if (value.isEmpty) return null;
    if (value.length > maxLength) {
      throw WageRoleRowsRouteRejected(
        code: 'invalid_$field',
        message: '$field must be $maxLength characters or fewer',
        statusCode: 400,
      );
    }
    return value;
  }

  /// Read a numeric rate field (hourly_rate, weighted_hours) and
  /// reject negative / out-of-range values.
  double _requireRate(Map<String, Object?> body, String field) {
    final raw = body[field];
    double? value;
    if (raw is num) {
      value = raw.toDouble();
    } else if (raw is String) {
      value = double.tryParse(raw);
    }
    if (value == null) {
      throw WageRoleRowsRouteRejected(
        code: 'missing_$field',
        message: '$field is required and must be numeric',
        statusCode: 400,
      );
    }
    if (value.isNaN || value.isInfinite) {
      throw WageRoleRowsRouteRejected(
        code: 'invalid_$field',
        message: '$field must be a finite number',
        statusCode: 400,
      );
    }
    if (value < 0 || value > 10000) {
      throw WageRoleRowsRouteRejected(
        code: 'invalid_$field',
        message: '$field must be between 0 and 10000',
        statusCode: 400,
      );
    }
    return value;
  }
}
