// Phase 9 live-closeout B11 - FirebaseMfaClient adapter seam.
//
// Production [MfaEnrollmentService] talks to Firebase Identity
// Platform's MultiFactor API through this adapter rather than
// importing `firebase_auth` directly. Same shape as the B4
// `FirebaseAuthClient` seam — the SDK adapter that imports
// `firebase_auth` lives in a single sibling file and is gated
// behind the iOS/Android wiring (B7).
//
// Hard rules:
//
//   * No file outside `lib/services/mfa/firebase_mfa_client_*.dart`
//     may import the real `package:firebase_auth/firebase_auth.dart`
//     for MFA paths.
//   * The default binding is [ScaffoldFailingFirebaseMfaClient] so
//     a misconfigured deploy surfaces a "no Firebase MFA backend
//     wired" error rather than silently allowing.
//   * TOTP secrets (and the otpauth:// URL that contains them) NEVER
//     appear in `toString()`, debug prints, or error messages from
//     this layer — they leak the MFA factor itself.

/// Begin-enrollment payload returned by Firebase. The application
/// service composes this with the F&F recovery-code bundle into the
/// higher-level [TotpEnrollmentSetup] the UI renders.
class FirebaseMfaTotpBeginPayload {
  const FirebaseMfaTotpBeginPayload({
    required this.factorId,
    required this.secretBase32,
    required this.otpAuthUrl,
  });

  /// Firebase MultiFactor session-scoped factor id (NOT the
  /// `mfa_factors.factor_id` UUID — that is generated by the proxy
  /// when the row is inserted).
  final String factorId;

  /// Base32-encoded TOTP secret. Echoed to the user once as a
  /// fallback for QR scanning. Sensitive — never logged.
  final String secretBase32;

  /// `otpauth://` URL the UI renders as a QR code. Embeds the secret;
  /// sensitive — never logged.
  final String otpAuthUrl;
}

/// Outcome of [FirebaseMfaClient.confirmTotpEnrollment].
sealed class FirebaseMfaConfirmOutcome {
  const FirebaseMfaConfirmOutcome();
}

/// Confirmation succeeded. [factorMetadata] is whatever JSON the
/// proxy will persist on the `mfa_factors.factor_metadata` column
/// (e.g. `{"firebase_factor_uid": "abc", "issuer": "Forge & Flow"}`).
class FirebaseMfaConfirmSucceeded extends FirebaseMfaConfirmOutcome {
  const FirebaseMfaConfirmSucceeded({
    required this.factorMetadata,
  });

  final Map<String, Object?> factorMetadata;
}

/// Confirmation failed (wrong OTP, expired session, etc.). [code] is
/// the stable machine-readable code the UI maps to copy. [message]
/// MUST NOT echo the OTP or the secret.
class FirebaseMfaConfirmFailed extends FirebaseMfaConfirmOutcome {
  const FirebaseMfaConfirmFailed({required this.code, required this.message});

  final String code;
  final String message;
}

/// What the production [MfaEnrollmentService] needs from a Firebase
/// Auth MultiFactor SDK. Production wires a thin adapter around
/// `MultiFactor.beginEnrollment` + `TotpMultiFactorGenerator`. Tests
/// inject fakes that return canned payloads.
abstract class FirebaseMfaClient {
  /// Begins TOTP enrollment for [userId]. Returns the secret + the
  /// otpauth URL the UI renders as a QR.
  Future<FirebaseMfaTotpBeginPayload> beginTotpEnrollment({
    required String userId,
    required String userEmail,
    required String issuerName,
  });

  /// Confirms enrollment by exchanging the first OTP from the user's
  /// authenticator app for a permanent enrolled factor.
  Future<FirebaseMfaConfirmOutcome> confirmTotpEnrollment({
    required String factorId,
    required String oneTimeCode,
  });

  /// Removes a previously enrolled factor (Firebase-side). The
  /// proxy then writes `mfa_factors.revoked_at` for the local row.
  /// Used by the 24-hour-delayed MFA removal flow (`MfaRemovalService`).
  Future<void> unenrollFactor({
    required String userId,
    required String factorId,
  });
}

/// Hard-fail-closed default. Every method throws so a production
/// deploy that wires the production [MfaEnrollmentService] but
/// forgets the real SDK adapter surfaces a clear "no Firebase MFA
/// backend wired" error rather than silently rejecting.
class ScaffoldFailingFirebaseMfaClient implements FirebaseMfaClient {
  const ScaffoldFailingFirebaseMfaClient();

  @override
  Future<FirebaseMfaTotpBeginPayload> beginTotpEnrollment({
    required String userId,
    required String userEmail,
    required String issuerName,
  }) async {
    throw StateError(_message);
  }

  @override
  Future<FirebaseMfaConfirmOutcome> confirmTotpEnrollment({
    required String factorId,
    required String oneTimeCode,
  }) async {
    throw StateError(_message);
  }

  @override
  Future<void> unenrollFactor({
    required String userId,
    required String factorId,
  }) async {
    throw StateError(_message);
  }

  static const String _message =
      'B11 scaffold: real FirebaseMfaClient is not wired — bind the '
      '`firebase_auth` MultiFactor adapter (TotpMultiFactorGenerator, '
      'MultiFactor.beginEnrollment) in the proxy bootstrap before '
      'exposing the MFA enrollment surface.';
}
