// GENERATED by tool-side authoring, then verified against the live card
// bodies: every phrase below is a unique, whole-word, non-overlapping
// substring of THAT card's body. A phrase that does not match would simply
// fail to highlight, silently, so the check is not optional.
//
// Why per card: the old per-manual term lists were shared by every card in a
// manual, so which words lit up was an accident of word order rather than
// what the card taught. The operator's bar is that scanning only the
// highlights should still convey the card's information.
//
// A card with no entry here falls back to its manual's list, so a partial
// roll-out never leaves a card unhighlighted.


const Map<String, List<String>> kBarrioCardKeysTrainingTableManicuring =
    <String, List<String>>{
  'training_table_manicuring_c0_u0': <String>[
    'reflection of the establishment\'s commitment to excellence',
    'involves the general cleaning and upkeep of the dining table',
    'goes a step further by silently and discreetly removing non-essential items',
    'pristine and uncluttered environment',
    'instead of being distracted by the unnecessary items',
  ],
  'training_table_manicuring_c1_u0': <String>[
    'streamlines the process of clearing and resetting for the next guests',
    'clearing plates, removing empty glassware, and ensuring the table is reset for each course',
    'delicate balance between guest comfort and attentive service',
    'staff skillfully operate in the background',
    'cluttered with unnecessary glassware and used plates',
    'making guests feel rushed rather than relaxed',
  ],
  'training_table_manicuring_c2_u0': <String>[
    'execute table service seamlessly and with minimal disruption to guests',
    'adhere to fundamental principles',
    'significantly elevate the overall guest experience',
    'transforming a meal into a memorable occasion',
  ],
  'training_table_manicuring_c2_u1': <String>[
    'promptly removing empty plates, used napkins, and dirty cutlery',
    'preventing clutter and allowing for a seamless flow',
    'plates should only be cleared when every guest at the table has completed their meal',
    'unless a specific request for removal has been made',
  ],
  'training_table_manicuring_c2_u2': <String>[
    'take the empty glass with you when presenting a fresh drink',
    'Utilizing a tray becomes invaluable',
    'clear away empties while seamlessly serving refills',
    'monitoring drink levels and offering refills, rather than merely responding to requests',
    'refilling water immediately when it runs low',
  ],
  'training_table_manicuring_c2_u3': <String>[
    'salt and pepper shakers and sugar caddies',
    'clean, adequately filled, and neatly positioned for easy access',
    'promptly removed once they are empty or are no longer needed',
    'preventing clutter on the table',
    'commitment to high standards of service',
  ],
  'training_table_manicuring_c2_u4': <String>[
    'may seem like a harmless time-saving technique',
    'create an impression of haste that can make guests feel rushed or uncomfortable',
    'compromising both the visual appeal and sanitation',
    'remnants of food, condiments, and oil can end up on the bottoms of plates',
    'expensive, handcrafted, and challenging to replace',
    'protects valuable tableware',
  ],
  'training_table_manicuring_c2_u5': <String>[
    'condensation from glassware, potential spills, and any debris',
    'immediately wiped from the table using a clean cloth',
    'ensuring the area is dry',
    'prevent guest discomfort and minimize any hazards',
  ],
  'training_table_manicuring_c2_u6': <String>[
    'consistent layout standard for tables is essential',
    'Uniformity strengthens the aesthetics',
    'chairs are neatly tucked in reinforces this cohesive look',
    'immediately perceive the level of care and attention',
    'speaks volumes about the establishment\'s commitment to quality',
  ],
  'training_table_manicuring_c2_u7': <String>[
    'delicate balance of efficiency and discretion',
    'cleared from the right side of the guest',
    'minimizing noise and disruption',
    'reading the room to identify the right moments for engagement',
    'without over-serving or interrupting conversations',
    'seamless transition between courses',
  ],
  'training_table_manicuring_c2_u8': <String>[
    'maximizing each trip to and from the kitchen, bar, or other essential areas',
    'carrying items in both directions',
    'consistently enter and exit with their hands full',
    'When servers practice FIFO',
    'proactively maintain other tables',
    'removing unnecessary items from the surrounding areas',
  ],
  'training_table_manicuring_c3_u0': <String>[
    'proactive and continuous process',
    'straw wrappers, cutlery bands, condensation-filled glasses, and empty ramekins',
    'from the moment guests are seated until their departure',
    'Unlike standard table maintenance, which focuses merely on functionality',
    'leading to better tips and more efficient table turns',
  ],
  'training_table_manicuring_c3_u1': <String>[
    'Rather than resting solely on the shoulders of the assigned server',
    'any staff member who passes by is encouraged to participate',
    'remains unobtrusive and fluid',
    'swiftly wiping away small, sticky spots',
    'maintaining impeccable table settings between courses',
  ],
  'training_table_manicuring_c4_u0': <String>[
    'embodying calmness, confidence, and grace',
    'a frantic approach can be disruptive and make guests feel hurried or uneasy',
    'project composure, it signals control and professionalism',
    'an anxious demeanor can lead guests to perceive an underlying issue',
    'prompting them to search for problems',
  ],
  'training_table_manicuring_c4_u1': <String>[
    'refolding napkins every time guests leave the table',
    '"crumbing" tables between courses',
    'a thorough, "down to the wood" cleaning approach',
    'every level of debris is addressed',
    'conveys a sense of care and professionalism',
  ],
  'training_table_manicuring_c4_u2': <String>[
    'truly a team effort',
    'transcending the boundaries of individual sections',
    'prioritizes the collective experience of our guests',
    'shifts from one of "that\'s not my table" to one of shared responsibility',
    'take the initiative, regardless of whose table it is',
    'guests feel valued and cared for',
  ],
  'training_table_manicuring_c5_u0': <String>[
    'meticulously control the flow of the meal',
    'each course is served promptly without the risk of overcrowding the table',
    'encourages guests to indulge in dessert and after-dinner beverages',
    'contributing positively to the restaurant\'s bottom line',
    'quietly removing items, waitstaff can facilitate quicker table turns',
    'avoiding any sense of being rushed',
  ],
  'training_table_manicuring_c5_u1': <String>[
    'directly impacting gratuity and guest feedback',
    'leading to increased tips and positive reviews',
    'clean table reduces visual clutter, alleviating stress and discomfort',
    'contributing to a sophisticated, "whiteglove" ambiance',
    'establishing a repeatable and consistent system',
    'diminishing the dependency on key staff members',
  ],
};
