// GENERATED by tool-side authoring, then verified against the live card
// bodies: every phrase below is a unique, whole-word, non-overlapping
// substring of THAT card's body. A phrase that does not match would simply
// fail to highlight, silently, so the check is not optional.
//
// Why per card: the old per-manual term lists were shared by every card in a
// manual, so which words lit up was an accident of word order rather than
// what the card taught. The operator's bar is that scanning only the
// highlights should still convey the card's information.
//
// A card with no entry here falls back to its manual's list, so a partial
// roll-out never leaves a card unhighlighted.


const Map<String, List<String>> kBarrioCardKeysTrainingThreePillars =
    <String, List<String>>{
  'training_three_pillars_c0_u0': <String>[
    'food, service, and atmosphere intertwine',
    'unforgettable guest experience',
    'they are interdependent',
    'form the foundation of each dining experience',
    'true hospitality thrives when food, service, and atmosphere harmoniously converge',
  ],
  'training_three_pillars_c1_u0': <String>[
    'harmonious blend of ambient lighting',
    'carefully curated music, thoughtful layout, and tasteful decor',
    'create an inviting environment',
    'As soon as guests step in',
    'sets the stage for their experience',
    'heartbeat of the dining journey',
  ],
  'training_three_pillars_c1_u1': <String>[
    'Soft, gentle illumination creates a warm and inviting atmosphere',
    'harsh lighting can produce an uncomfortable glare',
    'fluorescent-lit cafeteria',
    'overly dim settings can lead to guests squinting at the menu',
    'warm, welcoming glow that illuminates the space without overwhelming the senses',
  ],
  'training_three_pillars_c1_u2': <String>[
    'without overpowering the intimate conversations',
    'volume level conducive to conversation',
    'Overly loud music can disrupt the joy of shared moments',
    'too quiet a backdrop can render the space unwelcoming',
    'takes precedence over personal musical preferences',
    'the music enhances rather than distracts',
  ],
  'training_three_pillars_c1_u3': <String>[
    'directly influence profitability and brand loyalty',
    'intentionally crafted to convey the restaurant\'s identity',
    'clean and hanging straight',
    'share their experiences on social media',
    'acting as organic marketing',
    'not just about aesthetics',
  ],
  'training_three_pillars_c1_u4': <String>[
    'chairs are neatly tucked under tables',
    'floor sparkles without debris',
    'picking up a stray wrapper or sweeping beneath tables after guests depart',
    'fully stocked salt and pepper shakers',
    'A well-organized host stand, free from chaotic piles of menus',
    'cultivates a welcoming ambiance',
  ],
  'training_three_pillars_c1_u5': <String>[
    'well-regulated environment ensures that guests remain comfortable',
    'An optimal temperature is an overlooked detail',
    'cozy winter evening or a warm summer afternoon',
    'significantly enhance the overall enjoyment for the guest',
  ],
  'training_three_pillars_c2_u0': <String>[
    'instills a sense of value in every guest',
    'accurate order fulfillment, reasonable wait times, and prompt resolution',
    'warmth, respect, and genuine personal attention',
    'transcends the mere transactional aspects',
    'forging connections and creating memorable experiences',
  ],
  'training_three_pillars_c2_u1': <String>[
    'articulate the unique attributes of each dish',
    'ingredients, preparation methods, and complementary flavors',
    'make informed choices that align with their preferences',
    'personalized recommendations',
    'builds connection between the guest and the restaurant',
  ],
  'training_three_pillars_c2_u2': <String>[
    'guests are often keenly aware of any mistakes',
    'wrong orders, missing items, or inconsistent service',
    'undermine a guest\'s confidence in the establishment',
    'prioritize polite and clear communication',
    'anticipate guests\' needs and swiftly address any hiccups',
  ],
  'training_three_pillars_c2_u3': <String>[
    'well-paced service creates a seamless flow',
    'guests feel neither rushed nor neglected',
    'body language and engagement levels',
    'gauge whether individuals are in a rush or looking to relax',
    'tailor their service pace accordingly',
  ],
  'training_three_pillars_c2_u4': <String>[
    'how promptly their orders are taken and delivered',
    'reduce wait times without adding undue pressure',
    'balance between attentiveness and discretion',
    'Greeting guests with a warm smile, conducting unobtrusive check-ins',
    'gauge a table\'s mood and respond appropriately',
  ],
  'training_three_pillars_c2_u5': <String>[
    'Service is black and white; hospitality is color',
    'denotes the fundamental competence and efficiency',
    'signifies the deeper emotional connections forged with guests',
    'remembering a guest\'s name or their preference for a dish',
    'transform an ordinary experience into an extraordinary one',
  ],
  'training_three_pillars_c3_u0': <String>[
    'unparalleled ability to unite people',
    'embark on culinary adventures',
    'may not find their way into their home kitchens',
    'transcends mere sustenance',
    'celebration of culture and creativity',
  ],
  'training_three_pillars_c3_u1': <String>[
    'instrumental in building guest trust',
    'prioritizes freshness, correct temperatures, and vibrant flavors',
    'rigorous food quality control',
    'safeguards against foodborne illnesses',
    'high-quality produce and proteins',
    'elevate guest perception',
  ],
  'training_three_pillars_c3_u2': <String>[
    'visual appeal plays a pivotal role in shaping our perception',
    'making the food seem more appetizing even before the first bite is taken',
    'signals the chef\'s expertise and attention to detail',
    'Garnishes such as fresh herbs and vibrant sauces add a burst of color',
    'all elements are proportionally balanced',
    'shared on social media, generating buzz and attracting new guests',
  ],
  'training_three_pillars_c3_u3': <String>[
    'adhering to precise specifications',
    'aligns with the expectations set during previous visits',
    'promotes a sense of reliability',
    'any variations in dish size, appearance, or taste can lead to disappointment and erode trust',
    'inconsistency can jeopardize guest loyalty',
    'prioritize uniformity to maintain the strong relationships',
  ],
  'training_three_pillars_c3_u4': <String>[
    'profound connection to human emotions is frequently overlooked',
    'nostalgia of cherished childhood meals',
    'the thrill of trying something adventurous',
    'comforting embrace of familiar flavors',
    'how deeply intertwined our feelings are with what we eat',
    'also the emotional resonance it carries',
  ],
  'training_three_pillars_c4_u0': <String>[
    'harmonious interplay of service, food, and atmosphere',
    'When these essential elements converge seamlessly',
    'a simple meal becomes a cherished occasion',
    'embraces the creation of lasting memories',
    'each of these pillars stands firm',
    'unlock the potential for unforgettable culinary adventures',
  ],
};
