// GENERATED by tool-side authoring, then verified against the live card
// bodies: every phrase below is a unique, whole-word, non-overlapping
// substring of THAT card's body. A phrase that does not match would simply
// fail to highlight, silently, so the check is not optional.
//
// Why per card: the old per-manual term lists were shared by every card in a
// manual, so which words lit up was an accident of word order rather than
// what the card taught. The operator's bar is that scanning only the
// highlights should still convey the card's information.
//
// A card with no entry here falls back to its manual's list, so a partial
// roll-out never leaves a card unhighlighted.


const Map<String, List<String>> kBarrioCardKeysTrainingStrongFoundation =
    <String, List<String>>{
  'training_strong_foundation_c0_u0': <String>[
    'Consistency serves as the foundation for crafting memorable experiences',
    'By establishing clear standards',
    'Standards are not just operational guidelines',
    'fundamentally shape a brand\'s identity',
    'begins with open communication and committing to regular training',
  ],
  'training_strong_foundation_c1_u0': <String>[
    'Consistency is the foundational pillar of trust',
    'they develop a reliable perception of the brand',
    'High standards create a dependable dining environment',
    'generates authentic word-of-mouth recommendations and positive reviews',
    'valuable forms of free advertising',
    'Such loyalty nurtures a community of enthusiastic fans who return regularly',
  ],
  'training_strong_foundation_c2_u0': <String>[
    'consistency is as an invaluable asset',
    'every guest experience aligns with the last',
    'cultivate a sense of reliability that builds guest loyalty',
    'guests develop clear expectations',
    'Standardized procedures play a major part in delivering consistent and efficient service',
    'reducing the potential for errors, controlling costs',
  ],
  'training_strong_foundation_c2_u1': <String>[
    'depend on a uniform level of excellence with each visit',
    'a positive reputation begins to spread organically',
    'fueling both repeat business and referrals',
    'cohesive brand image is reinforced through consistent messaging across various platforms',
    'restaurants boost marketing efforts and develop a recognizable brand presence',
    'serves to distinguish the restaurant and resonates with guests',
  ],
  'training_strong_foundation_c3_u0': <String>[
    'standardization, which enhances efficiency',
    'minimizes confusion and streamlines workflows',
    'Consistency acts as a safety net',
    'leads to more predictable and manageable food costs',
    'prevent over-portioning that can erode profit margins',
    'accelerating the onboarding process for new staff',
  ],
  'training_strong_foundation_c4_u0': <String>[
    'To drive repeat business and build trust',
    'restaurant owners and management should concentrate',
    'each visit delivers a reliable and enjoyable dining experience',
  ],
  'training_strong_foundation_c4_u1': <String>[
    'dishes taste, look, and feel the same every time',
    'only to discover that its flavor has changed',
    'standardized plating, ingredients, and portion measurements',
    'By implementing standardized recipes',
    'every bite delivers that familiar taste',
  ],
  'training_strong_foundation_c4_u2': <String>[
    'Uniform portion sizes help manage costs',
    'a lukewarm entree can quickly spoil a great meal',
    'Serving food at the appropriate temperature amplifies the flavors',
    'frequently running out of popular dishes can disappoint guests and erode trust',
    'careful inventory management and contingency plans',
  ],
  'training_strong_foundation_c4_u3': <String>[
    'they anticipate a warm and attentive interaction with the staff',
    'The emotional connection forged during these interactions',
    'when the service quality fluctuates, the impact on a restaurant\'s reputation can be profound',
    'every staff member understands the expectations set for them',
    'not only meet but frequently exceed guests\' expectations',
    'each guest leaves feeling like royalty',
  ],
  'training_strong_foundation_c4_u4': <String>[
    'warm, inviting lighting sets the tone',
    'harsh, bright illumination that can render a space sterile',
    'carefully curated selections complementing the restaurant\'s theme',
    'A pristine environment builds trust',
    'Rigorous cleaning schedules must be non-negotiable',
    'every detail feels intentional',
  ],
  'training_strong_foundation_c4_u5': <String>[
    'Operating hours should always be predictable',
    'only to find it unexpectedly closed',
    'By adhering to posted hours and ensuring consistent availability',
    'building a reputation for reliability',
    'commitment to predictability lays the groundwork for longterm success',
  ],
  'training_strong_foundation_c5_u0': <String>[
    'rely on an exceptional dining experience every time they visit',
    'reduces the necessity for expensive marketing campaigns',
    'remain loyal during times of slight price increases',
    'standardized recipes, meticulous inventory management, and precise portion control',
    'eliminate waste, thereby preventing costly food spoilage',
    'Standard Operating Procedures (SOPs) streamline the training process for new staff',
  ],
  'training_strong_foundation_c6_u0': <String>[
    'transition from merely executing tasks to genuinely investing in the quality of their work',
    'not just checkboxes to be ticked off but are integral to the overall success',
    'recognize that the standards set forth have purpose',
    'they move from a mentality of obligation',
    'one of enthusiasm characterized by "I want to."',
    'cultivates a workforce that is motivated to surpass expectations',
  ],
  'training_strong_foundation_c6_u1': <String>[
    'nurture an environment that encourages emotional investment',
    'Transparent communication and ongoing guidance are key components',
    'understand the rationale behind policies',
    'more likely to engage fully and feel connected to their work',
    'By clarifying expectations and providing guidance',
    'creates a culture of pride and collaboration',
  ],
  'training_strong_foundation_c6_u2': <String>[
    'Systems serve as the foundational framework that supports every team member',
    'operate with consistency and clarity',
    'staff can feel secure in their roles',
    'a clear path to follow',
    'rely on established protocols',
    'stability and confidence that translates into improved service for guests',
  ],
  'training_strong_foundation_c6_u3': <String>[
    'transforms a diverse group of individuals into a cohesive team',
    'When training is thorough and offers hands-on experience',
    'empowered to make decisions that align with the restaurant\'s standards',
    'when training is rushed or lacks clarity',
    'contribute to higher staff turnover',
    'actively seek clarification on processes and guidelines',
  ],
  'training_strong_foundation_c6_u4': <String>[
    'Setting a clear standard serves as a cornerstone for driving performance',
    'When expectations are well-defined, it fosters alignment among all members',
    'the real challenge lies in ensuring that everyone is on board, energized, and motivated',
    'identify areas of strength alongside potential gaps in performance',
    'reinforce tools that capitalize on strengths while addressing weaknesses',
    'culture of support and open communication can significantly enhance the work environment',
  ],
};
