// GENERATED by tool-side authoring, then verified against the live card
// bodies: every phrase below is a unique, whole-word, non-overlapping
// substring of THAT card's body. A phrase that does not match would simply
// fail to highlight, silently, so the check is not optional.
//
// Why per card: the old per-manual term lists were shared by every card in a
// manual, so which words lit up was an accident of word order rather than
// what the card taught. The operator's bar is that scanning only the
// highlights should still convey the card's information.
//
// A card with no entry here falls back to its manual's list, so a partial
// roll-out never leaves a card unhighlighted.


const Map<String, List<String>> kBarrioCardKeysTrainingSuggestiveSelling =
    <String, List<String>>{
  'training_suggestive_selling_c0_u0': <String>[
    'enhance both guest satisfaction and revenue generation',
    'not just about pushing additional items onto the guest',
    'requires a keen awareness of the menu and an ability to read guests\' preferences',
    'feels organic rather than forced',
    'encouraging repeat business',
  ],
  'training_suggestive_selling_c1_u0': <String>[
    'two essential sales strategies: passive selling and active selling',
    'occurs when guests take the initiative to make purchases',
    'without direct prompting from staff',
    'generates revenue effortlessly, requiring minimal ongoing operational involvement',
    'merchandise cabinets, franchising opportunities, membership fees, and rental fees',
    'demand a high level of effort and engagement',
  ],
  'training_suggestive_selling_c1_u1': <String>[
    'characterized by a proactive approach where the seller actively engages with guests',
    'seeking out sales opportunities through direct interaction',
    'marked by high engagement levels',
    'personalized consultations, active outreach, and targeted direct marketing',
    'build loyalty, and ultimately drive sales',
  ],
  'training_suggestive_selling_c2_u0': <String>[
    'a sales tactic within the realm of active selling',
    'servers recommending complementary items',
    'leverage their detailed menu knowledge',
    'framed in a way that highlights their value',
    'indulge in higher-value options without feeling coerced',
  ],
  'training_suggestive_selling_c2_u1': <String>[
    'Rather than employing high-pressure techniques',
    'utilize timing and descriptive language',
    'a light nudge toward an enhanced experience',
    'thoughtful addition rather than an aggressive upsell',
    'read guest cues and respond with sincere, helpful recommendations',
    'boost both average guest check and overall sales',
  ],
  'training_suggestive_selling_c2_u2': <String>[
    'encourages guests to consider a more expensive or upgraded version of an item',
    'increasing the average guest check',
    'the art of persuasion in sales',
    'present the benefits of premium options',
    'understand the guests\' needs and preferences',
    'alternatives that feel both natural and advantageous',
  ],
  'training_suggestive_selling_c2_u3': <String>[
    'suggesting related or complementary items',
    'enhance the guest\'s primary purchase',
    'boosts the total number of items sold',
    'elevate the value of a guest\'s original selection',
    'create meaningful connections between products',
    'contributes to increased sales',
  ],
  'training_suggestive_selling_c3_u0': <String>[
    'severely undermine the trust and loyalty',
    'Employing aggressive sales techniques',
    'create feelings of pressure and manipulation',
    'bombarded with excessive options',
    'pushed toward high-margin items that do not align with their needs',
    'lead to confusion and irritation',
  ],
  'training_suggestive_selling_c3_u1': <String>[
    'damaged trust, decreased satisfaction, and a decline in repeat business',
    'jeopardizes tips for service staff but also threatens the long-term equity of the brand',
    'shift a company\'s image from one of premium service to a more transactional and desperate approach',
    'leading to decision fatigue',
    'generic recommendations instead of tailored, value-added suggestions',
    'pushing high-priced items on clients with limited budgets risks both their loyalty and the establishment\'s reputation',
  ],
  'training_suggestive_selling_c4_u0': <String>[
    'train staff to provide tailored, enthusiastic recommendations',
    'rather than merely taking orders',
    'grounded in the quality and trust',
    'menu knowledge, personal connection, adaptability, and the strategic picking of moments',
  ],
  'training_suggestive_selling_c4_u1': <String>[
    'familiarity with complementary items, add-ons, preparation details, and portion sizes',
    'have staff taste menu items',
    'memorize upselling and cross-selling options',
    'which wines, beers, or sides perfectly complement each entree',
  ],
  'training_suggestive_selling_c4_u2': <String>[
    'authentic connections that transcend the act of eating',
    'sharing the stories behind dishes',
    'employing vivid, descriptive language',
    'personalized recommendations based on their own experiences',
    'elevating the meal and creating memorable experiences instead of inflating the bill',
  ],
  'training_suggestive_selling_c4_u3': <String>[
    'hesitant to relinquish control over their dining experience',
    'friendly body language and genuine gestures',
    'sincere interest in a guest\'s preferences',
    'authentic recommendations that align with guests\' tastes',
    'elevating the server\'s role to a trusted advisor',
    'presenting recommendations as enhancements to the dining experience rather than selling techniques',
  ],
  'training_suggestive_selling_c4_u4': <String>[
    'transforms the traditional, scripted approach',
    'responsive to real-time guest cues, dietary needs, and the overall pacing of the meal',
    'recognizing moments of indecision over food quantities',
    'suggest an extra side to share',
    'identifying dietary restrictions allows for recommendations of substitutions',
    'stands in stark contrast to the one-size-fits-all script',
  ],
  'training_suggestive_selling_c4_u5': <String>[
    'Timing is undeniably the most critical element',
    'feel genuine rather than intrusive',
    'Instead of leading with an upsell, a server might first inquire about allergies',
    'high-profit appetizers or premium spirits right after the initial drink order is taken',
    'a "premium modifier" or a complementary side dish',
    '"Assumption Close" where the server suggests upgrades with the expectation that the guest is already on board',
  ],
  'training_suggestive_selling_c4_u6': <String>[
    'dessert or coffee recommendations is just after main plates are cleared',
    'match the timing of suggestions to the guests\' pace',
    'quick add-ons for those in a hurry',
    'limiting suggestions to one or two impactful items',
    'avoid making the experience feel overly sales-oriented',
    'increased check amount as an organic outcome rather than the primary objective',
  ],
  'training_suggestive_selling_c4_u7': <String>[
    'Have you been here before?',
    'Guests often rely on restaurant staff as guides',
    'positive phrasing and encouraging questions from guests',
    'personal enthusiasm about specific dishes transforms recommendations from scripts into authentic invitations',
    'increases average check but also increases guest loyalty',
  ],
  'training_suggestive_selling_c4_u8': <String>[
    'begins with upselling, where staff suggest higher-tier products',
    'followed closely by cross-selling complementary items',
    'seamlessly pair entrees with high-margin sides or drinks',
    'offering an upgrade and suggesting an additional item',
  ],
  'training_suggestive_selling_c5_u0': <String>[
    'setting clear and measurable goals',
    'tracking of progress using POS data',
    'defining realistic targets based on past performance',
    'do not inadvertently frustrate their staff',
    'increasing average check averages, higher-margin items, and beverage sales',
    'bonuses for hitting these benchmarks',
  ],
  'training_suggestive_selling_c5_u1': <String>[
    'Aligning these sales goals with the broader objectives of the restaurant',
    'seamlessly integrate with its marketing and service strategies',
    'Regular monitoring of performance through POS data',
    'timely and constructive feedback to the staff',
    'influence how much each guest spends, thereby directly impacting the Average Guest Check',
  ],
};
