// Per-CARD key phrases for the Wine Training manual (doc id
// 'training_wine'), authored against the LIVE card bodies in
// `../../training/training_wine_content.dart`.
//
// Every phrase below is a unique, whole-word, non-overlapping substring of
// THAT card's own body, carries no digit, and does not collide with the
// card's chapter-end quiz answer evidence. Each of those is a silent
// failure mode at render time, not an error: the numeric tier and the
// answer-evidence tier both outrank this one and drop a colliding phrase
// whole, and a phrase that does not match simply never lights up. So the
// check runs before the data ships, never after.
//
// The bar the phrases are written to: scanning ONLY the highlights on a
// card must still convey what that card teaches. Phrases are whole ideas
// (a clause carrying a fact), not single nouns, and they name grape
// characteristics, food pairings, service steps, and regions rather than
// trivia.
//
// Cards with fewer than three phrases that survive those rules carry NO
// entry and fall back to the per-manual list, which is what keeps partial
// coverage safe. See `barrio_card_keys_index.dart` for the full authoring
// contract.

const Map<String, List<String>> kBarrioCardKeysTrainingWine =
    <String, List<String>>{
  // ---- c0: What Is Wine ---------------------------------------------
  'training_wine_c0_u0': <String>[
    'begins with the harvesting and crushing of grapes',
    'yeast converts the natural sugars present in the fruit into alcohol',
    '"Old World" refers to traditional winemaking regions such as France, Italy, and Spain',
    'showcasing the earthiness, minerality, and unique characteristics of the local terroir',
    '"New World" wines emerge from regions like the United States, Australia, and Chile',
    'create fruit-forward wines that highlight the specific grape varieties used',
  ],
  'training_wine_c0_u1': <String>[
    'Unlike table grapes, which are larger and sweeter',
    'wine grapes are smaller, with thicker skins and a concentrated burst of sugars, tannins, and acidity',
    'influenced not only by its genetics but also by the soil, climate, and the choices made by the winemaker',
    'emphasizing the seasonal nature of winemaking',
    'each vintage year on a wine label signifies a snapshot in time',
    'insight into the conditions that shaped that particular bottle',
  ],
  // ---- c1: Key Elements ---------------------------------------------
  'training_wine_c1_u0': <String>[
    'the intricate interplay of factors that define a vineyard\'s unique character',
    'cooler climates are instrumental in preserving high malic acid levels',
    'warmer climates contribute to thicker grape skins and richer tannins',
    'deep clay soils, which retain moisture and soften tannins',
    'gravel soils create natural water stress that encourages deep-rooted vines',
    'deliberate choices in harvest timing, fermentation techniques, and aging methods',
  ],
  'training_wine_c1_u1': <String>[
    'Red grapes are known for delivering rich, intense dark fruit flavors',
    'white grapes typically impart more vibrant and refreshing flavors',
    'how heavy or light it feels on the palate',
    'Full-bodied wines, for instance, deliver a rich and velvety sensation',
    'medium-bodied wines strike a harmonious balance between weight and freshness',
    'Light-bodied wines, on the other hand, offer a more delicate and refreshing profile',
  ],
  'training_wine_c1_u2': <String>[
    'backbone that brings freshness, balance, and aging potential',
    'The three primary acids found in wine are tartaric, malic, and citric',
    'tartaric acid, which serves as the foundational structure and aids in microbial stability',
    'malic acid, abundant in cool-climate grapes and contributing a refreshing crispness',
    'mellowed through malolactic fermentation',
    'citric acid, which adds a subtle citrus zest',
  ],
  'training_wine_c1_u3': <String>[
    'Tannins are the grippy, mouth-drying compounds',
    'adding the structure and assisting with the aging of red wines',
    'vary significantly depending on the grape variety, climate, and winemaking techniques',
    'Bold, high-tannin wines like Cabernet Sauvignon, Nebbiolo, and Syrah can initially present astringency',
    'they develop smoother, more refined textures',
    'softer reds such as Merlot boast lower tannin levels, making them more approachable',
  ],
  // ---- c2: Red v.s White --------------------------------------------
  'training_wine_c2_u0': <String>[
    'Red wine is crafted from dark grapes, undergoing fermentation alongside their skins',
    'allows for the extraction of vibrant color and tannins',
    'impart a rich, bold flavor and a characteristic astringency',
    'white wine is typically produced from lighter-skinned grapes',
    'resulting in a wine devoid of tannins',
    'zesty acidity and bright aromas reminiscent of citrus, apple, and tropical fruits',
  ],
  // ---- c3: Common Red Wine Grape Varietals --------------------------
  'training_wine_c3_u0': <String>[
    'embodies the essence of terroir',
    'sun-drenched vineyards of Napa Valley in California',
    'deep color and full-bodied structure',
    'moderate to high acidity and high tannin levels',
    'In Bordeaux, where Cabernet Sauvignon reigns supreme',
    'layers of black currant, dark spices, and cedarwood',
  ],
  'training_wine_c3_u1': <String>[
    'warm climate allows for grapes to achieve optimal ripeness',
    'rich with blackberry, plum, and hints of cocoa',
    'distinctive terra rossa soil imparting an unmistakable touch of menthol and eucalyptus',
    'Chile\'s Maipo Valley offers a harmonious blend of Old World and New World styles',
    'highlight the savory elements of the grape',
    'intriguing hints of tomato leaf',
  ],
  'training_wine_c3_u2': <String>[
    'The grape\'s thick skins protect it from disease',
    'ability to adapt to various soils and climates',
    'aging potential that reveals complex layers of leather, tobacco, and cedarwood',
    'a favorite among collectors and enthusiasts',
  ],
  'training_wine_c3_u3': <String>[
    'origins traced back to the ancient vineyards of France',
    'moderate to high acidity and low to medium tannins',
    'lighter color and elegant structure',
    'notoriously challenging to cultivate',
    'early harvests tend to produce wines with heightened acidity and lower alcohol',
    'Burgundy, France, remains the spiritual heart of Pinot Noir',
  ],
  'training_wine_c3_u4': <String>[
    'Central Otago in New Zealand, California, and Oregon in the USA',
    'vibrant, fruit-forward expressions that contrast the more restrained style of Burgundy',
    'lush fruit flavors alongside the grape\'s signature earthiness',
    'California\'s diverse climates allow for a wide range of styles',
    'Oregon has also emerged as a notable player',
    'balance fruit, acidity, and complexity',
  ],
  'training_wine_c3_u5': <String>[
    'a key component of Champagne production',
    'Blended with Chardonnay and Pinot Meunier',
    'contributes body and structure to the sparkling wines',
    'delicate balance of flavors',
    'express the nuances of the terroir from which it hails',
  ],
  'training_wine_c3_u6': <String>[
    'producing some of the most intense and complex red wines',
    'Originating from the Rhône Valley in France',
    'cornerstone of renowned wines such as Hermitage and Côte-Rôtie',
    'blackberry, black pepper, and hints of mint',
    'natural medium acidity of these wines invites aging',
  ],
  'training_wine_c3_u7': <String>[
    'the climate is warmer and fruit ripens more fully',
    'vibrant notes of ripe blackberry and distinctive spice',
    'fuller body, medium-high to high tannins, and a luscious mouthfeel',
    'Mendoza in Argentina produces remarkable Syrah wines',
    'benefiting from high altitudes and significant temperature variations between day and night',
    'flavors of licorice and dark chocolate to emerge as the wine matures',
  ],
  'training_wine_c3_u8': <String>[
    'regions like Paso Robles and Sonoma',
    'mirrors the opulence of the Barossa Valley',
    'rich, fruit-driven wines layered with spices and earthy undertones',
    'both bold and nuanced expressions of this powerful grape',
    'convey the essence of its terroir',
  ],
  'training_wine_c3_u9': <String>[
    'its name implying a diminutive version of Syrah',
    'robust structure, elevated tannins, and lively acidity',
    'deeply concentrated and richly textured',
    'Thriving particularly in California\'s diverse wine regions',
    'dense, full-bodied red wines',
    'ripe blackberry, luscious plum, and velvety dark chocolate',
  ],
  'training_wine_c3_u10': <String>[
    'traces back to the Mediterranean regions of Apulia in Italy and Croatia',
    'found a particularly hospitable home in California',
    'bold, black-skinned grape',
    'jammy raspberries and blackberries, intertwined with hints of anise and black pepper',
    'White Zinfandel, a sweeter rosé variant',
    'retains a certain level of residual sweetness due to its high sugar content',
  ],
  'training_wine_c3_u11': <String>[
    'originated in Cahors, France',
    'Locally referred to as Côt',
    'dark fruit profiles and earthy nuances',
    'complex flavors that highlight dark berries and plum',
    'medium acidity and a full body',
    'allowing its tannins to soften and its flavors to evolve',
  ],
  'training_wine_c3_u12': <String>[
    'Mendoza, Argentina has become synonymous with Malbec',
    'high-altitude vineyards that define the region',
    'luscious flavors of ripe plum and dark berries',
    'warm, sunny climate coupled with cool nights allows for optimal ripening',
    'aging process in oak barrels further elevates Malbec\'s profile',
    'enhancing its chocolate and spice notes',
  ],
  'training_wine_c3_u13': <String>[
    'known as Grenache in France',
    'low to medium acidity, low to medium tannins, and a medium body',
    'coupled with high alcohol content',
    'Thriving in warm, arid climates',
    'thick skins and drought-resistant nature',
    'juicy red berry flavors, along with subtle herbal notes and a touch of spice',
  ],
  'training_wine_c3_u14': <String>[
    'iconic wines like Châteauneuf-du-Pape in the Rhône Valley',
    'often blended with Syrah and Mourvèdre',
    'rich, full-bodied wines that are both inviting and richly textured',
    'winemakers experiment with its bold profile',
    'juicy fruit, soft tannins, and warming alcohol',
  ],
  'training_wine_c3_u15': <String>[
    'Bordeaux in France, Napa Valley in the United States, Tuscany in Italy',
    'likely named after the French word "merle" which means blackbird',
    'medium acidity, medium chalky tannins, and a medium-to-full body',
    'notes of red or black plum, depending on the ripeness',
    'subtle hints of chocolate, mild cherry, and leafy nuances',
    'soften the bold tannins of Cabernet Sauvignon',
  ],
  'training_wine_c3_u16': <String>[
    'loose clusters and large berries',
    'high sugar content while maintaining lower levels of malic acid',
    'signature soft and round mouthfeel',
    'earlier picking to retain acidity and enhance the wine\'s aging potential',
    'later harvesting to amplify the ripe fruit characteristics',
    'richer, darker flavors of plum and chocolate',
  ],
  'training_wine_c3_u17': <String>[
    'high acidity, medium-plus tannins, and full-bodied structure',
    'Chianti, Brunello di Montalcino, and Vino Nobile di Montepulciano',
    'warm Mediterranean climate and diverse terroirs allow Sangiovese to flourish',
    'red cherry, earthy herbs, dried flowers, and leather',
    'provide a structure that pairs beautifully with food',
    'compatibility with oak aging enhances its depth and complexity',
  ],
  // ---- c4: Common White Wine Grape Varietals ------------------------
  'training_wine_c4_u0': <String>[
    'most notably Bordeaux and the Loire Valley in France',
    'celebrated for its high acidity and distinctive flavor profile',
    'showcases Sauvignon Blanc\'s mineral-driven character',
    'crisp, dry, and often infused with zesty notes of green apple, citrus, and grassy herbs',
    'In New Zealand\'s Marlborough region, Sauvignon Blanc has garnered international fame',
    'Chilean versions may present a more approachable fruitiness with a slightly herbal undertone',
  ],
  'training_wine_c4_u1': <String>[
    'A distinguished variation of Sauvignon Blanc that was introduced in California',
    'unique oak aging process',
    'imparts smoky and toasty flavors to the wine',
    'subtle notes of hazelnut and caramel',
    'offers a richer, rounder texture',
  ],
  'training_wine_c4_u2': <String>[
    'Originating from the esteemed Burgundy region of France',
    'one of the most universally embraced white wine grapes worldwide',
    'In cooler climates, expect vibrant notes of green apple, pear, and citrus',
    'warmer regions present luscious flavors of fig and tropical fruits',
    'chalk and limestone enhancing its structure and minerality',
  ],
  'training_wine_c4_u3': <String>[
    'particularly through oak aging and malolactic fermentation',
    'adding layers of toasty vanilla, spice, and caramel',
    'a creamy, buttery mouthfeel',
    'it plays a vital role in crafting exquisite sparkling wines, most notably Champagne',
    'contributes a seamless balance of elegance and acidity',
  ],
  'training_wine_c4_u4': <String>[
    'while genetically identical, showcase distinct personalities',
    'produces Pinot Gris wines that are often fuller-bodied and more textured',
    'flavors of ripe pear, lemon, and subtle floral notes',
    'smooth, sometimes oily mouthfeel',
    'Italy\'s Pinot Grigio is celebrated for its approachable, light, and crisp character',
    'bright lemon and melon notes',
  ],
  'training_wine_c4_u5': <String>[
    'such as Oregon and Washington in the USA, as well as California and Australia',
    'wines with lower acidity and higher alcohol levels',
    'a fuller mouthfeel that can mimic the richness found in Alsace',
    'leans towards lush fruitiness',
    'a more opulent style, with pronounced fruit flavors',
  ],
  'training_wine_c4_u6': <String>[
    'notably Germany, Alsace, Australia, Washington State, and New Zealand',
    'steep, slate-rich hillsides of the Mosel and Rheingau',
    'allowing it to age gracefully',
    'Alsace produces drier Rieslings that are more structured',
    'Australian Rieslings, especially from the Clare and Eden Valleys, present a vibrant lime character',
  ],
  'training_wine_c4_u7': <String>[
    'balance citrus acidity with aromatic notes',
    'In Washington State, Riesling retains its crisp, refreshing profile',
    'hints of honeysuckle and tropical fruit',
    'emphasize a broader range of flavors, including toast and spice',
    'flavor notes ranging from citrus and honey to wax and even a hint of petrol',
  ],
  'training_wine_c4_u8': <String>[
    'including Alsace in France, Germany, Northern Italy, the Pacific Northwest of the USA, and Australia',
    'low acidity, full body, and high aromatic profile',
    'distinguishes itself with a deeper complexity and an unmistakable lush texture',
    'trace back to a Traminer variety from northern Italy',
    'buds early and thrives best in cooler climates',
    'a lingering residual sweetness that captivates the palate',
  ],
  'training_wine_c4_u9': <String>[
    'originating from the Loire Valley in France',
    'ranging from crisp, dry whites to rich, lusciously sweet dessert styles',
    'high acidity and vibrant fruit notes, such as honeyed apple, quince, and floral undertones',
    'riper flavors like peach and tropical fruit',
    'affectionately known as Steen',
    'the country\'s most widely planted variety',
  ],
  'training_wine_c4_u10': <String>[
    'roots that potentially tracing back to ancient Egypt',
    'a common signature of high aromatics and fruit-forward profiles',
    'highly aromatic and often sweet nature, featuring a light to medium body',
    'Fresh flavor notes of citrus, rose, and peach',
    'complex notes reminiscent of fruit cake, raisins, and toffee',
  ],
  'training_wine_c4_u11': <String>[
    'Muscat of Alexandria stands out for its adaptability and abundance',
    'thriving in warmer climates and lending itself to the production of sweet dessert wines',
    'Muscat Blanc à Petits Grains, revered for its floral and melon flavors',
    'essential in crafting iconic wines such as Moscato d\'Asti',
    'Muscat Ottonel\'s cool-climate origins yield lighter, delicately sweet wines',
    'the Black Muscat variety produces richly aromatic red wines',
  ],
  // ---- c5: Other Notable Grape Varietals ----------------------------
  'training_wine_c5_u0': <String>[
    'A high-acid white grape from northwestern Spain',
    'high tannins, tar and rose aromas',
    'offering dry, aromatic wines with citrus, floral, and mineral notes',
    'high alcohol, bright acidity, red berry flavors, and earthy, gamey notes',
    'high acidity, subtle fruit flavors, and use in Brandy production',
    'high acidity and low tannins, delivering juicy dark fruit flavors',
  ],
  'training_wine_c5_u1': <String>[
    'known for its floral, aromatic wines with bright citrus, peach, and tropical fruit notes',
    'A Greek white variety from Santorini, producing crisp, mineral-rich wines',
    'combining Pinot Noir\'s fruitiness with Cinsault\'s earthiness',
    'A full-bodied, aromatic white from France\'s Rhône Valley',
    'Spain\'s flagship red grape, used in Rioja and Ribera del Duero',
    'known for its rich blackberry, herbal, and meaty characteristics',
  ],
  // ---- c6: Sparkling Wine -------------------------------------------
  'training_wine_c6_u0': <String>[
    'the benchmark for sparkling wine',
    'must originate from the specific Champagne region in northern France',
    'the second fermentation occurs inside a sealed bottle, trapping carbon dioxide to create bubbles',
    'spend extended time on the yeast lees',
    'a distinctive aroma of fresh baked bread and a creamy, luxurious mouthfeel',
  ],
  'training_wine_c6_u1': <String>[
    'a style often celebrated for its remarkable elegance and finesse',
    'a blanc de noirs (white of blacks) is a white Champagne produced exclusively from the red grapes',
    'typically richer and more full-bodied',
    'red base wine is added to white base wine until the desired shade is achieved',
    'a method employed before the second fermentation that is rarely used elsewhere in winemaking',
  ],
  'training_wine_c6_u2': <String>[
    'dominated by non-vintage (NV) offerings',
    'the base wine is a skillful blend of multiple vintages',
    'This blending ensures remarkable consistency from year to year',
    'setting aside the best lots to create a vintage Champagne',
    'A producer\'s finest offering, often made from the best fruit and vineyards, is known as a prestige cuvée',
  ],
  'training_wine_c6_u3': <String>[
    'mandatory sur lie aging where bottles rest on spent yeast cells called lees',
    'imparts bready, biscuit-like flavors and a creamy mouthfeel',
    'the lees must be removed through a process called disgorging',
    'topping up with a reserve wine known as liqueur d\'expédition',
    'which may include added sugar, known as a dosage',
    'from bone-dry Brut Nature to sweet Doux',
  ],
  'training_wine_c6_u4': <String>[
    'its meticulous, labor-intensive production and the prestige of its terroir',
    'the high real estate value of the Champagne region',
    'results in a higher price compared to other bubblies',
    'remarkably flexible with food and sublime on its own',
  ],
  'training_wine_c6_u5': <String>[
    'French sparkling wines produced outside the Champagne region',
    'made using the same traditional method as Champagne',
    'a fraction of the price of their Champagne counterparts',
    'Produced across key wine regions such as the Loire Valley, Alsace, and Burgundy',
    'reliably delicious, refreshing, and consistently affordable',
  ],
  'training_wine_c6_u6': <String>[
    'the best-known examples hailing from Penedès near Barcelona',
    'local Spanish varieties like Macabeo, Xarel·lo, and Parellada',
    'warmer climate typically yields lower acidity than French counterparts',
    'less pronounced bready notes and lower acidity',
    'noticeably more body and structure',
    'pairs well with a wide range of foods',
  ],
  'training_wine_c6_u7': <String>[
    'A premium sparkling wine from Lombardy in northern Italy',
    'crafted primarily from Chardonnay and Pinot Noir',
    'the traditional "metodo classico" (secondary fermentation in bottle)',
    'earned Italy\'s highest DOCG classification',
  ],
  'training_wine_c6_u8': <String>[
    'an appellation in the northeastern corner of Italy',
    'only wines from this specific area can legally bear the name Prosecco',
    'the Conegliano-Valdobbiadene zone',
    'typically made with the local Glera grape varietal',
    'secondary fermentation occurs in large pressurized tanks rather than in individual bottles',
    'preserving fresh fruit flavors like green apple and melon',
  ],
  'training_wine_c6_u9': <String>[
    'significantly more affordable than Champagne',
    'look for "Prosecco Superiore" for premium, extra-fine bottles',
    'the most produced sparkling wine in the world',
    'its light, fruity character is best enjoyed young',
    'pairs beautifully with spicy cuisines and warm-weather occasions',
    'the classic choice for mimosas',
  ],
  'training_wine_c6_u10': <String>[
    'A red sparkling wine from central Italy',
    'ranges in color from light ruby to deep purple',
    'can be either bone dry or semi-sweet',
  ],
  'training_wine_c6_u11': <String>[
    'these aromatic sparkling wines are sweeter and lower in alcohol',
    'delightful flavours of peaches, grapes, and roses',
    'Moscato d\'Asti offers a lightly sparkling style with lower alcohol and less sweetness',
  ],
  'training_wine_c6_u12': <String>[
    'a sparkling wine produced in Germany',
    'often made from grapes imported from Italy or France',
    'Germany itself is the world\'s largest consumer of sparkling wine',
    'bottles labeled as Deutscher Sekt',
    'must be made entirely from German-grown grapes',
    'the finest examples typically crafted from Riesling',
  ],
  'training_wine_c6_u13': <String>[
    'elegant, complex traditional method sparkling wines',
    'primarily from Chardonnay and Pinot Noir',
    'cooler regions such as the Yarra Valley, Adelaide Hills, and Tasmania',
    'the Southern Hemisphere\'s preeminent red sparkling wine',
    'ripe red berry flavors and a touch of sweetness',
  ],
  // ---- c7: Argentinian Wine -----------------------------------------
  'training_wine_c7_u0': <String>[
    'a true powerhouse in the wine world',
    'crafting some of the most bold, elegant, and distinctive wines',
    'the country\'s diverse terroir produces wines that cater to every palate',
    'consistently delivering exceptional quality',
  ],
  // ---- c8: History of Argentinian Wine ------------------------------
  'training_wine_c8_u0': <String>[
    'Spanish missionaries introduced European vine species along the Atlantic coast',
    'the first vineyards were established in Mendoza and San Juan',
    'becoming the dominant variety for centuries',
    'the construction of a railroad connecting Mendoza to Buenos Aires',
    'Mendoza soon emerged as Argentina\'s most productive wine region',
  ],
  'training_wine_c8_u1': <String>[
    'initially prioritized quantity over quality',
    'winemakers focused on crafting exceptional wines',
    'a resurgence in exports mainly to the US and UK',
    'each with unique soils, climates, and altitudes',
    'Wineries have also embraced wine tourism',
  ],
  // ---- c9: Argentina Terroir ----------------------------------------
  'training_wine_c9_u0': <String>[
    'Argentina\'s wine regions experience a surprisingly uniform range of climates',
    'As one travels north, vineyards are planted at progressively higher elevations',
    'the effective growing conditions remain remarkably similar',
    'Even the extreme vineyards of Colomé near Salta',
  ],
  'training_wine_c9_u1': <String>[
    'the abundant water supply from the Andes supports high yields',
    'it also dilutes the concentration of substances in the grapes',
    'strategically restricting water flow to the vines',
    'generally characterized by arid and dry conditions',
    'it prevents the onset of diseases and mold',
    'high sun exposure, low humidity, and cool nights',
  ],
  // ---- c10: Argentina's Wine Growing Regions ------------------------
  'training_wine_c10_u0': <String>[
    'The undisputed heart of Argentine viticulture',
    'vineyards thrive in a desert landscape, sheltered from rain by the towering Andes Mountains',
    'naturally protects the vines from pests and molds',
    'providing abundant sunshine, cool nights, and low humidity',
    'perfect conditions for producing concentrated, flavorful red wines',
    'excels with varieties like Bonarda, Cabernet Sauvignon, Syrah, and Tempranillo',
  ],
  'training_wine_c10_u1': <String>[
    'distinct subregions like the Uco Valley and Luján de Cuyo showcase diverse microclimates',
    'The cooler, elevated Uco Valley yields wines with refined acidity and elegant intensity',
    'Luján de Cuyo, with its robust soils and slightly warmer climate',
    'produces wines with deep fruit flavors and structured tannins',
    'sustainable viticulture and modern techniques are increasingly embraced',
  ],
  'training_wine_c10_u2': <String>[
    'Mendoza\'s climate is classified as semi-desert',
    'many vineyards are planted on light, free-draining soils',
    'prompting most producers to protect their best plots with hail nets',
    'trained using the pergola system, where a leafy roof shields the grapes from intense sun',
    'Well-managed flood irrigation, applied infrequently with large volumes, encourages deep root growth',
    'olive trees often interplanted among old vines',
  ],
  'training_wine_c10_u3': <String>[
    'Argentina\'s oldest wine-producing area',
    'hot, dry summers and cool nights',
    'allows grapes to ripen slowly and develop deep, concentrated fruit flavors with vibrant acidity',
    'The mineral-rich soils and unique terroir impart distinctive complexity',
    'especially in varietals like Malbec, Cabernet Sauvignon, Torrontés, and Syrah',
  ],
  'training_wine_c10_u4': <String>[
    'Argentina\'s cool-climate wine region',
    'uniquely shaped by its proximity to the Atlantic Coast',
    'oceanic winds and significant diurnal temperature variation help preserve the acidity and flavor',
    'a smooth, creamy texture that appeals to those who favor lighter reds',
  ],
  'training_wine_c10_u5': <String>[
    'Located just north of Mendoza',
    'Argentina\'s second-largest wine-producing region',
    'high temperatures and dry climate',
    'high-yielding grape varieties such as Tempranillo and Syrah',
    'rich spice notes and bold, vibrant red fruit flavors',
    'a robust, full-bodied red with an extra punch of intensity',
  ],
  'training_wine_c10_u6': <String>[
    'Nestled in the rugged landscape of northwestern Argentina',
    'possessing some of the highest vineyards on Earth',
    'intense sunlight and cool nights, force the vines to struggle',
    'grapes of remarkable purity and concentration',
    'wines with vivid aromatics, bright acidity, and deeply structured flavors',
  ],
  // ---- c11: Argentina's Wine Varietals ------------------------------
  'training_wine_c11_u0': <String>[
    'Malbec is undoubtedly the most iconic variety',
    'celebrated for its dark fruit notes and velvety texture',
    'flavors of plum, black cherry, and subtle spice',
    'its abundance of old vineyards',
    'often interplanted with olive trees',
  ],
  'training_wine_c11_u1': <String>[
    'a large genetic reservoir of Carmenère',
    'the Catena Institute conducted a massive massal selection process',
    'identifying and propagating high-quality vines with small berries and strong disease resistance',
    'intense, full-bodied red wines that burst with flavors of cherry and blueberry',
    'originally brought to Argentina by the French',
  ],
  'training_wine_c11_u2': <String>[
    'particularly in regions like Mendoza and the Uco Valley',
    'dark fruit flavors, spicy notes, and a rich structure',
    'Often aged in French oak',
    'subtle toasted oak nuances',
    'delivers a high-tannin, intense experience',
    'high-altitude vineyards add remarkable depth and intensity',
  ],
  'training_wine_c11_u3': <String>[
    'particularly when sourced from the cooler climates of Patagonia and the Uco Valley',
    'vibrant red fruit flavors like black cherry and strawberry',
    'a velvety texture with just a hint of spice',
    'a refreshing, easy-drinking wine that balances fruit and finesse',
    'gracing everything from grilled fish to charcuterie',
  ],
  'training_wine_c11_u4': <String>[
    'In the sun-drenched wine regions of San Juan and La Rioja',
    'deep ruby-colored wines that burst with bold black fruit flavors, black pepper, smoked meat, and dark chocolate',
    'This full-bodied varietal offers a smooth yet structured finish',
    'its robust character beautifully complements the rich, savory notes of the cuisine',
  ],
  'training_wine_c11_u5': <String>[
    'particularly those who appreciate balance and versatility',
    'cool-climate regions such as Patagonia and the Uco Valley',
    'a harmonious blend of crisp acidity and ripe fruit flavors',
    'bright citrus notes like lemon and lime',
    'hints of green apple and a subtle creamy texture when oak-aged',
    'pairs beautifully with seafood, chicken, or fresh salads',
  ],
  'training_wine_c11_u6': <String>[
    'Argentina\'s signature white grape',
    'the high-altitude vineyards of San Juan and Salta provinces',
    'Renowned for its intensely aromatic profile',
    'an ideal choice for warm-weather enjoyment',
    'Its crisp, refreshing character, accented by a subtle touch of spice',
  ],
  'training_wine_c11_u7': <String>[
    'sparkling wine production in Argentina is a dynamic and growing segment',
    'the high-altitude vineyards contribute to sparkling wines with exceptional freshness and fine bubbles',
    'the cool climate helps retain vibrant acidity',
    'both the traditional method (Méthode Champenoise) and the Charmat method',
    'The traditional method typically produces wines with complex, toasty flavors and persistent effervescence',
    'the Charmat method emphasizes fresh, fruity, and approachable profiles',
  ],
  // ---- c12: Chilean Wine --------------------------------------------
  'training_wine_c12_u0': <String>[
    'evolving from a troubled and divisive political past into a modern, forward-looking nation',
    'Its open-market economy has driven strong growth',
    'earn a reputation for consistency and quality',
    'Chilean wines stand out for their remarkable consistency in quality from vintage to vintage',
    'controlled irrigation that reduces yield variation',
  ],
  'training_wine_c12_u1': <String>[
    'long-established family-owned bodegas with generations of expertise',
    'such as Concha y Toro',
    'top winemakers and investors from Europe and California have been drawn to Chile',
    'are rarely over-oaked or overly tannic, and remain fruit-forward without needing aging',
    'a growing number of smaller, independent wineries are emerging',
    'embrace organic, natural, biodynamic, and sustainable practices',
  ],
  // ---- c13: Chilean Wine History ------------------------------------
  'training_wine_c13_u0': <String>[
    'high yields from the fertile, warm, and flood-irrigated Central Valley',
    'that era of bargain-priced wines has largely ended',
    'now dominated by copper, of which it is the world\'s largest producer',
    'Booming demand from China has strengthened the Chilean peso',
    'labor for the wine industry has become both more expensive and scarcer',
    'energy costs have risen rapidly',
  ],
  'training_wine_c13_u1': <String>[
    'a surprisingly deep winemaking tradition',
    'vines of the Pais grape from that colonial era still survive',
    'unlike virtually every other wine-producing region on Earth',
    'Chile\'s wines can represent old-world vines in a way the Old World itself can no longer',
    'The national grape, Carmenere',
    'having found its true renaissance as a flagship single-variety wine in Chile',
  ],
  // ---- c14: Chilean Terroir -----------------------------------------
  'training_wine_c14_u0': <String>[
    'Chile\'s extraordinary geographical span',
    'encompasses virtually every climate type except for tropical and subtropical zones',
    'the flat, fertile Central Valley, where warm temperatures and rich soils facilitated large yields',
    'enabling vineyards to be established on cooler, less fertile south-facing slopes',
    'allowed winemakers to plant on a greater variety of soils and altitudes',
    'Andean snowmelt provides essential water reserves for irrigated vineyards',
  ],
  'training_wine_c14_u1': <String>[
    'Chile\'s east-west topography introduces dramatic temperature variations',
    'Chile excelled at matching climate with grape variety',
    'The alluvial terraces of the Maipo River near Santiago',
    'further moderated by cool mountain air descending at night',
    'deeper knowledge of soil types, appropriate planting densities, careful rootstock and clonal selections',
  ],
  // ---- c15: Chilean Wine Regions ------------------------------------
  'training_wine_c15_u0': <String>[
    'attempting to put in place an appellation system to better define its wine regions',
    'from the Andes to the sea',
    'Chile\'s climate is heavily influenced by proximity to the cool Andes and the cool coastal ranges',
    'the well-named Central Valley and its warm offshoots are shaped more by latitude',
    'creating significant temperature variations',
  ],
  'training_wine_c15_u1': <String>[
    'Chile\'s first major success with Cabernet Sauvignon',
    'currently called Maipo Alto or Upper Maipo',
    'near the head of the Maipo River and close to the Andes Mountains',
    'alluvial terraces of rounded stones and gravel deposited by the river',
    'These well-drained, heat-retaining soils perfectly suit Cabernet Sauvignon',
    'cool air descending from the Andes at night moderates temperatures',
  ],
  'training_wine_c15_u2': <String>[
    'The high-altitude vineyards, stony soils, and cooling mountain air',
    'firm, linear Cabernets with an attractive cedary profile',
    'richer than Bordeaux, requiring no Merlot to soften them',
    'Cabernet Franc is often blended in to contribute cigar-box aromas',
    'offer simpler, softer, fruitier expressions with less structure and length',
    'lack the complexity and aging potential',
  ],
  'training_wine_c15_u3': <String>[
    'one of the highest and coolest communes',
    'west-facing slopes push cabernet to its ripening limits',
    'imparting a subtle minty character',
    'either remarkably elegant or austere',
  ],
  'training_wine_c15_u5': <String>[
    'a coastal town in Chile where the Maipo River meets the sea',
    'a burgeoning wine region with many vineyards still in their early stages',
    'The precise appellation boundaries remain fluid',
    'Leyda, a sub-area slightly further inland',
    'reflecting a dynamic and evolving winegrowing landscape',
  ],
  'training_wine_c15_u6': <String>[
    'Nestled on the south bank of the Maipo River',
    'this varied commune produces fine, elegant wines',
    'consistently understated and fine-boned',
  ],
  'training_wine_c15_u7': <String>[
    'yields softer, broader wines compared to Macul, Puente Alto, and Pirque',
    'the fourth alluvial terrace soils of the River Maipo',
    'surface layer of franco',
    'layer of stones and gravel over sand and boulders',
  ],
  'training_wine_c15_u8': <String>[
    'the soils become more varied',
    'fingers of the finest stony soil derived from the Maipo\'s third and fourth alluvial terraces',
    'Buin\'s style closely resembling that of Alto Jahuel',
  ],
  'training_wine_c15_u9': <String>[
    'In the central region downstream of Santiago',
    'warmer temperatures and diminished Andean influence',
    'distance from the Pacific\'s cooling effects',
    'create less distinguished soils',
    'the gravelly banks with a high water table in Isla de Maipo',
  ],
  'training_wine_c15_u10': <String>[
    'a bowl-shaped valley',
    'where cold air collects and frost is a frequent hazard',
    'numerous sub-valleys and widely varying microclimates',
    'underlain largely by clay and loam soils',
    'the eastern end near Veramonte is warm enough to ripen merlot and pinot noir',
    'the coolest south-western point can be almost too windy and cool for sauvignon blanc and chardonnay',
  ],
  'training_wine_c15_u11': <String>[
    'the significant challenge of a severe water deficit',
    'a pipeline was constructed to pump water from the Maipo River',
    'Cooled by the Pacific Ocean',
    'planted on low-fertility granitic soils on rolling hillsides',
    'varieties such as Chardonnay, Sauvignon Gris, Riesling, and Syrah soon gained recognition as among the best in the country',
  ],
  'training_wine_c15_u12': <String>[
    'planted on steep slopes',
    'in Lo Abarca with pinot noir, riesling, sauvignon blanc, and sauvignon gris',
    'particularly susceptible to fungal diseases like botrytis',
    'due to their coastal proximity',
  ],
  'training_wine_c15_u13': <String>[
    'an exceptionally dynamic wine region defined by its dramatic temperature gradient',
    'cool near the coast and warming inland',
    'a diverse array of soils including rare limestone, granite, clay, and rocky types',
    'Viognier, Syrah, and Red Muscat thrive further inland',
    'the taut, firm, and mineral chardonnays from limestone-rich soils',
    'a gap in the coastal range to the northwest that channels a strong ocean influence',
  ],
  'training_wine_c15_u14': <String>[
    'Chile\'s coolest vineyard is defined by its extraordinary limestone soil',
    'a sedimentary marine terrace composition',
    'Talinay wines emerge with a remarkably taut and mineral character',
    'This bedrock acts like a sponge, storing water during dry periods yet draining freely in floods',
    'Its alkaline nature limits the uptake of certain elements, restricting vine vigor',
    'impressive structure, subdued fruit, and exceptional aging potential',
  ],
  'training_wine_c15_u15': <String>[
    'situated near the bodega',
    'produce successful Syrah',
    'the newer Espinal vineyards',
    'yield impressive Pinot and Chardonnay',
  ],
  'training_wine_c15_u16': <String>[
    'the vineyard\'s upper soil layer',
    'clay above alluvial subsoils',
    'has made Pinot Noir a standout success here',
    'better mid-palate weight than most other coastal vineyards',
  ],
  'training_wine_c15_u17': <String>[
    'The northernmost commercial wine-producing valley',
    'supports substantial table-grape cultivation',
    'tiny experimental vineyards dot the hyper-arid Atacama Desert',
  ],
  'training_wine_c15_u18': <String>[
    'The valley rises and narrows, cooling as it gains elevation',
    'At its upper end lies the Alto Los Toros vineyard',
    'The intense heat is moderated by the high altitude',
    'the pergola training system shades the grapes like a parasol',
    'providing crucial protection from strong ultraviolet rays',
  ],
  'training_wine_c15_u20': <String>[
    'a considerable number of old unirrigated Cabernet and Carmenère vines',
    'in decomposed granite soils',
    'a water table lies within reach of the roots',
    'Carmenère, which ripens a month after cabernet',
    'thrives in Apalta\'s ample heat and water',
    'ensuring its leaves stay active and the wine avoids green flavors',
  ],
  'training_wine_c15_u21': <String>[
    'producing abundant quantities of good, inexpensive wines alongside ordinary bulk offerings',
    'generally warm yet marked by cooler, sloping sites near the mountains',
    'much of what was labeled as Sauvignon Blanc actually came from here',
    'it was made from Tocai Friulano, a variety lacking pronounced aromatic intensity',
    'beginning to shift toward higher-quality production',
  ],
  'training_wine_c15_u22': <String>[
    'widely recognized in Chile for its sparkling wines',
    'primarily crafted from grapes sourced from coastal vineyards',
    'Some Rhône varieties, for instance, come from the warm Sagrada Familia region',
    'very old bush-vine Carignan',
    'blended into a ripe, southern-Rhône-style wine called Eclat',
  ],
  'training_wine_c15_u23': <String>[
    'enthusiastically embraced by twelve Chilean wineries',
    'the remainder sourced from old vine varieties',
    'grafted onto old país rootstock',
    'the dry-farmed Maule secano region',
  ],
  // ---- c16: Chilean Wine Varietals ----------------------------------
  'training_wine_c16_u0': <String>[
    'often hailed as the king of Chilean grapes',
    'thrives in warmer valleys like Maipo, Colchagua, and Aconcagua',
    'delivering a full-bodied, intense wine',
  ],
  'training_wine_c16_u1': <String>[
    'their similar appearance and the grape\'s distinctive peppery, herbaceous character',
    'Chilean Merlot was actually Carmenère',
    'Rather than uproot the vines, Chileans embraced the variety',
    'cultivating it far more extensively than in its native Bordeaux',
    'prized for its deep color and complexity',
    'flavors of tart raspberries, cocoa powder, and herbaceous notes of green peppercorn',
  ],
  'training_wine_c16_u2': <String>[
    'Ranking second among Chile\'s primary red grape varieties',
    'produces simple table wines during high-yielding seasons',
    'smoother, less intense flavor compared to Cabernet Sauvignon',
  ],
  'training_wine_c16_u3': <String>[
    'especially from the cool coastal valleys of Casablanca and San Antonio',
    'bright, citrusy, and fruit-forward profile with high acidity',
    'a subtle jalapeño aroma',
    'adds a savory, green note to the otherwise zesty character',
    'the wine\'s acidity and herbal hint beautifully complement the dish\'s fresh, citrus-marinated seafood',
  ],
  'training_wine_c16_u4': <String>[
    'Riesling thrives in cooler climates',
    'the cooler valleys south of Santiago: Rapel, Curicó, and Maule',
    'limiting Riesling\'s production volume',
    'range from lush green to golden yellow in color',
    'a light, fresh taste that is occasionally mineral',
    'vibrant citrus notes of grapefruit, lemon, apple, and passion fruit',
  ],
  'training_wine_c16_u5': <String>[
    'Chardonnay thrives in limy soils and a moderate climate',
    'neutral, lightly fruity, and exotic aromas',
    'along with excellent acidity',
  ],
  // ---- c17: Spanish Wine --------------------------------------------
  'training_wine_c17_u0': <String>[
    'a tradition that pulses through every region\'s identity',
    'Spain\'s famed tapas culture, where small, savory plates are designed to be shared',
    'the refreshing wine-based drink that has become a global symbol of Spanish hospitality',
    'especially popular during the hot summer months',
    'this effortless pairing of food, drink, and social connection',
  ],
  'training_wine_c17_u1': <String>[
    'much of which flows from European Union frameworks',
    'clear categories should simplify buying decisions',
    'Frequent regulatory changes can create confusion rather than clarity',
    'segmented into a hierarchy of aging categories',
    'The production of Gran Reserva wines, those long-aged powerhouses, has been steadily decreasing',
    'Crianza, younger, fresher, and more approachable, is enjoying a remarkable surge in popularity',
  ],
  // ---- c18: Spanish Wine History ------------------------------------
  'training_wine_c18_u0': <String>[
    'Spain\'s viticultural roots run deeper than any other country',
    'The Phoenicians first planted vines in sun-drenched regions',
    'the Romans later transformed by introducing new grape varieties and advanced techniques',
    'the Moorish occupation',
    'Spanish winemakers replanted with phylloxera-resistant American rootstock',
    'a bold move that saved the industry and paved the way for modern innovation',
  ],
  'training_wine_c18_u1': <String>[
    'The earliest Spanish wines were strong and often sweet or rancio',
    'fully oxidized and heavily reduced for safe storage',
    'The Greeks had sealed amphorae with pine resin',
    'In Spain, winemakers turned to tinajas',
    'long neglected but now rediscovered by a new generation',
    'a living link to the ingenuity of the past',
  ],
  // ---- c19: Spanish Terroir -----------------------------------------
  'training_wine_c19_u0': <String>[
    'confronting the harsh realities of climate change head-on',
    'Water scarcity and prolonged droughts are becoming increasingly common',
    'threatening vine development and the delicate balance of wine quality',
    'embracing sustainable viticultural practices',
    'safeguard the future of some of Europe\'s most iconic wine regions, from Rioja to Ribera del Duero',
  ],
  'training_wine_c19_u1': <String>[
    'Spain is the third most mountainous country in Europe',
    'altitude plays as crucial a role as latitude in shaping wine character',
    'This rugged topography, crisscrossed by major rivers like the Tajo, creates a tapestry of microclimates',
    '"Green Spain" with abundant rainfall and mild temperatures',
    'the continental Meseta, marked by scorching summers, cold winters, and scarce rainfall',
    'the Mediterranean coast, where sea breezes temper the heat',
  ],
  // ---- c20: Spanish Wine Regions ------------------------------------
  'training_wine_c20_u0': <String>[
    'Reigning as the undisputed king of Spanish wine',
    'global respect for its elegant, age-worthy reds',
    'a diverse patchwork of vineyards',
    'the chalky, limestone-rich soils of Rioja Alta',
    'the more modern, fruit-forward expressions emerging from Rioja Oriental',
    'its distinctive hallmark of balance and longevity',
  ],
  'training_wine_c20_u1': <String>[
    'Nestled along the Duero River in Castilla y León',
    'crafting powerful, full-bodied red wines from Tempranillo',
    'known locally as Tinto Fino',
    'consistently earn international recognition',
  ],
  'training_wine_c20_u2': <String>[
    'Located in Catalonia\'s rugged, mountainous terrain',
    'steep, slate-soiled terraces and extreme climate',
    'intensely concentrated red wines from Garnacha and Cariñena',
    'worldwide acclaim for its distinctive, powerful character',
  ],
  'training_wine_c20_u3': <String>[
    'Positioned in Galicia\'s cool, Atlantic-influenced Rías Baixas',
    'owe their distinctive character to the perfect growing conditions',
    'the vineyards\' proximity to sea level',
    'the moderating influence of the Atlantic Ocean',
  ],
  'training_wine_c20_u4': <String>[
    'Although Cava is not a geographical region itself',
    'Spain\'s iconic sparkling wine',
    'masterfully crafted in the Penedès area of Catalonia',
    'using the traditional method and native grape varieties such as Macabeo, Parellada, and Xarel-lo',
    'countless local vineyards wholly dedicated to its production',
  ],
  'training_wine_c20_u5': <String>[
    'Nestled in Spain\'s sun-drenched Andalusia region',
    'the undisputed sherry capital of the world',
    'each aged to perfection through the meticulous solera system',
  ],
  'training_wine_c20_u6': <String>[
    'Located in the rugged northwestern corner of Castilla y León',
    'just a stone\'s throw from the Portuguese border',
    'crafted almost exclusively from the Mencía grape',
    'slate and granite soils impart a remarkable mineral tension and layered complexity',
    'aromatic, structured, and often surprising, with a distinct earthiness',
    'the cool Atlantic influence that shapes this dramatic landscape',
  ],
  'training_wine_c20_u7': <String>[
    'Situated along the Duero River in Castilla y León',
    'crafted from the Tinta de Toro grape, a robust local clone of Tempranillo',
    'intense fruit flavors, firm tannins, and elevated alcohol content',
    'the region\'s scorching summers and sandy soils',
  ],
  'training_wine_c20_u8': <String>[
    'Stretching across central Spain',
    'the country\'s largest wine region',
    'vast vineyards that yield an impressive array of red and white wines',
    'hosts many of Spain\'s unclassified vineyards',
  ],
  'training_wine_c20_u9': <String>[
    'Produced from the Hondarrabi Zuri grape',
    'the Basque Country\'s rugged coastal vineyards',
    'a captivatingly crisp, low-alcohol profile with high acidity and a gentle spritz',
    'an ideal pairing for the region\'s bountiful seafood cuisine',
  ],
  // ---- c21: Spanish Red Wine Varietals ------------------------------
  'training_wine_c21_u0': <String>[
    'Considered the backbone of Spain\'s most celebrated reds',
    'the legendary wine regions of Rioja and Ribera del Duero',
    'a compelling balance of power and finesse',
    'wines of medium to full body',
    'cradled by famously smooth tannins',
    'aging in American or French barrels imparts layers of vanilla, spice, and toast',
  ],
  'training_wine_c21_u1': <String>[
    'yields rich, fruit-forward red wines with soft tannins and elevated alcohol',
    'expressions from esteemed regions like Priorat and Montsant',
    'celebrated for their intense, concentrated flavors and powerful structural depth',
    'it demands a longer ripening window',
    'modern winemaking technologies have quelled oxidation fears',
    'consumer fatigue with Tempranillo has sparked renewed interest',
  ],
  'training_wine_c21_u2': <String>[
    'the sunbaked, arid landscapes of southeastern Spain',
    'full-bodied red wines defined by dark fruit intensity and firm, structured tannins',
    'dismissed as overly alcoholic and lacking finesse',
    'producers in Murcia\'s Jumilla and Yecla regions transformed the grape\'s reputation',
    'revealing Monastrell\'s capacity for vibrant complexity and deep, ripe fruit character',
    'the powerful structure and strength that make it a distinctive, age-worthy variety',
  ],
  'training_wine_c21_u3': <String>[
    'Once a workhorse grape used to bolster the color and alcohol content of European wines',
    'now primarily cultivated in Valencia',
    'has undergone a remarkable quality renaissance',
    'producing full-bodied, vividly colored wines that stand proudly on their own',
  ],
  'training_wine_c21_u4': <String>[
    'Grown in the borderlands of Zamora where Spain meets Portugal',
    'possesses immense untapped potential',
    'the region currently lacks the wineries and investment to realize it',
    'the fruit contains all the essential components for producing exceptional wines',
  ],
  'training_wine_c21_u5': <String>[
    'In the Balearic Islands of eastern Spain',
    'yields delightfully light, fruit-forward wines',
    'increasingly crafted with minimal oak',
    'a dynamic new generation of Binissalem winemakers',
  ],
  'training_wine_c21_u6': <String>[
    'The dominant grape of Tacoronte-Acentejo and the broader Canary Islands',
    'skillfully harnessed by local wineries',
    'distinctive, terroir-driven wines that vividly express the region\'s volcanic origins',
  ],
  'training_wine_c21_u7': <String>[
    'Though not a native Spanish varietal',
    'has thrived across Spain\'s diverse regions',
    'its robust tannins are often softened through blending with local grapes',
    'complex, internationally appealing wines',
  ],
  'training_wine_c21_u8': <String>[
    'may not rival Cabernet Sauvignon\'s widespread acclaim in Spain',
    'this classic Bordeaux variety',
    'carved out a quietly successful niche across numerous Spanish wine regions',
    'adding appealingly soft, plush textures to the local portfolio',
  ],
  'training_wine_c21_u9': <String>[
    'particularly in La Mancha and Mediterranean regions',
    'Syrah has gained notable popularity',
    'a distinctly full-bodied, high-alcohol expression',
    'sets it apart from its counterparts in the Rhône Valley or Australia',
  ],
  'training_wine_c21_u10': <String>[
    'A member of the esteemed Tempranillo family',
    'thrives in the sun-drenched soils of Zamora',
    'produces robust, full-bodied wines that capture the region\'s bold character',
  ],
  // ---- c22: Spanish White Wine Varietals ----------------------------
  'training_wine_c22_u0': <String>[
    'Originating in the Rueda region of Castilla y León',
    'aromatic intensity, tropical fruit, fennel, and fresh grass',
    'balanced by a surprising body and bright citrus-mineral undertones',
    'a frustrating tendency to oxidize easily',
    'modern techniques like refrigeration and night harvesting',
    'the authentic, herbaceous complexity',
  ],
  'training_wine_c22_u1': <String>[
    'the star white grape of Rías Baixas in the northwestern Spanish region of Galicia',
    'renowned for their aromatic intensity and crisp, refreshing acidity',
    'a silky texture imparted by naturally high glycerin levels',
    'balances the zesty citrus and stone fruit notes',
    'confirming Albariño\'s deep-rooted Iberian heritage',
    'producing vibrant, mineral-driven whites that are rich yet never cloying',
  ],
  'training_wine_c22_u2': <String>[
    'With its honeyed richness and affordability',
    'known as muscat in France',
    'in the hands of young Spanish winemakers',
    'craft dynamic, value-driven sweet wines from Valencia\'s Mediterranean vineyards',
  ],
  'training_wine_c22_u3': <String>[
    'Originating in Greece',
    'thrives across Spain, from Valencia to the Canary Islands',
    'semi-fortified sweet wines with a striking volcanic character',
    'appearing in Rioja blends with Viura',
    'in Catalonia, under the name subirat-parent',
  ],
  'training_wine_c22_u4': <String>[
    'Once nearly forgotten',
    'masterfully revived in Galicia\'s Valdeorras region',
    'exquisitely aromatic white wines',
    'balance crispness and peachiness with a rich, dry complexity',
  ],
  'training_wine_c22_u5': <String>[
    'also known as Listán',
    'fails to achieve remarkable results elsewhere',
    'it thrives exclusively in the chalky soils of Jerez de la Frontera',
    'produce the region\'s iconic Fino sherries',
  ],
  'training_wine_c22_u6': <String>[
    'Also known as Xarel-lo',
    'the backbone of quality Cava',
    'provides the alcohol, weight, and power essential for the blend',
    'it historically oxidized quickly',
    'modern innovations such as early harvesting and temperature-controlled fermentation',
    'capable of producing excellent still wines as well',
  ],
  'training_wine_c22_u7': <String>[
    'Widely cultivated across Catalonia',
    'produces approachable, easy-drinking still white wines',
    'unassuming in their individual charm',
    'a key component in the region\'s celebrated sparkling cava',
  ],
  'training_wine_c22_u8': <String>[
    'Though often overlooked',
    'thrives in the scorching summers of La Mancha',
    'long been used as the base for brandy',
    'modern winemaking techniques are unlocking its potential',
    'tours from Madrid that also pass the iconic Don Quixote windmills',
  ],
  'training_wine_c22_u9': <String>[
    'Once a humble table grape',
    'has risen to prominence in Spanish winemaking',
    'its aromatic skins are increasingly used to enhance the often neutral profiles of Airen and Viura',
    'particularly in Ribera del Duero and the heavily planted vineyards of Madrid',
  ],
  'training_wine_c22_u10': <String>[
    'also known as Viura',
    'anchors both the traditional production of Cava in Catalonia',
    'the nuanced, herb-and-spice-driven still wines of Rioja and Navarra',
    'even a neutral variety can yield captivating complexity',
  ],
  'training_wine_c22_u11': <String>[
    'often abbreviated as PX',
    'the foundational grape of Spain\'s Montilla-Moriles region',
    'its sun-drenched berries in southern Spain produce intensely rich dessert wines',
    'with age, deepen to an almost black hue',
    'equally superb for sipping and as a decadent topping for cakes and ice cream',
  ],
  // ---- c23: Spanish Wine Classification -----------------------------
  'training_wine_c23_u3': <String>[
    'a classification for Spanish wines that do not fall under any specific DO or IGP',
    'often made from grapes sourced from various regions',
    'a more affordable, easy-drinking option for consumers',
    'fruity and approachable, making them perfect for everyday enjoyment',
  ],
  'training_wine_c23_u4': <String>[
    'produced from grapes grown in a specific vineyard',
    'the entire winemaking process takes place on the estate',
    'represent the highest level of Spanish wine production',
    'showcase the unique terroir of individual estates',
  ],
  // ---- c24: Portuguese Wine -----------------------------------------
  'training_wine_c24_u0': <String>[
    'a viticultural revolution that mirrors the transformation seen in neighbouring Spain',
    'Rather than chasing international trends by planting ubiquitous global grape varieties',
    'The new generation of full-bodied, fruit-forward wines',
    'a distinctive alternative to the familiar profiles of Cabernet, Merlot, and Chardonnay',
    'turning a perceived conservatism into a powerful market differentiator',
    'this trove of bold, authentic tastes is a welcome discovery',
  ],
  'training_wine_c24_u1': <String>[
    'the progressive stance many Portuguese producers are taking on sustainability',
    'Long-term research projects and a deep respect for ancient techniques',
    'Portugal\'s ancient cork forests provide the raw material',
    'one of its most iconic exports',
    'supports both the environment and local livelihoods',
    'a vital pillar of the nation\'s economy',
  ],
  // ---- c25: Portuguese Wine Regions ---------------------------------
  'training_wine_c25_u0': <String>[
    'Nestled in Portugal\'s verdant northwest',
    'renowned for its lightness and traditionally delicate spritz',
    'serving as the backbone for many blends',
    'the Loureiro grape dominates further south, lending floral and citrus notes',
    'The classic, inexpensive styles retain that signature pétillance',
    'a more still, concentrated expression',
  ],
  'training_wine_c25_u1': <String>[
    'one of the wettest and most fertile areas for vine cultivation',
    'grapes that ripen with moderate sugar levels',
    'defined by crisp acidity, lively fruit flavors, and a low alcohol content',
    'one of the most refreshing dry wine styles',
    'an excellent partner for the region\'s abundant fish and charcuterie',
    'the red Vinho Verde, with its naturally low alcohol and rather astringent profile',
  ],
  'training_wine_c25_u2': <String>[
    'Located in the country\'s rugged north-east',
    'hemmed in by towering peaks on one side and the Spanish border on the other',
    'Its schistous soils and grape varieties echo those of the Douro Valley',
    'harsh, frost-laden winters and parched summers with scant rainfall',
    'lighter in body and more aromatic than their Douro neighbours',
    'a distinctly perfumed, elegant expression',
  ],
  'training_wine_c25_u3': <String>[
    'the Douro Valley is the undisputed crown jewel',
    'No longer content to live in the shadow of its own famous fortified wine',
    'a palpable pioneering spirit among the winemakers',
    'many of whom are the very port shippers',
    'producing full-flavored reds and fresh, crisp whites',
  ],
  'training_wine_c25_u4': <String>[
    'Its terraced vineyards cling to spectacularly steep, sun-baked slopes',
    'the overarching character is hot, arid, and ruggedly sparse',
    'the fragrant Touriga Nacional, alongside Touriga Franca, Tinta Roriz, Tinta Cão, and Tinta Barroca',
    'naturally high in tannin and intense in flavor',
    'preserving fruit and freshness',
    'power never comes at the expense of elegance',
  ],
  'training_wine_c25_u5': <String>[
    'where granite slopes are sheltered by towering mountains and protective pine forests',
    'long home to one of Portugal\'s most recognizable red wines',
    'Once dominated by lackluster cooperatives that produced uninspiring bottles',
    'thrives through a vibrant wave of small, dynamic producers',
    'craft approachable, elegant wines that capture both the rugged terroir and a newfound finesse',
  ],
  'training_wine_c25_u6': <String>[
    'this strikingly disparate region defies easy categorization',
    'vineyards cling to high-altitude granite slopes',
    'cooler temperatures and well-drained soils lend tension and minerality',
    'The north echoes the classic varieties of the Douro Valley',
    'a compelling mosaic of indigenous and experimental grapes, from Aragonez to Trincadeira',
    'altitude tempering the heat',
  ],
  'training_wine_c25_u7': <String>[
    'takes its name from the clay-rich soils',
    'famously tough and astringent in youth, with searing acidity and firm tannins',
    'given time they evolve into elegantly perfumed, complex bottlings',
    'blend baga with international grapes to create softer, more approachable cuvées',
    'cool late-afternoon breezes from the coast lend freshness',
  ],
  'training_wine_c25_u8': <String>[
    'a sprawling, breezy countryside',
    'the country\'s largest wine-producing region by volume',
    'persistent onshore winds off the Atlantic, which cool the vineyards',
    'preserve the fresh acidity and aromatic lift',
    'the tiny DOC of Bucelas',
    'turns out crisp, dry whites',
  ],
  'training_wine_c25_u9': <String>[
    'Straddling the banks of the River Tagus',
    'approachable, everyday drinking wines that showcase remarkable stylistic diversity',
    'a broad range of permitted grape varieties',
    'a predominantly flat, sandy expanse',
    'Palmela, whose sandy soils perfectly suit the Castelão grape, yielding robust reds',
    'a luscious sweet fortified wine crafted primarily from Muscat of Alexandria',
  ],
  'training_wine_c25_u10': <String>[
    'Stretching south from the Tagus River to the sun-drenched Algarve',
    'encompasses nearly a third of mainland Portugal',
    'a patchwork of vineyards divided into seven distinct sub-regions',
    'interwoven with olive groves, cork oak forests, wheat fields, and grazing sheep',
    'droughts are a recurring trial',
    'one of Portugal\'s most dynamic wine regions',
  ],
  // ---- c26: Portuguese White Wine Varietals -------------------------
  'training_wine_c26_u1': <String>[
    'Primarily cultivated in Portugal\'s Minho region',
    'yields crisp, aromatic wines',
    'vibrant notes of peach, apple, and citrus',
    'underpinned by a distinctive mineral character',
  ],
  'training_wine_c26_u2': <String>[
    'Widely cultivated across northern and central Portugal',
    'the padernã grape, better known in the Vinho Verde region',
    'produces dry, tangy wines brimming with bright citrus fruit',
    'an engaging, crisp character',
  ],
  'training_wine_c26_u3': <String>[
    'In the Bairrada region',
    'also known as Maria Gomes',
    'produces crisp, aromatic wines with delicate floral notes',
    'a refreshingly low acidity that makes them wonderfully approachable',
  ],
  // ---- c27: Portuguese Red Wine Varietals ---------------------------
  'training_wine_c27_u0': <String>[
    'Known as Tinta Roriz in northern Portugal',
    'this cornerstone Douro grape',
    'prized for its robust tannins',
    'vibrant bouquet of raspberry and red-fruit flavours',
  ],
  'training_wine_c27_u1': <String>[
    'Though not especially widely planted',
    'earned a devoted following among winemakers',
    'its deep-coloured, well-balanced wines',
    'it remains a challenge for vine growers',
    'its pronounced susceptibility to rot',
  ],
  'training_wine_c27_u2': <String>[
    'Primarily cultivated in Bairrada and also found in Dão',
    'this late-ripening variety',
    'can yield lean, tannic reds in lesser hands',
    'serving as the base for lively sparkling wines',
  ],
  'training_wine_c27_u3': <String>[
    'Often referred to as Periquita in the southern reaches',
    'this widely planted variety',
    'yields fleshy, fruit-forward reds with occasional gamey undertones',
    'equally suited for early enjoyment or extended cellaring',
  ],
  'training_wine_c27_u4': <String>[
    'Once considered the backbone of many Ports',
    'now equally celebrated for its still red wines',
    'ideally suited for long-term ageing',
  ],
  'training_wine_c27_u5': <String>[
    'One of the most widespread varieties',
    'making flavourful, dry reds',
    'blackcurrant fruit flavours and herbaceous, floral aromas',
  ],
  // ---- c28: Port ----------------------------------------------------
  'training_wine_c28_u0': <String>[
    'a fortified wine whose soul lies in the Douro Valley',
    'a rule as strict as Champagne\'s appellation',
    'Crafted traditionally from red grapes but now also in white and rosé styles',
    'tightly regulated by Wines of Portugal',
    'Many vineyards still practice interplanting and manual harvesting',
    'from Ruby and Tawny to Late Bottle Vintage, Colheita, Reserve, or Single Quinta',
  ],
  // ---- c29: Wine Glasses --------------------------------------------
  'training_wine_c29_u0': <String>[
    'a carefully engineered tool that shapes the entire tasting experience',
    'The bowl\'s size and contour determine how much surface area is exposed to air',
    'Larger bowls allow full-bodied reds to open up and soften',
    'narrower bowls preserve the freshness and focused aromatics of white wines',
    'The rim, with its precise diameter, concentrates volatile aromas',
    'the base provides stability',
  ],
  'training_wine_c29_u1': <String>[
    'Aeration, the interaction between wine and oxygen',
    'Swirling a wine in a large, wide bowl',
    'unlock complex aromas in young or structured reds',
    'narrow bowls limit oxygen exposure, which suits white wines and delicate reds',
    'tapered shapes funnel aromas directly to the nose, while rounded designs enhance swirling',
    'a catalyst for discovering a wine\'s full potential',
  ],
  // ---- c30: Red Wine Glasses ----------------------------------------
  'training_wine_c30_u0': <String>[
    'every curve and dimension serves a purpose',
    'draws out the wine\'s aromas and flavors while softening harsh tannins',
    'the Cabernet/Merlot glass provides ample bowl space that emphasizes fruit notes',
    'lighter-bodied reds like Pinot Noir and Nebbiolo, which are higher in acidity and moderate in tannins',
    'an exaggeratedly wide bowl that allows unhindered aeration',
    'ideal for thin-skinned red grape varieties',
  ],
  'training_wine_c30_u1': <String>[
    'the Syrah/Shiraz glass is tailored for medium-bodied reds',
    'the Bordeaux glass, tall and broad, works beautifully for bold reds like Cabernet Sauvignon, Merlot, and Malbec',
    'Its large bowl invites generous swirling',
    'a round, wide bowl paired with a narrow mouth to preserve subtle aromatics',
    'the wider opening tames tannins and releases aromatics',
  ],
  // ---- c31: White Wine Glasses --------------------------------------
  'training_wine_c31_u0': <String>[
    'distinctly smaller and more narrow than their red wine counterparts',
    'direct the wine toward the tip of the tongue for a crisp, refreshing finish',
    'excessive oxygen exposure can dull the vibrant freshness',
    'the Sauvignon Blanc glass, for instance, features a narrow bowl that concentrates citrus and herbal notes',
    'the tall, narrow opening of a Riesling glass intensifies floral and fruity aromas',
    'balancing high acidity and residual sugar',
  ],
  'training_wine_c31_u1': <String>[
    'encourages gentle oxygenation',
    'allows fuller-bodied, oak-aged whites to develop a creamy texture and rich, layered flavors',
    'expanding their aromatic profile rather than confining it',
    'the common goal of preserving crispness and coolness',
    'one size does not fit all',
  ],
  // ---- c32: Specialty Glasses ---------------------------------------
  'training_wine_c32_u0': <String>[
    'the Bordeaux glass, tall and broad, works beautifully for bold reds like Cabernet Sauvignon, Merlot, and Malbec',
    'Its large bowl invites generous swirling',
    'the Pinot Noir glass, also known as a Burgundy glass',
    'a round, wide bowl paired with a narrow mouth to preserve subtle aromatics',
    'the wider opening tames tannins and releases aromatics',
  ],
  // ---- c33: Reading Wine Labels -------------------------------------
  'training_wine_c33_u0': <String>[
    'two of the most telling elements are the producer and the region',
    'reveals who actually made the wine',
    'typically produced by a large wine company rather than a small, hands-on estate',
    'A broad designation like "California" generally signals a value-oriented wine',
    'As the source narrows to a single vineyard, the wine\'s refinement and price tend to rise',
    'many blends do not disclose exact percentages',
  ],
  'training_wine_c33_u1': <String>[
    'the appellation can provide clues based on regional regulations',
    'The vintage, or year the grapes were harvested',
    'non-vintage (NV) wines are often lower in value due to blending from multiple years',
    'ABV offers insight into a wine\'s style',
    'indicating riper grapes and more fruit-forward flavors',
  ],
  'training_wine_c33_u2': <String>[
    'Estate bottled wines are those grown, produced, and bottled entirely on the estate',
    'offering a direct connection to a specific vineyard and its terroir',
    'négociant producers source grapes or wine from multiple locations and blend them',
    'often resulting in a more approachable but generally lower-quality product',
    'many small producers use it to denote their top-tier selections from the best barrels',
    'its appearance on a label does not guarantee a higher standard',
  ],
  'training_wine_c33_u3': <String>[
    '"Old Vine" suggests more concentrated flavors from mature vines',
    'the wine may even include younger vine grapes in the blend',
    'a mandatory U.S. label requirement for all imported and domestic wines',
    'sulfites occur naturally in grapes',
    'the concern is minimal',
  ],
  // ---- c34: How to Open Wine ----------------------------------------
  'training_wine_c34_u0': <String>[
    'briefly introducing the wine\'s main details',
    'whether a creative fantasy label or a straightforward varietal designation',
    'Identify the grape variety or blend',
    'Mention the producer',
    'we remove the capsule, the protective foil covering the cork and neck',
    'cut neatly around the capsule just below the glass lip',
  ],
  'training_wine_c34_u1': <String>[
    'Lift the top portion of the capsule to reveal clear access to the cork',
    'eliminating the risk of torn edges or jagged foil',
    'discreetly place it in your pocket',
    'clean the upper portion of the bottle with a napkin',
    'an attached small knife for cutting foil, a two-notch lever for controlled leverage',
    'insert the corkscrew\'s spiral directly into the center of the cork',
  ],
  'training_wine_c34_u2': <String>[
    'twist the corkscrew steadily, keeping the worm centered',
    'being careful not to penetrate completely to avoid cork particles in the wine',
    'insufficient twisting may cause the cork to break in half',
    'apply steady leverage with a gentle twisting motion and an upward pull on the handle',
    'positioning the appropriate ridge over the bottle\'s lip',
    'Gently ease the cork upward with steady, controlled movements',
  ],
  'training_wine_c34_u3': <String>[
    'place the cork to the side so guests can inspect it at their leisure',
    'the outer end remains dry',
    'a simple yet telling sign of proper storage and condition',
    'give a quick wipe of the bottle\'s neck',
    'pour a small taste for the host to sample',
    'allowing them to approve the selection',
  ],
  'training_wine_c34_u4': <String>[
    'While food is typically placed from the left',
    'turn the label toward the person who ordered the bottle',
    'Pour the wine slowly and steadily into the center of the glass bowl',
    'pour smaller portions when sharing among a larger group',
    'Pour wine for each guest in a clockwise progression around the table',
    'ensuring the host\'s glass is filled last',
  ],
  // ---- c35: How to Open Champagne/Sparkling -------------------------
  'training_wine_c35_u0': <String>[
    'To prevent an explosive geyser effect',
    'Use a wine refrigerator or an ice-water bucket',
    'avoiding any jostling and keeping the bottle dry for a secure grip',
    'cut a smooth, clean line around the top of your champagne bottle',
    'lift and twist the tab of the cork cage counter-clockwise about six turns',
    'placing a cloth napkin securely over the bottle\'s opening helps catch a flying cork',
  ],
  'training_wine_c35_u1': <String>[
    'so the internal pressure presses against the curved glass rather than forcing out the liquid',
    'ensure nothing is in the line of a potential flying cork',
    'rotate the bottle from its base while holding the cork steady',
    'hear a subtle fizzing whisper of pressure release, rather than a forceful pop',
    'ensuring the champagne stays perfectly in the bottle',
  ],
  // ---- c36: How to Pour Champagne/Sparkling -------------------------
  'training_wine_c36_u0': <String>[
    'wasting the wine and creating a mess',
    'Pour slowly, allowing the sparkling wine to cascade gently down the inner side of the glass',
    'rather than plunging straight to the bottom',
    'This controlled flow minimizes agitation',
    'giving the bubbles time to rise and settle without foaming over',
    'Pausing briefly when the glass is half full to let the foam dissipate',
  ],
  // ---- c37: How to Decant Wine --------------------------------------
  'training_wine_c37_u0': <String>[
    'a purposeful ritual that unlocks a wine\'s full potential',
    'giving a young, tightly wound red the oxygen it needs to unfurl its aromas and flavors',
    'color pigments and tannins bond and fall out of solution over time',
    'stirring up that sediment can cloud the wine\'s appearance',
    'introduce bitter, gritty textures',
    'separate the clear wine from its lees through decanting',
  ],
  // ---- c38: How to Taste Wine ---------------------------------------
  'training_wine_c38_u0': <String>[
    'your tasting space should remain as odorless as possible',
    'skip the candles, perfumes, and aromatic foods',
    'rely on natural light, and plenty of it',
    'a stemmed glass featuring a thin rim and a generous bowl',
    'volatilizes the wine\'s aromatic compounds all at once',
    'delivering a fuller, more layered snapshot',
  ],
  'training_wine_c38_u1': <String>[
    'a deep, opaque purple might whisper Syrah or Malbec',
    'a pale, almost greenish glint suggests a crisp Sauvignon Blanc or Grüner Veltliner',
    'red wines gradually surrender their youthful vibrancy, mellowing into brick-like and orange tones as they age',
    'whites move from pale gold toward richer amber hues',
    'most commercial wines are stripped to a sterile, apple-juice-like brilliance',
    'an unfiltered beauty with a purposeful haze',
  ],
  'training_wine_c38_u2': <String>[
    'a pale Cabernet Sauvignon could have had a short, gentle kiss with its skins',
    'a deeply saturated Pinot Noir might have macerated for weeks',
    'coaxing out every bit of colour and structure',
    'Let\'s retire the old adage that they signal a better wine',
    'their viscosity causing them to creep slowly down the glass',
  ],
  'training_wine_c38_u3': <String>[
    'arguably the most critical skill in your wine journey',
    'our "aroma palette" is uniquely personal',
    'universal scents like apple or cherry',
    'wine-specific notes like wet wool or crushed stone',
    'use a structured flavor list as a search grid',
    'trains your brain to recognize and recall aromas far more quickly',
  ],
  'training_wine_c38_u4': <String>[
    'Always start with fruit descriptors',
    'identifying those can unlock a wealth of information about grape variety, climate, terroir, and vintage',
    'zesty citrus like lime or Meyer lemon',
    'crisp green fruit such as Granny Smith apple and gooseberry',
    'deeper black fruit like black currant and blackberry',
    'confected, dried notes of date, prune, or raisin',
  ],
  'training_wine_c38_u5': <String>[
    'Fruit descriptors alone are too vague',
    'early-season notes like sour, green, or unripe suggest youthful acidity',
    'late-season terms such as shrivelled, overripe, or unctuous point to warmer vintages',
    'grilled, pickled, dried, or stewed qualifiers reveal the influence of oak, maceration, or oxidative aging',
    'the fresh, non-fruit aromas that often stem directly from the grape variety itself',
    'delicate rose, violet, or honeysuckle',
  ],
  'training_wine_c38_u6': <String>[
    'evolved notes born from fermentation, biological processes, and aging',
    'the sweet warmth of new oak (vanilla, coconut, or maple)',
    'the earthy intrigue of fungal notes like truffle and damp earth',
    'mineral impressions (flint, river stones, petrichor) speak to geology',
    'Lactic notes of butter or brioche whisper of malolactic fermentation',
    'None of these aromas are inherently good or bad',
  ],
  'training_wine_c38_u7': <String>[
    'the tongue can only perceive salt, sweet, bitter, sour, umami, spice, and texture',
    'The real magic of flavor, however, unfolds through retronasal olfaction',
    'volatile compounds travel up through the back of your throat into your nasal cavity',
    'revealing nuanced notes that were undetectable in the glass',
    'those few seconds after the wine leaves your palate',
  ],
  'training_wine_c38_u8': <String>[
    'Acidity is the backbone of a wine\'s structure',
    'Tartaric, Malic, and Lactic acids',
    'sweetness or alcohol can effectively mask high acid levels',
    'misinterpreting a sharp, zesty sensation for bitterness',
    'close your mouth, tilt your head forward',
    'sour, tart, fruity, puckering, jarring, electric, or invigorating',
  ],
  'training_wine_c38_u9': <String>[
    'our brains can be easily misled by fruity aromas',
    'just because a wine smells like ripe peaches doesn\'t mean it contains sugar',
    'glycerol adds a rich, weighty texture',
    'alcohol itself can taste surprisingly sugary',
    'the presence or absence of sugar says nothing about quality',
  ],
  'training_wine_c38_u10': <String>[
    'a wine with low alcohol can feel thin, short-lived, and diluted',
    'delightfully subtle and ethereal, quaffable, light on its feet',
    'the presence of alcohol often reveals itself most clearly after you swallow',
    'the volatilized warmth rises back up through the breath',
    'distinguish between a harsh, spicy heat and a gentle, integrated glow',
    'whether that character feels distracting or harmonious with the whole',
  ],
  'training_wine_c38_u11': <String>[
    'one of the most elusive yet essential components to articulate',
    'the interplay of acids, sugars, tannins, and alcohols',
    'The classic benchmark for body is the dairy analogy',
    'a light-bodied wine flows across the palate like skim milk',
    'a full-bodied wine coats the mouth with the creamy weight of whole milk',
    'the buoyant lift of a high-acid white to the dense, angular grip of a tannic red',
  ],
  'training_wine_c38_u12': <String>[
    'leaving a distracting burn in the back of the throat',
    'that same heat becomes a warming, soft, almost sweet sensation',
    'a wine with low alcohol can feel thin, short-lived, and diluted',
    'the volatilized warmth rises back up through the breath',
    'distinguish between a harsh, spicy heat and a gentle, integrated glow',
  ],
  'training_wine_c38_u13': <String>[
    'Texture in wine remains one of the most elusive yet essential components',
    'partly exists as a distinct, almost mystical category unto itself',
    'a light-bodied wine flows across the palate like skim milk',
    'a full-bodied wine coats the mouth with the creamy weight of whole milk',
    'we use a straightforward scale, Light, Moderate, Full',
    'the real poetry of texture lies in its quality',
  ],
  'training_wine_c38_u14': <String>[
    'you move from raw observation to interpretation',
    'Complexity, for instance, isn\'t just about counting aromas',
    'it\'s about how those elements interact',
    'Balance then asks whether each structural component (tannin, acid, alcohol, fruit) is offset by a complementary partner',
    'A high-tannin red can be balanced if it carries enough richness and fruit to soften the grip',
    'a context-sensitive poise that makes the wine feel whole rather than lopsided',
  ],
  'training_wine_c38_u15': <String>[
    'wine is ultimately a beverage to be enjoyed, not just analyzed',
    'becomes cloying, fatiguing, or undrinkable after a single glass',
    'Deliciousness, often overlooked in formal tasting rubrics, is a wildly subjective yet valid metric',
    'You should trust your own palate',
    'Typicity adds another layer; a wine should taste like what it claims to be',
    'quality is the sum of these personal and objective judgments',
  ],
};
