// GENERATED by tool-side authoring, then verified against the live card
// bodies: every phrase below is a unique, whole-word, non-overlapping
// substring of THAT card's body. A phrase that does not match would simply
// fail to highlight, silently, so the check is not optional.
//
// Why per card: the old per-manual term lists were shared by every card in a
// manual, so which words lit up was an accident of word order rather than
// what the card taught. The operator's bar is that scanning only the
// highlights should still convey the card's information.
//
// A card with no entry here falls back to its manual's list, so a partial
// roll-out never leaves a card unhighlighted.


const Map<String, List<String>> kBarrioCardKeysTrainingCheersResponsibility =
    <String, List<String>>{
  'training_cheers_responsibility_c0_u0': <String>[
    'served safely and legally',
    'over-serving prevention by understanding the limits of patrons',
    'checking IDs diligently to verify age',
    'recognizing signs of intoxication early on',
    'Both employers and employees share the responsibility',
    'deciding when to cut someone off',
  ],
  'training_cheers_responsibility_c0_u1': <String>[
    'two pivotal pieces of legislation',
    'The Newfoundland and Labrador Control Act and the Liquor Corporation Act',
    'primary legislation for regulating liquor sales',
    'empowers the Newfoundland and Labrador Liquor Corporation (NLC), the Crown\'s agent',
    'issuing, refusing, or suspending liquor licenses and permits',
  ],
  'training_cheers_responsibility_c0_u2': <String>[
    'The Liquor Corporation Act establishes the NLC and its powers',
    'Liquor Licensing Regulations detail specific rules that govern the issuance of licenses',
    'the Smoke-Free Environment Act complements these efforts by protecting individuals from second-hand smoke',
    'including licensed venues',
    'prohibits smoking and vaping indoors and in certain outdoor areas',
  ],
  'training_cheers_responsibility_c0_u3': <String>[
    'broken into two divisions',
    'Licensing and Administration Unit is responsible for issuing licensing and responding to any licensee inquiries',
    'Regulatory Compliance Unit is responsible for conducting inspections, enforcement of rules and regulations',
    'Liquor inspectors are responsible for ensuring compliance by licensees',
    'show up unannounced to monitor compliance',
  ],
  'training_cheers_responsibility_c0_u4': <String>[
    'Each liquor license class has its own eligibility requirements',
    'Restaurant: An establishment which is exclusively engaged in the serving of regular meals',
    'Lounge operates solely for the sale of alcoholic liquor to the public',
    'food and entertainment may or may not be available',
  ],
  'training_cheers_responsibility_c0_u5': <String>[
    'sell to guests at meals',
    'sell to the public',
    'deliver alcoholic liquor to persons who purchased the liquor with a meal',
    'Hotel: An establishment where temporary lodging is regularly provided',
  ],
  'training_cheers_responsibility_c0_u6': <String>[
    'A Special Event License may be issued',
    'any charitable or non-profit organization raising funds for charitable purposes',
    'does not hold a subsisting license issued by the board',
    'sell spirits, beers and wines at a function',
    'on the date or dates to be prescribed in the license',
  ],
  'training_cheers_responsibility_c0_u7': <String>[
    'Catering License is a secondary license',
    'with a meal supplied by way of an off premises catering service',
    'Patio License can be obtained if you are a current licensee',
    'located adjoining the existing licensed establishment',
    'sponsored by a supplier or sales representative',
    'you may apply to NLC for permission',
  ],
  'training_cheers_responsibility_c1_u1': <String>[
    'Blood Alcohol Concentration Chart',
    'helps estimate a person\'s blood alcohol concentration level',
    'based on the amount of alcohol consumed, their body weight, and the time over which the alcohol was consumed',
    'expressed as a percentage',
  ],
  'training_cheers_responsibility_c1_u2': <String>[
    'given the unique ways it affects individuals',
    'slurred speech, impaired coordination, and unusual mood swings',
    'The more of these signs are present, the stronger the case for refraining from serving additional alcohol',
    'Increased speed or rate of consumption',
    'Bloodshot, glassy, or watery eyes',
    'Aggressive or belligerent',
  ],
  'training_cheers_responsibility_c1_u3': <String>[
    'Careless with money',
    'Swaying, staggering, or stumbling',
    'Extreme or sudden change in behaviour',
    'Difficulty standing up',
    'Can\'t find mouth with glass',
    'Odor of alcohol or marijuana',
  ],
  'training_cheers_responsibility_c1_u4': <String>[
    'must be valid and not expired, be the original',
    'examined to verify authenticity',
    'key features such as the photo, description, and security elements',
  ],
  'training_cheers_responsibility_c1_u5': <String>[
    'Provincial Driver\'s License with a Photo issued in NL or another province',
    'The picture and description match the person using the ID',
    'The photograph is genuine and hasn\'t been substituted',
    'The lettering for the name and date of birth hasn\'t been altered',
    'Have the guest remove their ID from their wallet and hold the ID in your hand',
    'Use the acronym FLAG when examining identification',
  ],
  'training_cheers_responsibility_c1_u6': <String>[
    'telltale signs of low-quality manufacturing',
    'bubbles, pin holes, rough edges, and excessive lamination',
    'focus on permanent traits',
    'eye and hair color can be altered',
    'ask targeted, cryptic questions',
    'their postal code, year of high school graduation, or horoscope',
  ],
  'training_cheers_responsibility_c1_u7': <String>[
    'GIVE BACK: If you discover that a guest is using a fake ID',
    'deny them service',
    'inform your fellow staff members',
    'document the incident',
    'only police officers in Canada are authorized to confiscate fake IDs',
  ],
  'training_cheers_responsibility_c2_u0': <String>[
    'Combining alcohol with drugs and other substances',
    'can lead to a range of harmful effects',
    'create challenges for those in the hospitality industry',
    'Understanding these interactions is crucial for serving our guests responsibly',
    'we can encourage safer choices',
  ],
  'training_cheers_responsibility_c2_u1': <String>[
    'The caffeine in energy drinks can mask the sedative effects of alcohol',
    'encouraging them to consume more alcohol',
    'resulting in increased impairment',
    'a higher likelihood of alcohol poisoning or caffeine overdose',
    'caffeine does not enhance alcohol metabolism',
    'it won\'t help sober you up',
  ],
  'training_cheers_responsibility_c2_u2': <String>[
    'alcohol is known to enhance the body\'s absorption of THC',
    'increased euphoria and potential relief from alcohol-induced nausea in smaller doses',
    'Larger doses can result in overwhelming sensations of lethargy, disorientation, and heaviness',
    'faster alcohol absorption, prolonged intoxication, and even drug-related blackouts',
    'focus on one substance at a time',
  ],
  'training_cheers_responsibility_c2_u3': <String>[
    'Alcohol can enhance the intoxicating effects of various medications',
    'whether over-the-counter, prescription, or illicit',
    'heighten intoxication levels up to five times',
    'slurred speech, blurred vision, and slowed reflexes',
    'severe health consequences like overdose or even death',
    'opiates that can slow or stop breathing',
  ],
  'training_cheers_responsibility_c3_u0': <String>[
    'offer a wide variety of low and non-alcoholic drinks',
    'at prices that are competitive with regular alcoholic products',
    'Serving food is one way that you can lower the risk of guests becoming intoxicated',
    'delay the absorption of alcohol into the blood',
    'free or low-priced appetizers for after-work guests',
    'Train your servers to market food',
  ],
  'training_cheers_responsibility_c3_u1': <String>[
    'service must be stopped under any and all circumstances',
    'provide the reason for refused service',
    'do not insult the guest by calling them drunk',
    'Offer to call the guest a taxi',
    'Communicate with all staff about the decision to refuse service',
    'Document the refused service in your log book and with an incident report',
  ],
  'training_cheers_responsibility_c3_u2': <String>[
    'drinking and driving is the primary criminal cause of death and injury',
    'Even small amounts of alcohol or drugs can affect your ability to drive safely',
    'Provide the police with as many details as possible',
    'Observe from a safe distance and allow the police to handle the stop',
  ],
  'training_cheers_responsibility_c3_u3': <String>[
    'Do not take someone\'s keys',
    'puts you in a confrontational position with potential risk to you or the guest',
    'Taking someone\'s keys is classified as theft under the law',
    'Do not put yourself between the person and the vehicle',
    'Offer to call a taxi or family/friend of the guest',
  ],
  'training_cheers_responsibility_c3_u4': <String>[
    'owe a duty of care to their patrons and the public',
    'take reasonable steps to prevent patrons from becoming intoxicated',
    'prohibits licensed establishments from selling alcohol to anyone who is, or appears to be, intoxicated',
    'sue a licensed establishment for damages if an overserved person causes injury, death, or property damage',
    'Whether the patron showed visible signs of intoxication',
    'Whether the bar had a system for monitoring alcohol consumption',
  ],
  'training_cheers_responsibility_c3_u5': <String>[
    'Whether staff attempted to find safe transportation for the patron',
    'Whether the patron was ejected from the premises while intoxicated',
    'can impose fines and suspend or revoke a bar\'s license',
    'bar owners and employees could potentially face criminal charges',
    'purchasing specific liquor liability insurance policies',
    'General commercial liability insurance typically does not cover this exposure',
  ],
  'training_cheers_responsibility_c4_u0': <String>[
    'Once alcohol is bought for consumption at a licensed establishment',
    'it must not leave the premises',
    'remove alcoholic beverages from the licensed footprint',
    'in breach of the Licensing Regulations',
  ],
  'training_cheers_responsibility_c4_u1': <String>[
    'the number of persons on the premises',
    'including employees of the license holder',
    'does not exceed the capacity of the licensed premises',
    'as stated on the capacity card',
  ],
};
