// GENERATED by tool-side authoring, then verified against the live card
// bodies: every phrase below is a unique, whole-word, non-overlapping
// substring of THAT card's body. A phrase that does not match would simply
// fail to highlight, silently, so the check is not optional.
//
// Why per card: the old per-manual term lists were shared by every card in a
// manual, so which words lit up was an accident of word order rather than
// what the card taught. The operator's bar is that scanning only the
// highlights should still convey the card's information.
//
// A card with no entry here falls back to its manual's list, so a partial
// roll-out never leaves a card unhighlighted.


const Map<String, List<String>> kBarrioCardKeysJimTaylorLaborModel =
    <String, List<String>>{
  'jim_taylor_labor_model_c0_u0': <String>[
    'These notes build from zero',
    'Every chapter builds on the last',
    'know exactly what story they are telling',
  ],
  'jim_taylor_labor_model_c10_u0': <String>[
    'Manage the variance, not the %',
    'shows you exactly where the hours went',
    'If you want to make more profit. Manage the variance. Not the %',
  ],
  'jim_taylor_labor_model_c10_u1': <String>[
    'Most operators only track one. That\'s the problem',
    'Theoretical = What should happen',
    'The Gap = Management opportunity',
    'Variance = Actual Labor % - Theoretical Labor %',
  ],
  'jim_taylor_labor_model_c10_u10': <String>[
    'the exact same framework to food cost',
    'theoretical vs actual COGS, recipe costing, contribution margin, menu engineering',
    'The logic is identical. The foundation work is different.',
    'Master the labor model first.',
    'drops in on top of a model that already works',
  ],
  'jim_taylor_labor_model_c11_u0': <String>[
    'why going above it costs you as much as going below',
    'Below OPZ - too many staff',
    'CPLH low - labor bleeds',
    'Above OPZ - too few staff',
    'Check-backs stop - upsells die',
    'Inside the OPZ: team is busy but not overwhelmed',
  ],
  'jim_taylor_labor_model_c11_u2': <String>[
    'add people back. Intentionally.',
    'upsells happen, PPA rises, revenue grows',
    'Labor cost is slightly higher but the sales denominator grows faster',
    'The ratio improves.',
  ],
  'jim_taylor_labor_model_c12_u1': <String>[
    'Count covers, sales, and labor hours every shift - by daypart',
    'CPLH = Covers / FOH Hours. SPLH = Sales / BOH Hours.',
    'builds your theoretical labor %',
    'Actual % - Theoretical %. If it moved, one of the five levers moved with it.',
  ],
  'jim_taylor_labor_model_c12_u2': <String>[
    'Find and defend your OPZ',
    'identify the range where labor % declines and service holds',
    'Below it you are bleeding hours.',
    'Above it you are burning your team.',
    'Stay inside it.',
  ],
  'jim_taylor_labor_model_c12_u3': <String>[
    'PPA = Total Sales / Total Covers',
    'CPLH = Total Covers / FOH Labor Hours',
    'SPLH = Total Sales / BOH Labor Hours',
    'Required FOH Hours = Forecasted Covers / Target CPLH',
    'Labor % = (Hours x Wage) / (Covers x PPA)',
    'Variance = Actual Labor % - Theoretical Labor %',
  ],
  'jim_taylor_labor_model_c12_u4': <String>[
    'Pull covers, sales, and labor hours from POS - by daypart',
    'Calculate CPLH. Inside your OPZ?',
    'Is BOH producing at target? Is PPA where you expected?',
    'Compare to theoretical. What is the variance?',
    'If CPLH inside OPZ, SPLH on target, variance tight -> benchmark shift',
    'Identify which input moved. Fix that specific thing. Not "labor." The input',
  ],
  'jim_taylor_labor_model_c12_u5': <String>[
    'Covers, Labor Hours, PPA, Wage Mix',
    'CPLH - FOH, SPLH - BOH',
    'Required FOH Hours, Required BOH Hours',
    'Theoretical Labor, Variance, OPZ',
  ],
  'jim_taylor_labor_model_c1_u0': <String>[
    'The four raw inputs everything is built from',
    'Before any metric makes sense',
    'the four building blocks',
    'Everything Jim teaches is assembled from these',
  ],
  'jim_taylor_labor_model_c1_u1': <String>[
    'Jim uses covers not tables',
    'completely different amounts of work',
    'Covers are honest. Tables aren\'t.',
  ],
  'jim_taylor_labor_model_c1_u3': <String>[
    'PPA = Total Sales / Total Covers',
    'without a single fewer person walking in',
    'what the team failed to upsell',
  ],
  'jim_taylor_labor_model_c1_u4': <String>[
    'what goes into the labor % formula',
    'Every role, every pay rate, collapsed into one blended average',
    'Labor % moves with it - without a single cover or hour changing',
  ],
  'jim_taylor_labor_model_c2_u0': <String>[
    'The most tracked number in restaurants and the most misunderstood',
    'several restaurants measure units of productivity',
    'almost all of them measure labor costs',
    'few actually understand the importance of understanding how the two work together',
  ],
  'jim_taylor_labor_model_c2_u1': <String>[
    'Labor % is a ratio',
    'It does not tell you if the team worked hard',
    'Labor % = (Hours x Wage) / (Covers x PPA)',
  ],
  'jim_taylor_labor_model_c2_u2': <String>[
    'Four variables. Look at who controls each one',
    'The manager - scheduling decision',
    'Market rates and corporate pay bands',
    'The guests - whether they walk in',
    'A manager directly controls one of the four variables',
    'why good managers get blamed for numbers that were never in their hands',
  ],
  'jim_taylor_labor_model_c2_u3': <String>[
    'Fewer staff -> service slows -> check-backs stop',
    'Guests skip second drinks and desserts -> PPA drops',
    'Labor % is a scoreboard. Not a strategy.',
  ],
  'jim_taylor_labor_model_c3_u0': <String>[
    'Change any one of these and labor % moves',
    'even if nothing else changes',
    'What actually drives labor spend: guest count, average spend, hours worked, wage mix',
    'Change the inputs, the output follows',
    'Keep staring at the percentage, and you\'ll keep getting the same results',
  ],
  'jim_taylor_labor_model_c3_u1': <String>[
    'More guests, same cost',
    'Guests spent less',
    'Manager controls this',
    'Fewer hours - but does service hold?',
    'Set by market/corporate',
  ],
  'jim_taylor_labor_model_c3_u2': <String>[
    'Three of the four inputs - covers, PPA, wage',
    'largely outside a manager\'s control on any given shift',
    'through no action or fault of the manager',
    'you cannot evaluate a manager against a number they barely control',
  ],
  'jim_taylor_labor_model_c4_u0': <String>[
    'CPLH is the best metric to be used in the front of the house',
    'CPLH = Total Covers / Total Labor Hours',
    'Higher CPLH = more guests per hour of labor = more productive',
    'Lower CPLH = fewer guests per hour = overstaffed or slow',
  ],
  'jim_taylor_labor_model_c4_u1': <String>[
    'CPLH strips out money entirely',
    'two things the manager cannot control',
    'labor % swings, CPLH holds',
  ],
  'jim_taylor_labor_model_c4_u2': <String>[
    'If you evaluate this manager on labor %, Week B is a crisis',
    'CPLH tells the truth: nothing changed on the operations side',
    'One measures management. One measures the business.',
  ],
  'jim_taylor_labor_model_c4_u3': <String>[
    'Long stays, many service touches, low turns',
    'Balanced volume and service',
    'Faster turns, simpler service',
    'Minimal table service, high throughput',
    'No universal correct CPLH',
    'Your target comes from your OPZ data',
  ],
  'jim_taylor_labor_model_c4_u4': <String>[
    'One location is simply more productive',
    'Because of how it\'s being run.',
    'No wage advantage exists',
  ],
  'jim_taylor_labor_model_c4_u5': <String>[
    'Labor % is a scoreboard. Not a strategy.',
    'It is not a staffing problem',
    'It is a productivity problem',
    'CPLH names it. Labor % never could.',
  ],
  'jim_taylor_labor_model_c5_u1': <String>[
    'Jim says this is the wrong input',
    'Revenue tells you nothing about how many people are walking in',
    'Cover count gives the right answer every time',
  ],
  'jim_taylor_labor_model_c5_u2': <String>[
    'Required Hours = Expected Covers / Target CPLH',
    'Forecast your covers from historical same-day data',
    'Build the shift from those hours - not from a revenue guess',
    'Stop scheduling to revenue',
    'You don\'t control what guests order. You control how many people you put on the floor.',
    'you can forecast how many guests walk through the door',
  ],
  'jim_taylor_labor_model_c5_u3': <String>[
    'Scheduled perfectly to demand',
    'Labor % can\'t tell you the difference',
    'Restaurant A did not schedule to covers with CPLH',
    'That overstaffing is the direct cause of their problem',
    'they forecasted their covers from history, applied their CPLH target, and scheduled the right hours',
  ],
  'jim_taylor_labor_model_c6_u0': <String>[
    'SPLH is the best metric to be used in the back of the house',
    'SPLH = Total Sales / Total Labor Hours',
    'Track this across weeks and you will see which shifts the kitchen is fully productive vs which ones drag',
    'A drop in SPLH with consistent covers means the kitchen is taking longer per ticket, remakes are climbing, or BOH was overstaffed for the volume',
  ],
  'jim_taylor_labor_model_c6_u1': <String>[
    'The kitchen produces food, not covers',
    'CPLH is harder to apply to BOH because ticket complexity varies',
    'every station\'s output ultimately converts to sales, so revenue per hour is the right lens',
    'CPLH for FOH. SPLH for BOH.',
    'They are measuring the same concept - productivity per labor hour',
  ],
  'jim_taylor_labor_model_c7_u0': <String>[
    'When CPLH and SPLH move in different directions, something specific happened',
    'Document this shift. Replicate it.',
    'PPA dropped. Upselling issue or rushed service.',
    'Volume problem, not an execution problem. Fix the forecast.',
    'Fewer covers AND less spend.',
    'Check external cause first - weather, event nearby, day of week anomaly.',
  ],
  'jim_taylor_labor_model_c7_u1': <String>[
    'This is not a team performance problem',
    'SPLH above target means the team executed well',
    'CPLH below target means the restaurant was slightly overstaffed for the actual volume',
    'The fix is in the forecast, not on the floor',
  ],
  'jim_taylor_labor_model_c8_u0': <String>[
    'calculated from your actual inputs, not borrowed from anywhere',
    'Theoretical labor cost = (Hours x Avg Wage) / (Covers x Avg Spend)',
    'the number your manager should be measured against',
    'Not a guess. Not a benchmark. Not last year.',
  ],
  'jim_taylor_labor_model_c8_u1': <String>[
    'if everything went perfectly',
    'right hours scheduled, right team deployed',
    'at your actual wage rates and actual PPA',
    'This is your floor',
    'The minimum achievable without compromising service',
  ],
  'jim_taylor_labor_model_c8_u3': <String>[
    'nearly twice her gap',
    'He had room. She didn\'t',
    'Theoretical labor shows you what is actually possible',
    'evaluating people against a number that was never built for their reality',
  ],
  'jim_taylor_labor_model_c9_u0': <String>[
    'build the data foundation that makes your theoretical labor target real',
    'Acquire your restaurant\'s realistic weekly labor percentage target',
    'Acquire your target CPLH and SPLH for your team and your concept',
    'without changing anything operationally yet',
    'building a picture of what your operation actually is',
  ],
  'jim_taylor_labor_model_c9_u1': <String>[
    'track five numbers across every daypart - lunch, dinner, late night',
    'CPLH - covers per FOH labor hour',
    'SPLH - sales per BOH labor hour',
    'Blended Wage - your actual wage mix across every role, every shift',
    'A strong dinner can mask a bleeding lunch',
    'see which shift is consistently off target',
  ],
  'jim_taylor_labor_model_c9_u2': <String>[
    'when three things are high together: CPLH, SPLH, and PPA',
    'good pacing, clean ticket times, table touches happening',
    'Those are the days you build your targets from',
    'CPLH is high - FOH is productive, right number of people for the covers',
    'SPLH is high - BOH is producing efficiently, kitchen not backed up or overstaffed',
    'PPA is high - guests are being attended to, upsells are happening',
  ],
  'jim_taylor_labor_model_c9_u3': <String>[
    'not looking for your best single day',
    'the range where your team was consistently comfortable and productive',
    'From that range you set your target CPLH and target SPLH',
    'the inputs that build your theoretical labor %',
  ],
  'jim_taylor_labor_model_c9_u4': <String>[
    'they didn\'t know why Wednesday worked',
    'Two good Wednesdays do not give you a CPLH target - they give you a false floor',
    'enough days to see both ends of what your operation actually does',
  ],
  'jim_taylor_labor_model_c9_u5': <String>[
    'A CPLH target built from too few days',
    'your best Wednesday disguised as a standard',
    'Track long enough to see the full range',
    'Your target lives somewhere inside it',
  ],
  'jim_taylor_labor_model_c9_u7': <String>[
    'Forecasted Covers / Target CPLH',
    'Forecasted Sales / Target SPLH (Forecasted Sales = Covers x PPA)',
    'FOH Hours x FOH Wage + BOH Hours x BOH Wage',
  ],
  'jim_taylor_labor_model_c9_u8': <String>[
    'Built from your covers, your PPA, your target CPLH, your target SPLH, your FOH and BOH wages',
    'Not borrowed from a benchmark. Not copied from another location',
    'you know immediately which side of the house to look at first',
  ],
  'jim_taylor_labor_model_c9_u9': <String>[
    'one for CPLH by daypart, one for SPLH by daypart',
    'The patterns in them are what your targets come from',
    'Daily covers, FOH hours, CPLH per shift by daypart',
    'Daily sales, BOH hours, SPLH per shift by daypart',
  ],
};
