// GENERATED by tool-side authoring, then verified against the live card
// bodies: every phrase below is a unique, whole-word, non-overlapping
// substring of THAT card's body. A phrase that does not match would simply
// fail to highlight, silently, so the check is not optional.
//
// Why per card: the old per-manual term lists were shared by every card in a
// manual, so which words lit up was an accident of word order rather than
// what the card taught. The operator's bar is that scanning only the
// highlights should still convey the card's information.
//
// A card with no entry here falls back to its manual's list, so a partial
// roll-out never leaves a card unhighlighted.


const Map<String, List<String>> kBarrioCardKeysTrainingMasteringMetrics =
    <String, List<String>>{
  'training_mastering_metrics_c0_u0': <String>[
    'Two underutilized metrics that can significantly enhance operational efficiency and profitability',
    'focus heavily on labor percentage to gauge financial health',
    'a cycle of reactive decision-making that ultimately hampers',
    'last-minute staffing cuts that may provide a temporary fix',
    'By focusing on cover count and average guest check, the narrative shifts toward a more proactive stance',
    'align labor with anticipated guest traffic and spending patterns',
  ],
  'training_mastering_metrics_c1_u0': <String>[
    'boost overall revenue without incurring additional guest acquisition costs',
    'Also known as Per Person Average (PPA)',
    'whether weekends bring in higher revenue per guest compared to weekdays',
    'week-by-week analysis can reveal spending trends throughout the month',
    'AGC by day part - differentiating between lunch and dinner',
    'analyzing AGC by individual servers can highlight performance variances',
  ],
  'training_mastering_metrics_c1_u1': <String>[
    'guests tend to spend significantly more on weekends',
    'tailor promotions or menu offerings to encourage higher spending on traditionally slower days',
    'servers consistently register higher AGC figures',
    'analyze their techniques and share best practices among the team',
    'A higher AGC is often an indication that guests are enjoying their experience',
    'opting to order appetizers, desserts, or indulging in a drink',
  ],
  'training_mastering_metrics_c2_u0': <String>[
    'Covers are the number of guests dining in a day',
    'assessing business volume, seating capacity, and operational efficiency',
    'identify patterns, such as peak dining times',
    'The more guests we serve, the higher our potential sales',
    'how guest volume correlates with spending patterns',
  ],
  'training_mastering_metrics_c2_u1': <String>[
    'determine the appropriate staffing levels necessary to execute smooth service',
    'adequate staffing during busy periods without overextending during slower times',
    'Every time staff enter the number of guests into the POS',
    'past cover counts on specific days, which aids in scheduling staff effectively',
    'data on average table turnover',
    'book reservations more accurately and maximize thier seating capacity',
  ],
  'training_mastering_metrics_c3_u0': <String>[
    'take the number of covers and divide it by the total front-of-house labor hours',
    'a productivity score known as covers per labor hour (CPLH)',
    'pinpoint if staffing levels align with service demands',
    'monitoring AGC alongside CPLH',
    'If AGC is declining while CPLH is on the rise, it raises a red flag: they might be understaffed',
    'the team is stretched too thin, it can lead to service quality that suffers',
  ],
  'training_mastering_metrics_c3_u1': <String>[
    'find the sweet spot to achieve the highest productivity score without negatively impacting guest satisfaction',
    'maximizing sales while ensuring staff are not overburdened',
    'quantifies a team\'s output but also empowers operators to make informed staffing decisions',
    'minimize waste and enhance profitability',
    'accommodate fluctuations in guest traffic, whether during peak rushes or quieter times',
  ],
  'training_mastering_metrics_c4_u0': <String>[
    'cover count undeniably influences a restaurant\'s overall sales',
    'largely beyond a server\'s control',
    'a performance metric that servers can actively manage',
    'the average amount each guest spends during their visit',
    'maintain a strong AGC by connecting with guests, anticipating their needs',
    'Every engagement presents an opportunity to elevate the check',
  ],
  'training_mastering_metrics_c5_u0': <String>[
    'hinges on genuine interactions and a thorough understanding of your offerings',
    'cornerstone of this process is being attentive to your tables',
    'making eye contact, listening actively, and truly being present',
    'create a natural segue for personalized recommendations',
    'nudging the guest towards an upscale choice',
    'mastering your menu knowledge and suggestive selling skills',
  ],
  'training_mastering_metrics_c5_u1': <String>[
    'well-versed in the ingredients, preparation methods, and unique flavors of each dish',
    'rave about a seasonal special or a house favorite',
    'intrigued and inclined to order more',
    'presenting options that complement their meal without coming off as pushy',
    'using open-ended questions, you can gauge their interests',
    'Building relationships and trust with your guests',
  ],
  'training_mastering_metrics_c6_u0': <String>[
    'Promotions and discounts can be an effective strategy to attract guests, but they must be carefully managed',
    'promotions are enticing without significantly undermining profit margins',
    'Being understaffed can hinder your team\'s ability to provide the exceptional service',
    'If servers are stretched thin, they may miss opportunities to engage with customers, upsell items',
    'being friendly and welcoming creates a positive atmosphere',
    'A smile and a warm greeting can go a long way',
  ],
  'training_mastering_metrics_c6_u1': <String>[
    'cleaning around guests or rushing them can create an uncomfortable atmosphere',
    'When you sweep, mop, put the chairs up around tables',
    'makes guests feel rushed and like they are an inconvenience',
    'deter guests from coming later in the evening in the future',
    'dropping potential future sales',
  ],
  'training_mastering_metrics_c7_u0': <String>[
    'surpassing their own Average Guest Check',
    'emphasis shifts from competition with coworkers to self-improvement',
    'Identifying these key behaviors allows servers to replicate their successes',
    'days when AGC falls short offer equally valuable learning opportunities',
    'small goals that are set and achieved cumulatively lead to significant, long-term progress',
    'tangible impact on their earnings',
  ],
};
