// GENERATED by tool-side authoring, then verified against the live card
// bodies: every phrase below is a unique, whole-word, non-overlapping
// substring of THAT card's body. A phrase that does not match would simply
// fail to highlight, silently, so the check is not optional.
//
// Why per card: the old per-manual term lists were shared by every card in a
// manual, so which words lit up was an accident of word order rather than
// what the card taught. The operator's bar is that scanning only the
// highlights should still convey the card's information.
//
// A card with no entry here falls back to its manual's list, so a partial
// roll-out never leaves a card unhighlighted.


const Map<String, List<String>> kBarrioCardKeysInterviewPlaybook =
    <String, List<String>>{
  'interview_playbook_c0_u0': <String>[
    'exciting but often stressful experience',
    'with the undeniable pressure of making the right choice',
    'Interviews provide just a snapshot of a candidate\'s skills and potential',
    'a thoughtful system of tailored questions that align with our core values',
    'transforms the interview into a meaningful exchange',
  ],
  'interview_playbook_c10_u1': <String>[
    'the difference between service and hospitality?',
    'What did the restaurant do differently than others?',
    'What made them great and what made them difficult?',
    'What do you need from me as your manager in that moment?',
    'food at the pass, a table that needs to be greeted, and a table waiting to pay',
    'you went above and beyond for a guest',
  ],
  'interview_playbook_c11_u1': <String>[
    'proud of that won\'t show up on a resume?',
    'Who is someone that you admire?',
    'had to follow strict guidelines or procedures',
    'How do you decide what to prioritize when you have multiple tasks?',
    'How do you stay focused and careful while maintaining efficiency?',
    'a coworker took their frustrations out on you?',
  ],
  'interview_playbook_c12_u1': <String>[
    'favourite station to work',
    'run out of the ingredients for a dish that has already been ordered',
    'motivate yourself when confronting challenging situations',
    'your process for an order with an allergy',
    'What do you need from me as your manager',
    'most influential chef you worked for',
  ],
  'interview_playbook_c13_u0': <String>[
    'crafting a vibrant culture that reflects our vision and values',
    'doesn\'t simply appear out of nowhere',
    'we design with intention and care',
    'the real magic happens as you nurture and develop their skills',
    'isn\'t just a happy accident',
    'thrives on purpose and passion',
  ],
  'interview_playbook_c1_u0': <String>[
    'hiring with intention',
    'often stem from unclear expectations and hasty decisions rather than a shortage of qualified candidates',
    'resonate with our core values, enhance our vibrant culture',
    'curious, resilient, coachable, and adaptable',
    'cultivating a passionate team that will help shape and elevate our brand',
  ],
  'interview_playbook_c1_u1': <String>[
    'How often they change jobs',
    'Call candidate for a quick chat or send professional email',
    'Conversation driven questions',
    'Core values. Emotional intelligence. Composure',
    'Use red/green flag method',
    'shine a spotlight on different traits at each stage',
  ],
  'interview_playbook_c2_u0': <String>[
    'essential to be thoroughly prepared',
    'Ask follow up questions to gain deeper insight',
    'Do not follow a script',
    'Have different people conduct different stages to minimize bias',
    'Use same set of questions to best evaluate candidates fairly',
    'Allow for silences to see the candidate\'s composure',
  ],
  'interview_playbook_c3_u0': <String>[
    'signals of long-term potential, not just their current skillset',
    'Skills can be taught, willingness cannot',
    'Change exposes character',
    'ability to take feedback is key for their development, showing their coachability',
    'warmth, showing a positive demeanor',
  ],
  'interview_playbook_c4_u0': <String>[
    'green flags like open communication and respect for boundaries',
    'red flags like manipulation and dishonesty',
    'steer clear of toxic situations',
    'feeling unsure about a candidate, it is a no',
    'great candidates do not make you question your instincts',
  ],
  'interview_playbook_c4_u1': <String>[
    'Real, specific stories',
    'Ownership over actions',
    'Shows curiosity about the business and team',
    'Open to being challenged',
    'Has self-regulation strategies and system for multi-tasking',
    'Sees opportunities not burdens',
  ],
  'interview_playbook_c4_u2': <String>[
    'Vague or rehearsed answers',
    'Places blame or gives excuses',
    'Focus on money, perks, or shortcuts',
    'Views others needs as an annoyance',
    'Lacks self-awareness',
    'Speaks poorly about others',
  ],
  'interview_playbook_c5_u1': <String>[
    'What do you look for in a good employer?',
    'What kind of environment brings out your best work?',
    'any questions about the position or the company?',
    'What is your availability?',
    'How many shifts are you looking for?',
  ],
  'interview_playbook_c6_u1': <String>[
    'your interest in coming to work with us?',
    'favourite quality about yourself?',
    'Which of our core values resonates the most with you?',
    'the last time you completely screwed something up',
    'known for one thing by your co-workers',
    'the hardest piece of feedback you have ever received?',
  ],
  'interview_playbook_c7_u1': <String>[
    'proud of that won\'t show up on a resume?',
    'Who is someone that you admire?',
    'your communication skills solved a conflict?',
    'a guest demands to be seated right away even though there is a one hour wait?',
    'A guest calls you over to complain about their experience',
  ],
  'interview_playbook_c8_u1': <String>[
    'proud of that won\'t show up on a resume?',
    'Who is someone that you admire?',
    'had to follow strict guidelines or procedures',
    'How do you decide what to prioritize when you have multiple tasks?',
    'you kept going even though you were overwhelmed',
    'A guest calls you over to complain about their experience',
  ],
  'interview_playbook_c9_u1': <String>[
    'a regular looks upset but they haven\'t complained',
    'What was the best dining experience you ever had?',
    'Everything is going wrong. What do you need from me as your manager',
    'What made them great and what made them difficult?',
    'your favourite classic cocktail?',
  ],
};
