// GENERATED RECIPE INGREDIENT DATA - regenerate, do not hand-edit.
//
// Source: lib/internal/barrio/content/training/training_recipes_content.dart
// Generator: tool/barrio_recipe_ingredients_generator.py
//
// Every `raw` below is lifted character-for-character out of the card
// body it is keyed to, so the reader and the calculator can never
// show two different numbers. test/barrio_recipe_ingredients_test.dart
// re-proves that tie against the live doc, and proves the parse covers
// every ingredient line with nothing silently dropped.
//
// `amount` is the part of the line that is the amount, sliced out of
// `raw` itself. Scaling rewrites the numbers inside it and leaves
// everything else alone, so a scaled line is spaced and worded the
// way the card spaced and worded it.
//
// A line with a `quantity` can be multiplied; a line without one has
// nothing to multiply and prints as written. `quantityHigh` is the
// second number of a range, and it scales alongside the first.
//
// `nameNumbers` is one entry per number written inside the ingredient
// itself, in the order it is written: the value it scales from, or
// null for a number that stays exactly as written (a percentage, or a
// digit inside a word). Absent when the name holds no number at all.

import 'barrio_recipe_models.dart';

/// Structured ingredient lines for the Recipes manual, keyed by the
/// `HandbookUnit` id of the card whose body carries them.
const Map<String, List<BarrioRecipeIngredient>> kBarrioRecipeIngredients =
    <String, List<BarrioRecipeIngredient>>{
  'training_recipes_c0_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '500mL Olive Oil',
      name: 'Olive Oil',
      amount: '500mL',
      quantity: 500,
      unit: 'mL',
    ),
    BarrioRecipeIngredient(
      raw: '1 Jar Aji Amarillo',
      name: 'Aji Amarillo',
      amount: '1 Jar',
      quantity: 1,
      unit: 'Jar',
    ),
    BarrioRecipeIngredient(
      raw: '50ml Water ( Add to jar and shake)',
      name: 'Water ( Add to jar and shake)',
      amount: '50ml',
      quantity: 50,
      unit: 'ml',
    ),
    BarrioRecipeIngredient(
      raw: '2 Stalks Celery',
      name: 'Celery',
      amount: '2 Stalks',
      quantity: 2,
      unit: 'Stalks',
    ),
    BarrioRecipeIngredient(
      raw: '4 Cloves of garlic',
      name: 'garlic',
      amount: '4 Cloves',
      quantity: 4,
      unit: 'Cloves',
    ),
    BarrioRecipeIngredient(
      raw: '¼ Red Onion',
      name: 'Red Onion',
      amount: '¼',
      quantity: 0.25,
    ),
    BarrioRecipeIngredient(
      raw: '10g Ginger',
      name: 'Ginger',
      amount: '10g',
      quantity: 10,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '4 Juiced Limes',
      name: 'Juiced Limes',
      amount: '4',
      quantity: 4,
    ),
    BarrioRecipeIngredient(
      raw: 'Salt TT',
      name: 'Salt TT',
    ),
  ],
  'training_recipes_c1_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '7lbs Roma Tomato',
      name: 'Roma Tomato',
      amount: '7lbs',
      quantity: 7,
      unit: 'lbs',
    ),
    BarrioRecipeIngredient(
      raw: '4lbs Yellow Onion',
      name: 'Yellow Onion',
      amount: '4lbs',
      quantity: 4,
      unit: 'lbs',
    ),
    BarrioRecipeIngredient(
      raw: '210g Chipotle Pepper',
      name: 'Chipotle Pepper',
      amount: '210g',
      quantity: 210,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '2 Jars Aji Amarillo',
      name: 'Aji Amarillo',
      amount: '2 Jars',
      quantity: 2,
      unit: 'Jars',
    ),
    BarrioRecipeIngredient(
      raw: '4 Bunches Cilantro',
      name: 'Cilantro',
      amount: '4 Bunches',
      quantity: 4,
      unit: 'Bunches',
    ),
    BarrioRecipeIngredient(
      raw: '2 Bunches Scallions',
      name: 'Scallions',
      amount: '2 Bunches',
      quantity: 2,
      unit: 'Bunches',
    ),
    BarrioRecipeIngredient(
      raw: '32g Garlic',
      name: 'Garlic',
      amount: '32g',
      quantity: 32,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '400mL Rice Wine Vin',
      name: 'Rice Wine Vin',
      amount: '400mL',
      quantity: 400,
      unit: 'mL',
    ),
    BarrioRecipeIngredient(
      raw: '800mL Lime Juice',
      name: 'Lime Juice',
      amount: '800mL',
      quantity: 800,
      unit: 'mL',
    ),
    BarrioRecipeIngredient(
      raw: '1L Canola Oil',
      name: 'Canola Oil',
      amount: '1L',
      quantity: 1,
      unit: 'L',
    ),
    BarrioRecipeIngredient(
      raw: '60g Salt',
      name: 'Salt',
      amount: '60g',
      quantity: 60,
      unit: 'g',
    ),
  ],
  'training_recipes_c2_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '10lbs Ground Beef',
      name: 'Ground Beef',
      amount: '10lbs',
      quantity: 10,
      unit: 'lbs',
    ),
    BarrioRecipeIngredient(
      raw: '1lb Yellow Onion Brunoise',
      name: 'Yellow Onion Brunoise',
      amount: '1lb',
      quantity: 1,
      unit: 'lb',
    ),
    BarrioRecipeIngredient(
      raw: '120g Garlic Minced',
      name: 'Garlic Minced',
      amount: '120g',
      quantity: 120,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '300g Chipotle Peppers,Cleaned, Small Dice',
      name: 'Chipotle Peppers,Cleaned, Small Dice',
      amount: '300g',
      quantity: 300,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '110g Kosher Salt',
      name: 'Kosher Salt',
      amount: '110g',
      quantity: 110,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '1 Bunch Thyme Minced',
      name: 'Thyme Minced',
      amount: '1 Bunch',
      quantity: 1,
      unit: 'Bunch',
    ),
    BarrioRecipeIngredient(
      raw: '½ Bunch Fresh Oregano Minced',
      name: 'Fresh Oregano Minced',
      amount: '½ Bunch',
      quantity: 0.5,
      unit: 'Bunch',
    ),
    BarrioRecipeIngredient(
      raw: '80g Sweet Paprika',
      name: 'Sweet Paprika',
      amount: '80g',
      quantity: 80,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '60g Black Pepper Ground',
      name: 'Black Pepper Ground',
      amount: '60g',
      quantity: 60,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '8 Whole Eggs',
      name: 'Whole Eggs',
      amount: '8',
      quantity: 8,
    ),
    BarrioRecipeIngredient(
      raw: '260g Breadcrumbs',
      name: 'Breadcrumbs',
      amount: '260g',
      quantity: 260,
      unit: 'g',
    ),
  ],
  'training_recipes_c3_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '8-10lbs of beets',
      name: 'beets',
      amount: '8-10lbs',
      quantity: 8,
      quantityHigh: 10,
      unit: 'lbs',
    ),
    BarrioRecipeIngredient(
      raw: '3L Water',
      name: 'Water',
      amount: '3L',
      quantity: 3,
      unit: 'L',
    ),
    BarrioRecipeIngredient(
      raw: '200mL Red Wine Vinegar',
      name: 'Red Wine Vinegar',
      amount: '200mL',
      quantity: 200,
      unit: 'mL',
    ),
    BarrioRecipeIngredient(
      raw: '70g Salt ( 1.75% weight of beets)',
      name: 'Salt ( 1.75% weight of beets)',
      amount: '70g',
      quantity: 70,
      unit: 'g',
      nameNumbers: <double?>[null],
    ),
  ],
  'training_recipes_c5_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '5850g Ground Beef',
      name: 'Ground Beef',
      amount: '5850g',
      quantity: 5850,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '2100g Yellow Onion Fine Dice',
      name: 'Yellow Onion Fine Dice',
      amount: '2100g',
      quantity: 2100,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '780g Bell Pepper Fine Dice',
      name: 'Bell Pepper Fine Dice',
      amount: '780g',
      quantity: 780,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '105g Green Onions ( Green top only)',
      name: 'Green Onions ( Green top only)',
      amount: '105g',
      quantity: 105,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '80g Ground Cumin',
      name: 'Ground Cumin',
      amount: '80g',
      quantity: 80,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '42g Paprika',
      name: 'Paprika',
      amount: '42g',
      quantity: 42,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '42g Cinnamon',
      name: 'Cinnamon',
      amount: '42g',
      quantity: 42,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: 'Salt TT',
      name: 'Salt TT',
    ),
  ],
  'training_recipes_c6_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '100g RWV',
      name: 'RWV',
      amount: '100g',
      quantity: 100,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '60g Garlic Paste/ Blitz Garlic',
      name: 'Garlic Paste/ Blitz Garlic',
      amount: '60g',
      quantity: 60,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '30g Tomato Paste',
      name: 'Tomato Paste',
      amount: '30g',
      quantity: 30,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '1 TSP Smoked Paprika',
      name: 'Smoked Paprika',
      amount: '1 TSP',
      quantity: 1,
      unit: 'TSP',
    ),
    BarrioRecipeIngredient(
      raw: '15g Cumin Ground',
      name: 'Cumin Ground',
      amount: '15g',
      quantity: 15,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '10g Oregano',
      name: 'Oregano',
      amount: '10g',
      quantity: 10,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '80g Oil',
      name: 'Oil',
      amount: '80g',
      quantity: 80,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '10g Salt',
      name: 'Salt',
      amount: '10g',
      quantity: 10,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '5g Pepper',
      name: 'Pepper',
      amount: '5g',
      quantity: 5,
      unit: 'g',
    ),
  ],
  'training_recipes_c7_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '60g Aji Amarillo',
      name: 'Aji Amarillo',
      amount: '60g',
      quantity: 60,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '540g Roasted Red Pepper',
      name: 'Roasted Red Pepper',
      amount: '540g',
      quantity: 540,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '250g Soy Sauce',
      name: 'Soy Sauce',
      amount: '250g',
      quantity: 250,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '200g Mirin',
      name: 'Mirin',
      amount: '200g',
      quantity: 200,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '100g Brown Sugar',
      name: 'Brown Sugar',
      amount: '100g',
      quantity: 100,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '80g Garlic Paste',
      name: 'Garlic Paste',
      amount: '80g',
      quantity: 80,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '50g Ginger Grated',
      name: 'Ginger Grated',
      amount: '50g',
      quantity: 50,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '120g Rice Vinegar',
      name: 'Rice Vinegar',
      amount: '120g',
      quantity: 120,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '100g Canola Oil',
      name: 'Canola Oil',
      amount: '100g',
      quantity: 100,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '20g Sesame Oil',
      name: 'Sesame Oil',
      amount: '20g',
      quantity: 20,
      unit: 'g',
    ),
  ],
  'training_recipes_c8_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '470g Corn Nuts',
      name: 'Corn Nuts',
      amount: '470g',
      quantity: 470,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '235 Pumpkin Seeds',
      name: 'Pumpkin Seeds',
      amount: '235',
      quantity: 235,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '180g Sunflower Seeds',
      name: 'Sunflower Seeds',
      amount: '180g',
      quantity: 180,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '180g White/Black Sesame Seed (90g each)',
      name: 'White/Black Sesame Seed (90g each)',
      amount: '180g',
      quantity: 180,
      unit: 'g',
      nameNumbers: <double?>[90],
    ),
    BarrioRecipeIngredient(
      raw: '35g Maldon Salt',
      name: 'Maldon Salt',
      amount: '35g',
      quantity: 35,
      unit: 'g',
    ),
  ],
  'training_recipes_c9_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '500g Onion Scraps ( Skins,Ends, Outer Layers)',
      name: 'Onion Scraps ( Skins,Ends, Outer Layers)',
      amount: '500g',
      quantity: 500,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '500mL Canola Oil',
      name: 'Canola Oil',
      amount: '500mL',
      quantity: 500,
      unit: 'mL',
    ),
  ],
  'training_recipes_c10_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '400g Aji Panca',
      name: 'Aji Panca',
      amount: '400g',
      quantity: 400,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '830g Water',
      name: 'Water',
      amount: '830g',
      quantity: 830,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '930g Mango Chunks',
      name: 'Mango Chunks',
      amount: '930g',
      quantity: 930,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '400g Lime Juice',
      name: 'Lime Juice',
      amount: '400g',
      quantity: 400,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '400g Soy Sauce',
      name: 'Soy Sauce',
      amount: '400g',
      quantity: 400,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '465g Brown Sugar',
      name: 'Brown Sugar',
      amount: '465g',
      quantity: 465,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '400g Garlic',
      name: 'Garlic',
      amount: '400g',
      quantity: 400,
      unit: 'g',
    ),
  ],
  'training_recipes_c11_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '60g Canola Oil',
      name: 'Canola Oil',
      amount: '60g',
      quantity: 60,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '10g Sesame Oil',
      name: 'Sesame Oil',
      amount: '10g',
      quantity: 10,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '60g Ginger ( Sliced into coins)',
      name: 'Ginger ( Sliced into coins)',
      amount: '60g',
      quantity: 60,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '4 piece Star Anise',
      name: 'Star Anise',
      amount: '4 piece',
      quantity: 4,
      unit: 'piece',
    ),
    BarrioRecipeIngredient(
      raw: '4g Salt',
      name: 'Salt',
      amount: '4g',
      quantity: 4,
      unit: 'g',
    ),
  ],
  'training_recipes_c12_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '12lbs Skinless Chicken Thighs',
      name: 'Skinless Chicken Thighs',
      amount: '12lbs',
      quantity: 12,
      unit: 'lbs',
    ),
    BarrioRecipeIngredient(
      raw: '1814g Tomato Sauce',
      name: 'Tomato Sauce',
      amount: '1814g',
      quantity: 1814,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '1 Whole Can Chipotle Pepper in Adobo Sauce',
      name: 'Whole Can Chipotle Pepper in Adobo Sauce',
      amount: '1',
      quantity: 1,
    ),
    BarrioRecipeIngredient(
      raw: '130g Cup Tomato Paste',
      name: 'Cup Tomato Paste',
      amount: '130g',
      quantity: 130,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '120g Apple Cider Vinegar',
      name: 'Apple Cider Vinegar',
      amount: '120g',
      quantity: 120,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '10g Mexican Oregano',
      name: 'Mexican Oregano',
      amount: '10g',
      quantity: 10,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '6g Ground Cumin',
      name: 'Ground Cumin',
      amount: '6g',
      quantity: 6,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '10g Garlic Powder',
      name: 'Garlic Powder',
      amount: '10g',
      quantity: 10,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '480g Chicken Stock',
      name: 'Chicken Stock',
      amount: '480g',
      quantity: 480,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '1360g White Onion Thinly Sliced',
      name: 'White Onion Thinly Sliced',
      amount: '1360g',
      quantity: 1360,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '65g Garlic Minced',
      name: 'Garlic Minced',
      amount: '65g',
      quantity: 65,
      unit: 'g',
    ),
  ],
  'training_recipes_c13_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '11lbs Potatoes, unpeeled ( washed and dried)',
      name: 'Potatoes, unpeeled ( washed and dried)',
      amount: '11lbs',
      quantity: 11,
      unit: 'lbs',
    ),
    BarrioRecipeIngredient(
      raw: '120mL water split between pans',
      name: 'water split between pans',
      amount: '120mL',
      quantity: 120,
      unit: 'mL',
    ),
  ],
  'training_recipes_c14_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '3200g Mayo',
      name: 'Mayo',
      amount: '3200g',
      quantity: 3200,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '200g Chipotle (One 7oz Can)',
      name: 'Chipotle (One 7oz Can)',
      amount: '200g',
      quantity: 200,
      unit: 'g',
      nameNumbers: <double?>[7],
    ),
    BarrioRecipeIngredient(
      raw: '120g Lime Juice',
      name: 'Lime Juice',
      amount: '120g',
      quantity: 120,
      unit: 'g',
    ),
  ],
  'training_recipes_c15_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '1400g Ketchup',
      name: 'Ketchup',
      amount: '1400g',
      quantity: 1400,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '500g Clamato',
      name: 'Clamato',
      amount: '500g',
      quantity: 500,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '385g Orange Juice',
      name: 'Orange Juice',
      amount: '385g',
      quantity: 385,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '318g Lime Juice',
      name: 'Lime Juice',
      amount: '318g',
      quantity: 318,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '234g Jarritos Mandarina',
      name: 'Jarritos Mandarina',
      amount: '234g',
      quantity: 234,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '80g Valentina',
      name: 'Valentina',
      amount: '80g',
      quantity: 80,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '50g Garlic ( Microplaned)',
      name: 'Garlic ( Microplaned)',
      amount: '50g',
      quantity: 50,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '45g Worcestershire Sauce',
      name: 'Worcestershire Sauce',
      amount: '45g',
      quantity: 45,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '15g Salt',
      name: 'Salt',
      amount: '15g',
      quantity: 15,
      unit: 'g',
    ),
  ],
  'training_recipes_c16_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '6oz Cod , Bite sized cubes',
      name: 'Cod , Bite sized cubes',
      amount: '6oz',
      quantity: 6,
      unit: 'oz',
    ),
    BarrioRecipeIngredient(
      raw: '½ Cup cornstarch seasoned with salt',
      name: 'cornstarch seasoned with salt',
      amount: '½ Cup',
      quantity: 0.5,
      unit: 'Cup',
    ),
    BarrioRecipeIngredient(
      raw: '1 cup slaw',
      name: 'slaw',
      amount: '1 cup',
      quantity: 1,
      unit: 'cup',
    ),
    BarrioRecipeIngredient(
      raw: '2 Tortillas',
      name: 'Tortillas',
      amount: '2',
      quantity: 2,
    ),
  ],
  'training_recipes_c17_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '750mL Mayo',
      name: 'Mayo',
      amount: '750mL',
      quantity: 750,
      unit: 'mL',
    ),
    BarrioRecipeIngredient(
      raw: '200ml Sweet Chile Sauce',
      name: 'Sweet Chile Sauce',
      amount: '200ml',
      quantity: 200,
      unit: 'ml',
    ),
    BarrioRecipeIngredient(
      raw: '50mL Aji Sauce',
      name: 'Aji Sauce',
      amount: '50mL',
      quantity: 50,
      unit: 'mL',
    ),
    BarrioRecipeIngredient(
      raw: '5g Salt',
      name: 'Salt',
      amount: '5g',
      quantity: 5,
      unit: 'g',
    ),
  ],
  'training_recipes_c18_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '700g Cabbage',
      name: 'Cabbage',
      amount: '700g',
      quantity: 700,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '150g Carrots',
      name: 'Carrots',
      amount: '150g',
      quantity: 150,
      unit: 'g',
    ),
  ],
  'training_recipes_c19_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '15 Avocados',
      name: 'Avocados',
      amount: '15',
      quantity: 15,
    ),
    BarrioRecipeIngredient(
      raw: '500mL Lime Juice',
      name: 'Lime Juice',
      amount: '500mL',
      quantity: 500,
      unit: 'mL',
    ),
    BarrioRecipeIngredient(
      raw: '5 jalapeños (Deseeded)',
      name: 'jalapeños (Deseeded)',
      amount: '5',
      quantity: 5,
    ),
    BarrioRecipeIngredient(
      raw: '1/4 Bunch cilantro',
      name: 'cilantro',
      amount: '1/4 Bunch',
      quantity: 0.25,
      unit: 'Bunch',
    ),
    BarrioRecipeIngredient(
      raw: '1 Large Red Onion Small Dice',
      name: 'Large Red Onion Small Dice',
      amount: '1',
      quantity: 1,
    ),
    BarrioRecipeIngredient(
      raw: 'L5S TT',
      name: 'L5S TT',
      nameNumbers: <double?>[null],
    ),
    BarrioRecipeIngredient(
      raw: 'Salt TT',
      name: 'Salt TT',
    ),
  ],
  'training_recipes_c21_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '57g Garlic Cloves ( Crushed)',
      name: 'Garlic Cloves ( Crushed)',
      amount: '57g',
      quantity: 57,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '85g Cilantro Stems',
      name: 'Cilantro Stems',
      amount: '85g',
      quantity: 85,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '3 piece Bay Leaves',
      name: 'Bay Leaves',
      amount: '3 piece',
      quantity: 3,
      unit: 'piece',
    ),
    BarrioRecipeIngredient(
      raw: '70g Ginger ( Skin on, quartered then thinly sliced)',
      name: 'Ginger ( Skin on, quartered then thinly sliced)',
      amount: '70g',
      quantity: 70,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '28g Sweet Paprika',
      name: 'Sweet Paprika',
      amount: '28g',
      quantity: 28,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '397mL Soy Sauce',
      name: 'Soy Sauce',
      amount: '397mL',
      quantity: 397,
      unit: 'mL',
    ),
    BarrioRecipeIngredient(
      raw: '65g Aji Panca',
      name: 'Aji Panca',
      amount: '65g',
      quantity: 65,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '7g Mexican Oregano',
      name: 'Mexican Oregano',
      amount: '7g',
      quantity: 7,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '28mL Rice Vinegar',
      name: 'Rice Vinegar',
      amount: '28mL',
      quantity: 28,
      unit: 'mL',
    ),
  ],
  'training_recipes_c22_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '12 Eggs',
      name: 'Eggs',
      amount: '12',
      quantity: 12,
    ),
  ],
  'training_recipes_c23_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '500mL Mirin',
      name: 'Mirin',
      amount: '500mL',
      quantity: 500,
      unit: 'mL',
    ),
    BarrioRecipeIngredient(
      raw: '500mL Apple Cider Vinegar',
      name: 'Apple Cider Vinegar',
      amount: '500mL',
      quantity: 500,
      unit: 'mL',
    ),
    BarrioRecipeIngredient(
      raw: '591mL Rice Wine Vinegar ( 1 Bottle)',
      name: 'Rice Wine Vinegar ( 1 Bottle)',
      amount: '591mL',
      quantity: 591,
      unit: 'mL',
      nameNumbers: <double?>[1],
    ),
    BarrioRecipeIngredient(
      raw: '125mL Soy Sauce',
      name: 'Soy Sauce',
      amount: '125mL',
      quantity: 125,
      unit: 'mL',
    ),
    BarrioRecipeIngredient(
      raw: 'The Peel of One Orange',
      name: 'The Peel of One Orange',
    ),
    BarrioRecipeIngredient(
      raw: '2tsp Chili Flakes',
      name: 'Chili Flakes',
      amount: '2tsp',
      quantity: 2,
      unit: 'tsp',
    ),
    BarrioRecipeIngredient(
      raw: '3 tbsp White Sugar',
      name: 'White Sugar',
      amount: '3 tbsp',
      quantity: 3,
      unit: 'tbsp',
    ),
  ],
  'training_recipes_c24_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '5lbs Poblano Pepper',
      name: 'Poblano Pepper',
      amount: '5lbs',
      quantity: 5,
      unit: 'lbs',
    ),
    BarrioRecipeIngredient(
      raw: '1134g Sour Cream',
      name: 'Sour Cream',
      amount: '1134g',
      quantity: 1134,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '12 Bunches Cilantro',
      name: 'Cilantro',
      amount: '12 Bunches',
      quantity: 12,
      unit: 'Bunches',
    ),
    BarrioRecipeIngredient(
      raw: '45g Paprika',
      name: 'Paprika',
      amount: '45g',
      quantity: 45,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '23 Limes (Juiced)',
      name: 'Limes (Juiced)',
      amount: '23',
      quantity: 23,
    ),
    BarrioRecipeIngredient(
      raw: '454g Garlic',
      name: 'Garlic',
      amount: '454g',
      quantity: 454,
      unit: 'g',
    ),
  ],
  'training_recipes_c25_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '80g Aji Panca',
      name: 'Aji Panca',
      amount: '80g',
      quantity: 80,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '400g Roasted Red Pepper',
      name: 'Roasted Red Pepper',
      amount: '400g',
      quantity: 400,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '70g Garlic',
      name: 'Garlic',
      amount: '70g',
      quantity: 70,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '14g Black Pepper',
      name: 'Black Pepper',
      amount: '14g',
      quantity: 14,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '15g Cumin',
      name: 'Cumin',
      amount: '15g',
      quantity: 15,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '6g Mexican Oregano',
      name: 'Mexican Oregano',
      amount: '6g',
      quantity: 6,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '48g Kosher Salt',
      name: 'Kosher Salt',
      amount: '48g',
      quantity: 48,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '478g Red Wine Vinegar',
      name: 'Red Wine Vinegar',
      amount: '478g',
      quantity: 478,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '654 Canola Oil',
      name: 'Canola Oil',
      amount: '654',
      quantity: 654,
      unit: 'g',
    ),
  ],
  'training_recipes_c26_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '2.5kg Pork Belly ( Half a Slab)',
      name: 'Pork Belly ( Half a Slab)',
      amount: '2.5kg',
      quantity: 2.5,
      unit: 'kg',
    ),
    BarrioRecipeIngredient(
      raw: '250g Soy Sauce',
      name: 'Soy Sauce',
      amount: '250g',
      quantity: 250,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '200g Orange Juice',
      name: 'Orange Juice',
      amount: '200g',
      quantity: 200,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '50g Ginger',
      name: 'Ginger',
      amount: '50g',
      quantity: 50,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '60g Green Onion',
      name: 'Green Onion',
      amount: '60g',
      quantity: 60,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '30g Sesame Oil',
      name: 'Sesame Oil',
      amount: '30g',
      quantity: 30,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '10g Black Peppercorn',
      name: 'Black Peppercorn',
      amount: '10g',
      quantity: 10,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '8 piece Star Anise',
      name: 'Star Anise',
      amount: '8 piece',
      quantity: 8,
      unit: 'piece',
    ),
    BarrioRecipeIngredient(
      raw: '6 piece Cinnamon Sticks',
      name: 'Cinnamon Sticks',
      amount: '6 piece',
      quantity: 6,
      unit: 'piece',
    ),
    BarrioRecipeIngredient(
      raw: '1 Bunch Thyme',
      name: 'Thyme',
      amount: '1 Bunch',
      quantity: 1,
      unit: 'Bunch',
    ),
  ],
  'training_recipes_c27_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '750g Pumpkin Seeds',
      name: 'Pumpkin Seeds',
      amount: '750g',
      quantity: 750,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '210g Unhulled Seeds',
      name: 'Unhulled Seeds',
      amount: '210g',
      quantity: 210,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '9-10 Roma Tomatoes',
      name: 'Roma Tomatoes',
      amount: '9-10',
      quantity: 9,
      quantityHigh: 10,
    ),
    BarrioRecipeIngredient(
      raw: '225g White Onion',
      name: 'White Onion',
      amount: '225g',
      quantity: 225,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '135g Lime Juice',
      name: 'Lime Juice',
      amount: '135g',
      quantity: 135,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '90g Orange Juice',
      name: 'Orange Juice',
      amount: '90g',
      quantity: 90,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '42g Cilantro',
      name: 'Cilantro',
      amount: '42g',
      quantity: 42,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '(30g) 4-5 Habanero Peppers (deseeded and deribbed)',
      name: '(30g) 4-5 Habanero Peppers (deseeded and deribbed)',
      nameNumbers: <double?>[30, 4, 5],
    ),
    BarrioRecipeIngredient(
      raw: '75g Garlic',
      name: 'Garlic',
      amount: '75g',
      quantity: 75,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '30g Salt',
      name: 'Salt',
      amount: '30g',
      quantity: 30,
      unit: 'g',
    ),
  ],
  'training_recipes_c28_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '420g Pumpking Seed',
      name: 'Pumpking Seed',
      amount: '420g',
      quantity: 420,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '84g Sesame Seeds',
      name: 'Sesame Seeds',
      amount: '84g',
      quantity: 84,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '42g Corriander Seed',
      name: 'Corriander Seed',
      amount: '42g',
      quantity: 42,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '21g Cumin Seed',
      name: 'Cumin Seed',
      amount: '21g',
      quantity: 21,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '13g Chili Flake',
      name: 'Chili Flake',
      amount: '13g',
      quantity: 13,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '21g Maldon Salt',
      name: 'Maldon Salt',
      amount: '21g',
      quantity: 21,
      unit: 'g',
    ),
  ],
  'training_recipes_c29_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '6oz Mushrooms',
      name: 'Mushrooms',
      amount: '6oz',
      quantity: 6,
      unit: 'oz',
    ),
    BarrioRecipeIngredient(
      raw: '150g Mozzarella Cheese',
      name: 'Mozzarella Cheese',
      amount: '150g',
      quantity: 150,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '3 Corn Tortillas',
      name: 'Corn Tortillas',
      amount: '3',
      quantity: 3,
    ),
  ],
  'training_recipes_c30_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '12 Tomatoes',
      name: 'Tomatoes',
      amount: '12',
      quantity: 12,
    ),
    BarrioRecipeIngredient(
      raw: '3 Banana Peppers Small Dice',
      name: 'Banana Peppers Small Dice',
      amount: '3',
      quantity: 3,
    ),
    BarrioRecipeIngredient(
      raw: 'One Large Onion Red Small Dice',
      name: 'One Large Onion Red Small Dice',
    ),
    BarrioRecipeIngredient(
      raw: 'Lime 300mL',
      name: 'Lime',
      amount: '300mL',
      quantity: 300,
      unit: 'mL',
    ),
    BarrioRecipeIngredient(
      raw: 'Salt TT',
      name: 'Salt TT',
    ),
    BarrioRecipeIngredient(
      raw: 'L5S TT',
      name: 'L5S TT',
      nameNumbers: <double?>[null],
    ),
    BarrioRecipeIngredient(
      raw: '¼ Bunch Cilantro',
      name: 'Cilantro',
      amount: '¼ Bunch',
      quantity: 0.25,
      unit: 'Bunch',
    ),
  ],
  'training_recipes_c31_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '2kg-2.5kg Shrimp Shells',
      name: 'Shrimp Shells',
      amount: '2kg-2.5kg',
      quantity: 2,
      quantityHigh: 2.5,
      unit: 'kg',
    ),
    BarrioRecipeIngredient(
      raw: '7L Water',
      name: 'Water',
      amount: '7L',
      quantity: 7,
      unit: 'L',
    ),
    BarrioRecipeIngredient(
      raw: '670g Tomato Quartered',
      name: 'Tomato Quartered',
      amount: '670g',
      quantity: 670,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '335g White Onion (Large Dice)',
      name: 'White Onion (Large Dice)',
      amount: '335g',
      quantity: 335,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '150g Celery ( Large Dice)',
      name: 'Celery ( Large Dice)',
      amount: '150g',
      quantity: 150,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '170g Cilantro Stems',
      name: 'Cilantro Stems',
      amount: '170g',
      quantity: 170,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '120g Salt',
      name: 'Salt',
      amount: '120g',
      quantity: 120,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '50g Garlic Cloves',
      name: 'Garlic Cloves',
      amount: '50g',
      quantity: 50,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '4g Black Peppercorn',
      name: 'Black Peppercorn',
      amount: '4g',
      quantity: 4,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '1g Coriander Seeds',
      name: 'Coriander Seeds',
      amount: '1g',
      quantity: 1,
      unit: 'g',
    ),
    BarrioRecipeIngredient(
      raw: '8 Bay Leaves',
      name: 'Bay Leaves',
      amount: '8',
      quantity: 8,
    ),
  ],
  'training_recipes_c32_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '2 Bags Yellow Corn Tortilla',
      name: 'Yellow Corn Tortilla',
      amount: '2 Bags',
      quantity: 2,
      unit: 'Bags',
    ),
  ],
};
