// GENERATED RECIPE INGREDIENT DATA - regenerate, do not hand-edit.
//
// Source: lib/internal/barrio/content/training/training_recipes_content.dart
// Generator: tool/barrio_recipe_ingredients_generator.py
//
// Every `raw` below is lifted character-for-character out of the card
// body it is keyed to, so the reader and a calculator can never show
// two different numbers. test/barrio_recipe_ingredients_test.dart
// re-proves that tie against the live doc, and proves the parse covers
// every ingredient line with nothing silently dropped.
//
// `scalable` is the whole point: only a single quantity in a unit of
// mass or volume may be multiplied. Container counts, whole-item
// counts, bare numbers with no unit, ranges, and lines with no number
// at all are held back with the reason why, and a calculator carries
// them through unchanged. The rule and its five reasons are stated
// once, in the generator.

import 'barrio_recipe_models.dart';

/// Structured ingredient lines for the Recipes manual, keyed by the
/// `HandbookUnit` id of the card whose body carries them.
const Map<String, List<BarrioRecipeIngredient>> kBarrioRecipeIngredients =
    <String, List<BarrioRecipeIngredient>>{
  'training_recipes_c0_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '500mL Olive Oil',
      name: 'Olive Oil',
      quantity: 500,
      unit: 'mL',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '1 Jar Aji Amarillo',
      name: 'Aji Amarillo',
      quantity: 1,
      unit: 'Jar',
      scalable: false,
      hold: BarrioIngredientHold.containerCount,
    ),
    BarrioRecipeIngredient(
      raw: '50ml Water ( Add to jar and shake)',
      name: 'Water ( Add to jar and shake)',
      quantity: 50,
      unit: 'ml',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '2 Stalks Celery',
      name: 'Celery',
      quantity: 2,
      unit: 'Stalks',
      scalable: false,
      hold: BarrioIngredientHold.wholeItemCount,
    ),
    BarrioRecipeIngredient(
      raw: '4 Cloves of garlic',
      name: 'garlic',
      quantity: 4,
      unit: 'Cloves',
      scalable: false,
      hold: BarrioIngredientHold.wholeItemCount,
    ),
    BarrioRecipeIngredient(
      raw: '¼ Red Onion',
      name: 'Red Onion',
      quantity: 0.25,
      scalable: false,
      hold: BarrioIngredientHold.noUnit,
    ),
    BarrioRecipeIngredient(
      raw: '10g Ginger',
      name: 'Ginger',
      quantity: 10,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '4 Juiced Limes',
      name: 'Juiced Limes',
      quantity: 4,
      scalable: false,
      hold: BarrioIngredientHold.noUnit,
    ),
    BarrioRecipeIngredient(
      raw: 'Salt TT',
      name: 'Salt TT',
      scalable: false,
      hold: BarrioIngredientHold.noQuantity,
    ),
  ],
  'training_recipes_c1_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '7lbs Roma Tomato',
      name: 'Roma Tomato',
      quantity: 7,
      unit: 'lbs',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '4lbs Yellow Onion',
      name: 'Yellow Onion',
      quantity: 4,
      unit: 'lbs',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '210g Chipotle Pepper',
      name: 'Chipotle Pepper',
      quantity: 210,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '2 Jars Aji Amarillo',
      name: 'Aji Amarillo',
      quantity: 2,
      unit: 'Jars',
      scalable: false,
      hold: BarrioIngredientHold.containerCount,
    ),
    BarrioRecipeIngredient(
      raw: '4 Bunches Cilantro',
      name: 'Cilantro',
      quantity: 4,
      unit: 'Bunches',
      scalable: false,
      hold: BarrioIngredientHold.wholeItemCount,
    ),
    BarrioRecipeIngredient(
      raw: '2 Bunches Scallions',
      name: 'Scallions',
      quantity: 2,
      unit: 'Bunches',
      scalable: false,
      hold: BarrioIngredientHold.wholeItemCount,
    ),
    BarrioRecipeIngredient(
      raw: '32g Garlic',
      name: 'Garlic',
      quantity: 32,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '400mL Rice Wine Vin',
      name: 'Rice Wine Vin',
      quantity: 400,
      unit: 'mL',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '800mL Lime Juice',
      name: 'Lime Juice',
      quantity: 800,
      unit: 'mL',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '1L Canola Oil',
      name: 'Canola Oil',
      quantity: 1,
      unit: 'L',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '60g Salt',
      name: 'Salt',
      quantity: 60,
      unit: 'g',
      scalable: true,
    ),
  ],
  'training_recipes_c2_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '10lbs Ground Beef',
      name: 'Ground Beef',
      quantity: 10,
      unit: 'lbs',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '1lb Yellow Onion Brunoise',
      name: 'Yellow Onion Brunoise',
      quantity: 1,
      unit: 'lb',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '120g Garlic Minced',
      name: 'Garlic Minced',
      quantity: 120,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '300g Chipotle Peppers,Cleaned, Small Dice',
      name: 'Chipotle Peppers,Cleaned, Small Dice',
      quantity: 300,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '110g Kosher Salt',
      name: 'Kosher Salt',
      quantity: 110,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '1 Bunch Thyme Minced',
      name: 'Thyme Minced',
      quantity: 1,
      unit: 'Bunch',
      scalable: false,
      hold: BarrioIngredientHold.wholeItemCount,
    ),
    BarrioRecipeIngredient(
      raw: '½ Bunch Fresh Oregano Minced',
      name: 'Fresh Oregano Minced',
      quantity: 0.5,
      unit: 'Bunch',
      scalable: false,
      hold: BarrioIngredientHold.wholeItemCount,
    ),
    BarrioRecipeIngredient(
      raw: '80g Sweet Paprika',
      name: 'Sweet Paprika',
      quantity: 80,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '60g Black Pepper Ground',
      name: 'Black Pepper Ground',
      quantity: 60,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '8 Whole Eggs',
      name: 'Whole Eggs',
      quantity: 8,
      scalable: false,
      hold: BarrioIngredientHold.noUnit,
    ),
    BarrioRecipeIngredient(
      raw: '260g Breadcrumbs',
      name: 'Breadcrumbs',
      quantity: 260,
      unit: 'g',
      scalable: true,
    ),
  ],
  'training_recipes_c3_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '8-10lbs of beets',
      name: 'beets',
      quantity: 8,
      unit: 'lbs',
      scalable: false,
      hold: BarrioIngredientHold.range,
    ),
    BarrioRecipeIngredient(
      raw: '3L Water',
      name: 'Water',
      quantity: 3,
      unit: 'L',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '200mL Red Wine Vinegar',
      name: 'Red Wine Vinegar',
      quantity: 200,
      unit: 'mL',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '70g Salt ( 1.75% weight of beets)',
      name: 'Salt ( 1.75% weight of beets)',
      quantity: 70,
      unit: 'g',
      scalable: true,
    ),
  ],
  'training_recipes_c5_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '5850g Ground Beef',
      name: 'Ground Beef',
      quantity: 5850,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '2100g Yellow Onion Fine Dice',
      name: 'Yellow Onion Fine Dice',
      quantity: 2100,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '780g Bell Pepper Fine Dice',
      name: 'Bell Pepper Fine Dice',
      quantity: 780,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '105g Green Onions ( Green top only)',
      name: 'Green Onions ( Green top only)',
      quantity: 105,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '80g Ground Cumin',
      name: 'Ground Cumin',
      quantity: 80,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '42g Paprika',
      name: 'Paprika',
      quantity: 42,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '42g Cinnamon',
      name: 'Cinnamon',
      quantity: 42,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: 'Salt TT',
      name: 'Salt TT',
      scalable: false,
      hold: BarrioIngredientHold.noQuantity,
    ),
  ],
  'training_recipes_c6_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '100g RWV',
      name: 'RWV',
      quantity: 100,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '60g Garlic Paste/ Blitz Garlic',
      name: 'Garlic Paste/ Blitz Garlic',
      quantity: 60,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '30g Tomato Paste',
      name: 'Tomato Paste',
      quantity: 30,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '1 TSP Smoked Paprika',
      name: 'Smoked Paprika',
      quantity: 1,
      unit: 'TSP',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '15g Cumin Ground',
      name: 'Cumin Ground',
      quantity: 15,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '10g Oregano',
      name: 'Oregano',
      quantity: 10,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '80g Oil',
      name: 'Oil',
      quantity: 80,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '10g Salt',
      name: 'Salt',
      quantity: 10,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '5g Pepper',
      name: 'Pepper',
      quantity: 5,
      unit: 'g',
      scalable: true,
    ),
  ],
  'training_recipes_c7_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '60g Aji Amarillo',
      name: 'Aji Amarillo',
      quantity: 60,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '540g Roasted Red Pepper',
      name: 'Roasted Red Pepper',
      quantity: 540,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '250g Soy Sauce',
      name: 'Soy Sauce',
      quantity: 250,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '200g Mirin',
      name: 'Mirin',
      quantity: 200,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '100g Brown Sugar',
      name: 'Brown Sugar',
      quantity: 100,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '80g Garlic Paste',
      name: 'Garlic Paste',
      quantity: 80,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '50g Ginger Grated',
      name: 'Ginger Grated',
      quantity: 50,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '120g Rice Vinegar',
      name: 'Rice Vinegar',
      quantity: 120,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '100g Canola Oil',
      name: 'Canola Oil',
      quantity: 100,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '20g Sesame Oil',
      name: 'Sesame Oil',
      quantity: 20,
      unit: 'g',
      scalable: true,
    ),
  ],
  'training_recipes_c8_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '470g Corn Nuts',
      name: 'Corn Nuts',
      quantity: 470,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '235 Pumpkin Seeds',
      name: 'Pumpkin Seeds',
      quantity: 235,
      scalable: false,
      hold: BarrioIngredientHold.noUnit,
    ),
    BarrioRecipeIngredient(
      raw: '180g Sunflower Seeds',
      name: 'Sunflower Seeds',
      quantity: 180,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '180g White/Black Sesame Seed (90g each)',
      name: 'White/Black Sesame Seed (90g each)',
      quantity: 180,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '35g Maldon Salt',
      name: 'Maldon Salt',
      quantity: 35,
      unit: 'g',
      scalable: true,
    ),
  ],
  'training_recipes_c9_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '500g Onion Scraps ( Skins,Ends, Outer Layers)',
      name: 'Onion Scraps ( Skins,Ends, Outer Layers)',
      quantity: 500,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '500mL Canola Oil',
      name: 'Canola Oil',
      quantity: 500,
      unit: 'mL',
      scalable: true,
    ),
  ],
  'training_recipes_c10_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '400g Aji Panca',
      name: 'Aji Panca',
      quantity: 400,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '830g Water',
      name: 'Water',
      quantity: 830,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '930g Mango Chunks',
      name: 'Mango Chunks',
      quantity: 930,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '400g Lime Juice',
      name: 'Lime Juice',
      quantity: 400,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '400g Soy Sauce',
      name: 'Soy Sauce',
      quantity: 400,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '465g Brown Sugar',
      name: 'Brown Sugar',
      quantity: 465,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '400g Garlic',
      name: 'Garlic',
      quantity: 400,
      unit: 'g',
      scalable: true,
    ),
  ],
  'training_recipes_c11_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '60g Canola Oil',
      name: 'Canola Oil',
      quantity: 60,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '10g Sesame Oil',
      name: 'Sesame Oil',
      quantity: 10,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '60g Ginger ( Sliced into coins)',
      name: 'Ginger ( Sliced into coins)',
      quantity: 60,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '4 piece Star Anise',
      name: 'Star Anise',
      quantity: 4,
      unit: 'piece',
      scalable: false,
      hold: BarrioIngredientHold.wholeItemCount,
    ),
    BarrioRecipeIngredient(
      raw: '4g Salt',
      name: 'Salt',
      quantity: 4,
      unit: 'g',
      scalable: true,
    ),
  ],
  'training_recipes_c12_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '12lbs Skinless Chicken Thighs',
      name: 'Skinless Chicken Thighs',
      quantity: 12,
      unit: 'lbs',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '1814g Tomato Sauce',
      name: 'Tomato Sauce',
      quantity: 1814,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '1 Whole Can Chipotle Pepper in Adobo Sauce',
      name: 'Whole Can Chipotle Pepper in Adobo Sauce',
      quantity: 1,
      scalable: false,
      hold: BarrioIngredientHold.noUnit,
    ),
    BarrioRecipeIngredient(
      raw: '130g Cup Tomato Paste',
      name: 'Cup Tomato Paste',
      quantity: 130,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '120g Apple Cider Vinegar',
      name: 'Apple Cider Vinegar',
      quantity: 120,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '10g Mexican Oregano',
      name: 'Mexican Oregano',
      quantity: 10,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '6g Ground Cumin',
      name: 'Ground Cumin',
      quantity: 6,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '10g Garlic Powder',
      name: 'Garlic Powder',
      quantity: 10,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '480g Chicken Stock',
      name: 'Chicken Stock',
      quantity: 480,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '1360g White Onion Thinly Sliced',
      name: 'White Onion Thinly Sliced',
      quantity: 1360,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '65g Garlic Minced',
      name: 'Garlic Minced',
      quantity: 65,
      unit: 'g',
      scalable: true,
    ),
  ],
  'training_recipes_c13_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '11lbs Potatoes, unpeeled ( washed and dried)',
      name: 'Potatoes, unpeeled ( washed and dried)',
      quantity: 11,
      unit: 'lbs',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '120mL water split between pans',
      name: 'water split between pans',
      quantity: 120,
      unit: 'mL',
      scalable: true,
    ),
  ],
  'training_recipes_c14_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '3200g Mayo',
      name: 'Mayo',
      quantity: 3200,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '200g Chipotle (One 7oz Can)',
      name: 'Chipotle (One 7oz Can)',
      quantity: 200,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '120g Lime Juice',
      name: 'Lime Juice',
      quantity: 120,
      unit: 'g',
      scalable: true,
    ),
  ],
  'training_recipes_c15_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '1400g Ketchup',
      name: 'Ketchup',
      quantity: 1400,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '500g Clamato',
      name: 'Clamato',
      quantity: 500,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '385g Orange Juice',
      name: 'Orange Juice',
      quantity: 385,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '318g Lime Juice',
      name: 'Lime Juice',
      quantity: 318,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '234g Jarritos Mandarina',
      name: 'Jarritos Mandarina',
      quantity: 234,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '80g Valentina',
      name: 'Valentina',
      quantity: 80,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '50g Garlic ( Microplaned)',
      name: 'Garlic ( Microplaned)',
      quantity: 50,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '45g Worcestershire Sauce',
      name: 'Worcestershire Sauce',
      quantity: 45,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '15g Salt',
      name: 'Salt',
      quantity: 15,
      unit: 'g',
      scalable: true,
    ),
  ],
  'training_recipes_c16_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '6oz Cod , Bite sized cubes',
      name: 'Cod , Bite sized cubes',
      quantity: 6,
      unit: 'oz',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '½ Cup cornstarch seasoned with salt',
      name: 'cornstarch seasoned with salt',
      quantity: 0.5,
      unit: 'Cup',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '1 cup slaw',
      name: 'slaw',
      quantity: 1,
      unit: 'cup',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '2 Tortillas',
      name: 'Tortillas',
      quantity: 2,
      scalable: false,
      hold: BarrioIngredientHold.noUnit,
    ),
  ],
  'training_recipes_c17_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '750mL Mayo',
      name: 'Mayo',
      quantity: 750,
      unit: 'mL',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '200ml Sweet Chile Sauce',
      name: 'Sweet Chile Sauce',
      quantity: 200,
      unit: 'ml',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '50mL Aji Sauce',
      name: 'Aji Sauce',
      quantity: 50,
      unit: 'mL',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '5g Salt',
      name: 'Salt',
      quantity: 5,
      unit: 'g',
      scalable: true,
    ),
  ],
  'training_recipes_c18_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '700g Cabbage',
      name: 'Cabbage',
      quantity: 700,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '150g Carrots',
      name: 'Carrots',
      quantity: 150,
      unit: 'g',
      scalable: true,
    ),
  ],
  'training_recipes_c19_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '15 Avocados',
      name: 'Avocados',
      quantity: 15,
      scalable: false,
      hold: BarrioIngredientHold.noUnit,
    ),
    BarrioRecipeIngredient(
      raw: '500mL Lime Juice',
      name: 'Lime Juice',
      quantity: 500,
      unit: 'mL',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '5 jalapeños (Deseeded)',
      name: 'jalapeños (Deseeded)',
      quantity: 5,
      scalable: false,
      hold: BarrioIngredientHold.noUnit,
    ),
    BarrioRecipeIngredient(
      raw: '1/4 Bunch cilantro',
      name: 'cilantro',
      quantity: 0.25,
      unit: 'Bunch',
      scalable: false,
      hold: BarrioIngredientHold.wholeItemCount,
    ),
    BarrioRecipeIngredient(
      raw: '1 Large Red Onion Small Dice',
      name: 'Large Red Onion Small Dice',
      quantity: 1,
      scalable: false,
      hold: BarrioIngredientHold.noUnit,
    ),
    BarrioRecipeIngredient(
      raw: 'L5S TT',
      name: 'L5S TT',
      scalable: false,
      hold: BarrioIngredientHold.noQuantity,
    ),
    BarrioRecipeIngredient(
      raw: 'Salt TT',
      name: 'Salt TT',
      scalable: false,
      hold: BarrioIngredientHold.noQuantity,
    ),
  ],
  'training_recipes_c21_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '57g Garlic Cloves ( Crushed)',
      name: 'Garlic Cloves ( Crushed)',
      quantity: 57,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '85g Cilantro Stems',
      name: 'Cilantro Stems',
      quantity: 85,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '3 piece Bay Leaves',
      name: 'Bay Leaves',
      quantity: 3,
      unit: 'piece',
      scalable: false,
      hold: BarrioIngredientHold.wholeItemCount,
    ),
    BarrioRecipeIngredient(
      raw: '70g Ginger ( Skin on, quartered then thinly sliced)',
      name: 'Ginger ( Skin on, quartered then thinly sliced)',
      quantity: 70,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '28g Sweet Paprika',
      name: 'Sweet Paprika',
      quantity: 28,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '397mL Soy Sauce',
      name: 'Soy Sauce',
      quantity: 397,
      unit: 'mL',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '65g Aji Panca',
      name: 'Aji Panca',
      quantity: 65,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '7g Mexican Oregano',
      name: 'Mexican Oregano',
      quantity: 7,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '28mL Rice Vinegar',
      name: 'Rice Vinegar',
      quantity: 28,
      unit: 'mL',
      scalable: true,
    ),
  ],
  'training_recipes_c22_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '12 Eggs',
      name: 'Eggs',
      quantity: 12,
      scalable: false,
      hold: BarrioIngredientHold.noUnit,
    ),
  ],
  'training_recipes_c23_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '500mL Mirin',
      name: 'Mirin',
      quantity: 500,
      unit: 'mL',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '500mL Apple Cider Vinegar',
      name: 'Apple Cider Vinegar',
      quantity: 500,
      unit: 'mL',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '591mL Rice Wine Vinegar ( 1 Bottle)',
      name: 'Rice Wine Vinegar ( 1 Bottle)',
      quantity: 591,
      unit: 'mL',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '125mL Soy Sauce',
      name: 'Soy Sauce',
      quantity: 125,
      unit: 'mL',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: 'The Peel of One Orange',
      name: 'The Peel of One Orange',
      scalable: false,
      hold: BarrioIngredientHold.noQuantity,
    ),
    BarrioRecipeIngredient(
      raw: '2tsp Chili Flakes',
      name: 'Chili Flakes',
      quantity: 2,
      unit: 'tsp',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '3 tbsp White Sugar',
      name: 'White Sugar',
      quantity: 3,
      unit: 'tbsp',
      scalable: true,
    ),
  ],
  'training_recipes_c24_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '5lbs Poblano Pepper',
      name: 'Poblano Pepper',
      quantity: 5,
      unit: 'lbs',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '1134g Sour Cream',
      name: 'Sour Cream',
      quantity: 1134,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '12 Bunches Cilantro',
      name: 'Cilantro',
      quantity: 12,
      unit: 'Bunches',
      scalable: false,
      hold: BarrioIngredientHold.wholeItemCount,
    ),
    BarrioRecipeIngredient(
      raw: '45g Paprika',
      name: 'Paprika',
      quantity: 45,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '23 Limes (Juiced)',
      name: 'Limes (Juiced)',
      quantity: 23,
      scalable: false,
      hold: BarrioIngredientHold.noUnit,
    ),
    BarrioRecipeIngredient(
      raw: '454g Garlic',
      name: 'Garlic',
      quantity: 454,
      unit: 'g',
      scalable: true,
    ),
  ],
  'training_recipes_c25_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '80g Aji Panca',
      name: 'Aji Panca',
      quantity: 80,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '400g Roasted Red Pepper',
      name: 'Roasted Red Pepper',
      quantity: 400,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '70g Garlic',
      name: 'Garlic',
      quantity: 70,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '14g Black Pepper',
      name: 'Black Pepper',
      quantity: 14,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '15g Cumin',
      name: 'Cumin',
      quantity: 15,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '6g Mexican Oregano',
      name: 'Mexican Oregano',
      quantity: 6,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '48g Kosher Salt',
      name: 'Kosher Salt',
      quantity: 48,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '478g Red Wine Vinegar',
      name: 'Red Wine Vinegar',
      quantity: 478,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '654 Canola Oil',
      name: 'Canola Oil',
      quantity: 654,
      scalable: false,
      hold: BarrioIngredientHold.noUnit,
    ),
  ],
  'training_recipes_c26_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '2.5kg Pork Belly ( Half a Slab)',
      name: 'Pork Belly ( Half a Slab)',
      quantity: 2.5,
      unit: 'kg',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '250g Soy Sauce',
      name: 'Soy Sauce',
      quantity: 250,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '200g Orange Juice',
      name: 'Orange Juice',
      quantity: 200,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '50g Ginger',
      name: 'Ginger',
      quantity: 50,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '60g Green Onion',
      name: 'Green Onion',
      quantity: 60,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '30g Sesame Oil',
      name: 'Sesame Oil',
      quantity: 30,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '10g Black Peppercorn',
      name: 'Black Peppercorn',
      quantity: 10,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '8 piece Star Anise',
      name: 'Star Anise',
      quantity: 8,
      unit: 'piece',
      scalable: false,
      hold: BarrioIngredientHold.wholeItemCount,
    ),
    BarrioRecipeIngredient(
      raw: '6 piece Cinnamon Sticks',
      name: 'Cinnamon Sticks',
      quantity: 6,
      unit: 'piece',
      scalable: false,
      hold: BarrioIngredientHold.wholeItemCount,
    ),
    BarrioRecipeIngredient(
      raw: '1 Bunch Thyme',
      name: 'Thyme',
      quantity: 1,
      unit: 'Bunch',
      scalable: false,
      hold: BarrioIngredientHold.wholeItemCount,
    ),
  ],
  'training_recipes_c27_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '750g Pumpkin Seeds',
      name: 'Pumpkin Seeds',
      quantity: 750,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '210g Unhulled Seeds',
      name: 'Unhulled Seeds',
      quantity: 210,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '9-10 Roma Tomatoes',
      name: 'Roma Tomatoes',
      quantity: 9,
      scalable: false,
      hold: BarrioIngredientHold.range,
    ),
    BarrioRecipeIngredient(
      raw: '225g White Onion',
      name: 'White Onion',
      quantity: 225,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '135g Lime Juice',
      name: 'Lime Juice',
      quantity: 135,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '90g Orange Juice',
      name: 'Orange Juice',
      quantity: 90,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '42g Cilantro',
      name: 'Cilantro',
      quantity: 42,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '(30g) 4-5 Habanero Peppers (deseeded and deribbed)',
      name: '(30g) 4-5 Habanero Peppers (deseeded and deribbed)',
      scalable: false,
      hold: BarrioIngredientHold.noQuantity,
    ),
    BarrioRecipeIngredient(
      raw: '75g Garlic',
      name: 'Garlic',
      quantity: 75,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '30g Salt',
      name: 'Salt',
      quantity: 30,
      unit: 'g',
      scalable: true,
    ),
  ],
  'training_recipes_c28_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '420g Pumpking Seed',
      name: 'Pumpking Seed',
      quantity: 420,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '84g Sesame Seeds',
      name: 'Sesame Seeds',
      quantity: 84,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '42g Corriander Seed',
      name: 'Corriander Seed',
      quantity: 42,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '21g Cumin Seed',
      name: 'Cumin Seed',
      quantity: 21,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '13g Chili Flake',
      name: 'Chili Flake',
      quantity: 13,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '21g Maldon Salt',
      name: 'Maldon Salt',
      quantity: 21,
      unit: 'g',
      scalable: true,
    ),
  ],
  'training_recipes_c29_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '6oz Mushrooms',
      name: 'Mushrooms',
      quantity: 6,
      unit: 'oz',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '150g Mozzarella Cheese',
      name: 'Mozzarella Cheese',
      quantity: 150,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '3 Corn Tortillas',
      name: 'Corn Tortillas',
      quantity: 3,
      scalable: false,
      hold: BarrioIngredientHold.noUnit,
    ),
  ],
  'training_recipes_c30_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '12 Tomatoes',
      name: 'Tomatoes',
      quantity: 12,
      scalable: false,
      hold: BarrioIngredientHold.noUnit,
    ),
    BarrioRecipeIngredient(
      raw: '3 Banana Peppers Small Dice',
      name: 'Banana Peppers Small Dice',
      quantity: 3,
      scalable: false,
      hold: BarrioIngredientHold.noUnit,
    ),
    BarrioRecipeIngredient(
      raw: 'One Large Onion Red Small Dice',
      name: 'One Large Onion Red Small Dice',
      scalable: false,
      hold: BarrioIngredientHold.noQuantity,
    ),
    BarrioRecipeIngredient(
      raw: 'Lime 300mL',
      name: 'Lime 300mL',
      scalable: false,
      hold: BarrioIngredientHold.noQuantity,
    ),
    BarrioRecipeIngredient(
      raw: 'Salt TT',
      name: 'Salt TT',
      scalable: false,
      hold: BarrioIngredientHold.noQuantity,
    ),
    BarrioRecipeIngredient(
      raw: 'L5S TT',
      name: 'L5S TT',
      scalable: false,
      hold: BarrioIngredientHold.noQuantity,
    ),
    BarrioRecipeIngredient(
      raw: '¼ Bunch Cilantro',
      name: 'Cilantro',
      quantity: 0.25,
      unit: 'Bunch',
      scalable: false,
      hold: BarrioIngredientHold.wholeItemCount,
    ),
  ],
  'training_recipes_c31_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '2kg-2.5kg Shrimp Shells',
      name: 'Shrimp Shells',
      quantity: 2,
      unit: 'kg',
      scalable: false,
      hold: BarrioIngredientHold.range,
    ),
    BarrioRecipeIngredient(
      raw: '7L Water',
      name: 'Water',
      quantity: 7,
      unit: 'L',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '670g Tomato Quartered',
      name: 'Tomato Quartered',
      quantity: 670,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '335g White Onion (Large Dice)',
      name: 'White Onion (Large Dice)',
      quantity: 335,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '150g Celery ( Large Dice)',
      name: 'Celery ( Large Dice)',
      quantity: 150,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '170g Cilantro Stems',
      name: 'Cilantro Stems',
      quantity: 170,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '120g Salt',
      name: 'Salt',
      quantity: 120,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '50g Garlic Cloves',
      name: 'Garlic Cloves',
      quantity: 50,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '4g Black Peppercorn',
      name: 'Black Peppercorn',
      quantity: 4,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '1g Coriander Seeds',
      name: 'Coriander Seeds',
      quantity: 1,
      unit: 'g',
      scalable: true,
    ),
    BarrioRecipeIngredient(
      raw: '8 Bay Leaves',
      name: 'Bay Leaves',
      quantity: 8,
      scalable: false,
      hold: BarrioIngredientHold.noUnit,
    ),
  ],
  'training_recipes_c32_u0': <BarrioRecipeIngredient>[
    BarrioRecipeIngredient(
      raw: '2 Bags Yellow Corn Tortilla',
      name: 'Yellow Corn Tortilla',
      quantity: 2,
      unit: 'Bags',
      scalable: false,
      hold: BarrioIngredientHold.containerCount,
    ),
  ],
};
